### ISSUE TITLE
Moving up/down rows no longer working?

### ISSUE THREAD

**Issue by aaronstevens** [Helfima/helmod#103]
I like to adjust the rows to be in a certain order before pinning it to the side, e.g final product at top, and smelter/miner amount at bottom. This used to work fine before but now it has a strange behaviour, for example I clicked up on Red Circuit, this instead shifted it a few rows down, changed the icon of my science pack 3 to Red Circuit, and added -100 to red circuit output.

Any ideas why it's doing this?

![screenshot 2017-10-31 16 47 46](https://user-images.githubusercontent.com/8493061/32237118-ffa1f7b8-be5b-11e7-98d3-e54e2d4f152a.png)

**Comment by Helfima** [comment]
hello perhaps need only a refresh

**Comment by aaronstevens** [comment]
Please disregard, the list was being sorted by Energy column rather than Recipe

**Comment by Helfima** [comment]
np
