### ISSUE TITLE
Allow marking some outputs as secondary

### ISSUE THREAD

**Issue by MalikDrako** [Helfima/helmod#108]
Sometimes recipes output a secondary item that is used in larger quantities higher up, resulting in the primary output being multiplied to fulfill the need for the secondary output. 
I suggest adding some way to mark an output as secondary, which will still let it contribute to the requirements, but wont affect how many times that recipe will be run.

**Comment by Helfima** [comment]
I mean i understand what you want but with a sample it s better
actualy if you want there are product field to reduce production of recipe
![image](https://user-images.githubusercontent.com/20326713/34346641-0ae54624-e9fa-11e7-829a-624a0af2f82f.png)

**Comment by MalikDrako** [comment]
That works as a workaround, but requires manually calculating how much to adjust the output, and needs to be changed whenever the demand for either product changes

**Comment by Helfima** [comment]
I try resolve problem with a matrix solver, it's work but not in a case when your are few same recipe :)

**Comment by Helfima** [comment]
i have added a matrix solver, is it ok?

**Comment by MalikDrako** [comment]
Is the latest version still compatible with .15, or were there breaking changes in the API in .16?

**Comment by Helfima** [comment]
compatible only .16, there are too many changement
