### ISSUE TITLE
How do you add the sort options to table columns?

### ISSUE THREAD

**Issue by aubergine10** [Helfima/helmod#11]
Was looking through your code but couldn't find where they are added...

![region capture 3](https://cloud.githubusercontent.com/assets/1386719/18494107/26502cf8-7a0c-11e6-85f4-d57cb1178037.png)

Are they just normal buttons in the table, or is there a special way to add table header row with sorting options?

**Comment by Helfima** [comment]
@see https://github.com/Helfima/helmod/blob/master/planner/plannerResult.lua#L575

this select the style for display

```
local style = "helmod_button-sorted-none"
	if model.order.name == "index" and model.order.ascendant then style = "helmod_button-sorted-up" end
	if model.order.name == "index" and not(model.order.ascendant) then style = "helmod_button-sorted-down" end
```
this is the button to switch with action=change-sort and column=index
```
	self:addGuiButton(guiRecipe, self:classname().."=change-sort=ID=", "index", style)
```
after apply the values and refresh display
@see https://github.com/Helfima/helmod/blob/master/planner/plannerResult.lua#L220

i have implemented a spairs function to use custom pairs
@see https://github.com/Helfima/helmod/blob/master/planner/plannerResult.lua#L393
@see https://github.com/Helfima/helmod/blob/master/core/global.lua

i use global variable to memory the column order

I like this https://github.com/Helfima/helmod/blob/master/core/class.lua
and if know well the lua code
@see https://github.com/Helfima/helmod/blob/master/planner/plannerDialog.lua#L90
i mean can made better to parse in one line my parameters

**Comment by aubergine10** [comment]
Thanks for the infos! 👍
