### ISSUE TITLE
Low resolution makes the mod cannot use

### ISSUE THREAD

**Issue by TSStudio** [Helfima/helmod#114]
My resolution is 1366x768,The game is windowed.I can't even see the close button

**Comment by Helfima** [comment]
hello
check your scale is 100%
![image](https://user-images.githubusercontent.com/20326713/35110821-04c88bba-fc7a-11e7-92d0-8b1a1367cfdb.png)

or you can set lower size in mod settings
![image](https://user-images.githubusercontent.com/20326713/35110947-53bd4198-fc7a-11e7-85a4-bdddd3110005.png)
