### ISSUE TITLE
auto compute seems off in some cases

### ISSUE THREAD

**Issue by finndibaenn** [Helfima/helmod#116]
I'm playing with Seablock (on 0.15) and Helmod 0.6.10 and enjoy this mod a lot.

In some (rare) cases though, it seems the auto compute of quantities seems incorrect.

![image](https://user-images.githubusercontent.com/4275679/35238968-6d32359c-ffaf-11e7-9a28-c5bb66c5cad7.png)
In the example above, i clicked on the 3rd row/1st ingredient to add the last row, but quantities don't match. It requires 6/s but decided to produce 100/s.

**Comment by MalikDrako** [comment]
Is one of the outputs used somewhere else? Sounds like the same problem I was having in #108

**Comment by finndibaenn** [comment]
not in that production block.
My understanding is that a production block is not trying to match demand from other blocks of other resources than the one it was created for, correct ?

This block is for the copper tungsten plate, the "faulty" row has 2 outputs, the powder and water, water is not used in the block

![image](https://user-images.githubusercontent.com/4275679/35264770-429b42a0-001e-11e8-9615-26045b26a358.png)

**Comment by MalikDrako** [comment]
Is the "L" button selected for the line for the block itself? I believe that causes it to match demand

**Comment by Helfima** [comment]
Hey, I mean your are a water purified demand in other block
![image](https://user-images.githubusercontent.com/20326713/35468005-bfc63b4a-0316-11e8-9fb7-a14aea894fbe.png)
if you active debug you can see the input parameter
![image](https://user-images.githubusercontent.com/20326713/35468017-fc027542-0316-11e8-8273-9173760218e0.png)

**Comment by finndibaenn** [comment]
Oh, Merci.

I thought when you created production blcoks by selecting on a require ingredient in the overall production line, that block would only try to match needs for that particular product.

Now that I understand what's going on it will help a lot, 
Thanks a lot for the explanaiton

**Comment by Helfima** [comment]
perhaps my help panel is not well, my english is poor
