### ISSUE TITLE
"Show disable" and "Show hidden" no longer work

### ISSUE THREAD

**Issue by emk** [Helfima/helmod#117]
(Merci pour un mod super utile ! J'utilise Helmod pour un jeu avex Bob's mods, et ça m'aide beaucoup avec les circuits. C'est un vrai plaisir.)

With Factorio 0.16.20 and Hemod 0.7.5, checking either of these buttons in the recipe selector and hitting Apply does nothing. I'm running on 64-bit Linux. Please let me know if I can help troubleshoot this in any way, and thank you!

I'll patch my local copy with something hackish, so there's no rush. Merci !

**Comment by Helfima** [comment]
il y avait un bug sur les events des checkbox qui s'exécutait 2 fois :) et ceci est apparu après factorio 0.16.14

les checkbox ne réagissaient pas avec l'event on_gui_click et j'avais mis l'event on_gui_checked_state_changed pour que ca fonctionne mais ils ont remis l'event on_gui_click et donc ca réagissait 2 fois et on ne voyait pas tellement c'est rapide

résolu en 0.7.6
