### ISSUE TITLE
DyWorld compatibility

### ISSUE THREAD

**Issue by TehFreek** [Helfima/helmod#118]
Some issues required for full compatibility with [DyWorld](https://mods.factorio.com/mods/Dysoch/DyWorld):

- Material system productivity modules not being allowed in recipes where they are valid
- No handling of molten rock boilers (metallurgy temperature requirements, boiler heating rate and power usage)
- Can't select material system miners as a source for dirty ore
- Support for using recyclers with water to generate sludge water

**Comment by Helfima** [comment]
I don't know that mod, I need detailed explanation on each point and how it work

**Comment by TehFreek** [comment]
> Material system productivity modules not being allowed in recipes where they are valid

DyWorld adds a number of materials to Factorio, some metallic (aluminum, gold, tungsten, etc.), some non-metallic (rubber, obsidian, chitin). It removes the normal assemblers, three module types, chests, belts, pipes, construction and logistic bots, roboports, etc. and replaces them with a single tier of each of the items made of the different materials. This is the "Material System".

Helmod currently by default disallows e.g. Obsidian productivity modules from being placed in a factory (with 'Unknown key: "item-limitation."' on hover), regardless of the actual recipe being used. There is no such limitation for speed or efficiency modules.

It also shows the vanilla modules (Speed module, Speed module 2, etc.) even though they aren't available with the mod.

> No handling of molten rock boilers (metallurgy temperature requirements, boiler heating rate and power usage)

DyWorld adds Metallurgy, which allows you to melt rock in a blast furnace and add metal ore to it in order to forge metal plates with a higher yield than dumping the ore into a furnace, but the molten rock needs to be brought to a certain minimum temperature specified in the recipe before the metal can be added in a separate blast furnace. There are five boilers which bring the molten rock up to a temperature of n*1000deg and use n*500kW of electricity, where n is between 1 and 5 inclusive.

The boilers don't show up at all in Helmod, which is not entirely surprising since this mechanism is unlike the parts of vanilla that it does handle.

> Can't select material system miners as a source for dirty ore

The Material System also allows crafting burner and electric miners from the materials, each of which gives the miner a different speed and mining power (ore deposits with a given hardness require a miner with at least that hardness in order to be mined).

Helmod only shows the vanilla miners as sources for ore, even though those don't exist in DyWorld.

The "dirty ore" part comes from the fact that when ore is mined it is "dirty", and must be cleaned before it can be melted in a blast furnace. Helmod does currently handle the washing part correctly, including the byproducts.

> Support for using recyclers with water to generate sludge water

Sludge water is a byproduct of a few recipes in DyWorld, but it is also an ingredient in a couple of them, most notably blue science fluid (which then gets combined with glass to produce blue science packs). The best source for sludge water is the recycler, which turns one item or 50 fluid into 25 sludge water, and the best source for fluid is an offshore pump.

Since Helmod doesn't support water recycling, it will attempt to get the sludge water from other recipes such as melting rock in a blast furnace or washing dirty ore, with hilariously bad results. You can see this in action by examining the attached solution with the chromium washing recipe at the bottom unlinked and comparing the results after linking.

[Helmod DyWorld science example.txt](https://github.com/Helfima/helmod/files/1686682/Helmod.DyWorld.science.example.txt)

**Comment by Helfima** [comment]
i have add rule to filter the crafting machine
see admin tab if you want add other rules
