### ISSUE TITLE
Window too wide/not draggable

### ISSUE THREAD

**Issue by keryja** [Helfima/helmod#12]
I'm playing Factorio with quite a few addons that add buttons to the top left, as a result helmod gets pushed to the right so far I can't actually access the tab that opens on the right:

![2016-10-10_18-20-42](https://cloud.githubusercontent.com/assets/16323751/19243138/9f3b25fe-8f16-11e6-93d1-98277635ce77.png)

The easiest solution (I think) is to have the window draggable, then you can just drag it to where you can see it.

**Comment by Helfima** [comment]
ok, i try find a solution

**Comment by Helfima** [comment]
i have moved gui on the center
we can't have a draggable panel

**Comment by johntron** [comment]
I have the same issue with no mods installed and default GUI scale (image is only cropped along the bottom)
<img width="1438" alt="screen shot 2016-11-15 at 7 58 38 pm" src="https://cloud.githubusercontent.com/assets/131961/20331892/f546202a-ab6d-11e6-858a-2c65421a2a30.png">

**Comment by Omnifarious** [comment]
I have the exact same issue as @johntron, though my display is 15" and 3840x2160. Setting the GUI scale really high allows me to see a bit more of the window, but no scale setting lets me see all of it.
