### ISSUE TITLE
Desync when editing outputs

### ISSUE THREAD

**Issue by Fuyukai** [Helfima/helmod#121]
When editing the amount of output of a product in a production line, a desync happens.

Using latest Helmod 0.7.6. Not sure if this is specifically a helmod issue or something else messing with it, but it happens consistently for me when clicking the output icon.

**Comment by Helfima** [comment]
perhaps fixed in v0.7.7
if redesync put log file

**Comment by Esterni** [comment]
Hey Helfima, got a desync with current mod update. If it happens again ill try to get you a log file

**Comment by Helfima** [comment]
put desync-reportxxxx.zip file it s better
