### ISSUE TITLE
Can't connect to multiplayer: mod command handlers are not identical

### ISSUE THREAD

**Issue by domi1294** [Helfima/helmod#123]
Hello, we got the issue of no being able to connect to my hosted game while helmod is enabled, see attached screenshot for the exact error message. We made sure that everyone was both on the latest version of factorio and the latest version of helmod. We also tried to disable all other mods but even with only helmod enabled we still get the issue.
I attached log files of a friend trying to connect to my hosted game and my own logfile of hosting the game. If there is anything else we could try or can do to help with fixing this bug feel free to message me either here or on Discord @ Domi#6969

Screenshot of error message:
![image](https://user-images.githubusercontent.com/3752386/36285624-90b89f96-12ac-11e8-83c7-59bdcaa4d809.png)

Log of a friend trying to connect to my hosted game: [factorio-current.log](https://github.com/Helfima/helmod/files/1729662/factorio-current.log)
Log of me hosting said game: [factorio-current.log](https://github.com/Helfima/helmod/files/1729676/factorio-current.log)

**Comment by domi1294** [comment]
I fixed it by saving the map once and loading it again, the issue only appears when helmod is added to a map that didn't have it before or on a fresh map, but just saving and loading seems to fix it 100% of the time from my testing.

**Comment by katanakiwi** [comment]
Issue is not yet resolved, should remain open.
