### ISSUE TITLE
Calculate required amount of mining drills

### ISSUE THREAD

**Issue by noresistence** [Helfima/helmod#125]
Example: I want to know how much mining drills are required to mine 100 Copper Ore per Second.

Steps to reproduce:
- Add a production Line
- Add a recipe, choose "copper ore"

Problem: It is not possible to set the amount of copper; the production block is useless.

I guess this is because Output and Input are both copper and the mod just removes both, such that it is not possible to access the dialog for the amount of copper. This kind of behaviour probably makes sense for other products, but not for pure resources, as there is no differentiation between mined and unmined resources.

The solution would probably be either to ignore equal input and output for production blocks that contain only pure resources, or to introduce a differentiation between mined and unmined resources.

![grafik](https://user-images.githubusercontent.com/6641873/36594903-5aa00f1c-18a0-11e8-9ea4-0ffc1b384e5f.png)

**Comment by IronHair** [comment]
same problem, its especially tough to understand how to use this to a new player

**Comment by Helfima** [comment]
fixed, now we can add a ore recipe and put the product value
