### ISSUE TITLE
Connecting via RCON causes server crash.

### ISSUE THREAD

**Issue by cjmwid** [Helfima/helmod#126]
>192.355 Info RemoteCommandProcessor.cpp:229: New RCON connection from 6d808c64145549bf7ad83cbd60a7caef2ef2045f

>192.369 Error MainLoop.cpp:1029: Exception at tick 15413778: Error while running event helmod::on_console_command (ID 72) __helmod__/model/Player.lua:35: bad argument #2 to '__index' (string expected, got nil)

>192.369 Error ServerMultiplayerManager.cpp:96: MultiplayerManager failed: "Error while running event helmod::on_console_command (ID 72) __helmod__/model/Player.lua:35: bad argument #2 to '__index' (string expected, got nil)"
 
>192.369 Info ServerMultiplayerManager.cpp:698: mapTick(15413778) changing state from(InGame) to(Failed)

Simply connected to the server via RCON Client and instant crash

**Comment by Helfima** [comment]
what is RCON client?
