### ISSUE TITLE
0.16.27 Not Multiplayer Compatible

### ISSUE THREAD

**Issue by Tiogshi** [Helfima/helmod#127]
I'm fairly sure the mod is supposed to be; I used it in 0.15 a fair bit, and saw it had sharing settings... but when starting a map in 0.16.27, I got a message saying the hooks weren't identical between clients, and no-one was able to connect to my server.

Known issue, or unexpected bug?

**Comment by Tiogshi** [comment]
Forgot: current mod version, 0.7.6 is the one tested.

**Comment by katanakiwi** [comment]
Similar to closed issue 123:
https://github.com/Helfima/helmod/issues/123
That should be reopened and this closed.

**Comment by Tiogshi** [comment]
Re-attempted; I can confirm that the error message is that shown in issue #123. I did not attempt the save/reload workaround.

From the error message, my gut-reaction guess to the cause is that a function which uses upvalues from the parent lexical scope is being installed as a hook; thus, a Lua heap-allocated function (which aren't comparable between Lua State instances), not a "static" global or local function (which can be compared, because identical Lua source produces identical Lua bytecode). I'll do some snooping around for such later.

**Comment by katanakiwi** [comment]
I did try the workaround and it did work with a friend. Not tested on 0.16.28 though.

**Comment by Helfima** [comment]
fixed v0.7.7
