### ISSUE TITLE
Please support consumers as well as producers

### ISSUE THREAD

**Issue by mrvn** [Helfima/helmod#133]
In a production block you generally have a product with a given amount, e.g. iron gear wheel For that you need resources to build it, e.g. iron plate. So you add a producer of iron plates from iron ore and helmod will compute the right amount of iron ore needed.

Playing with angels mods though you have a lot of process that have waste products. For example sulfuric waste water is a common waste product. Sulfuric waste water can be processed into sulfur, purified water and mineralized water. Sulfur can be used to make sulfuric acid and together with the 2 other liquids those are usually inputs for the production block. It's a basic sulfur loop appearing many times in angles mods.

Now the point I'm trying to make is that I want to process all sulfuric waste water. Some of the sulfur might get fed back into the loop and any left over sulfur is an excess output. I don't know how much sulfur will be left so I can't specify this as a producer of sulfur. I don't see any way to tell helmod to use as many sulfur waste water processing as there is sulfuric waste water instead of how much sulfur/purified water/mineralized water is needed in the loop. I can't tell helmod that the recipe is a consume of left over sulfuric waste water instead of a producer of sulfur.

**Comment by minno726** [comment]
As a workaround, you can adjust the percentages on various recipes in the production line. For example, if you add a "sulfuric waste water purification" step to an ore filtration loop, but it decides you need to have sulfuric waste water as an input, you can reduce the percentage on that step until that input disappears.

**Comment by KiwiHawk** [comment]
Yes please! This would be very useful. 

It can be done by setting percentages, however it can be difficult to get the exact percentage so that all of the the input is used up. I've had to set percentages to 4 decimal places - mostly by trial and error.

Also if I change the output of the production chain, I often have to recalculate the percentages!

**Comment by Helfima** [comment]
I mean It is ok v0.10.20
