### ISSUE TITLE
Please support marking main and side products in a recipe

### ISSUE THREAD

**Issue by mrvn** [Helfima/helmod#134]
Sometimes in a production block I have multiple recipes to make something. For example angels has 2 recipes to make coke. One just makes coke and the other coke and sulfuric waste water. Now if my production block needs coke and sulfuric acid I want to use enough of the second recipe for coke+sulfuric waste water to make the needed sulfuric acid. For the rest I want to use the plain coke recipe.

As is I have to add both recipes and then set the % for the first to produce the right amounts. I have to manually balance the two recipes.

Instead I would like to add the coke+sulfuric waste water recipe first and then tell helmod that this is only used to make sulfuric waste water. The side product of coke is not to be used to calculate the amount for this recipe. Some coke might be produced by it but whatever coke is needed on top of that will use the later pure coke recipe (or remain as needed input). This should help helmod automatically balance recipes better.

**Comment by KiwiHawk** [comment]
Yes please! This would be very useful.

**Comment by Helfima** [comment]
added in v0.10.20
