### ISSUE TITLE
Issues with Basic Sea Block

### ISSUE THREAD

**Issue by TehFreek** [Helfima/helmod#138]
With [Basic Sea Block](https://mods.factorio.com/mods/euigrp/BasicSeaBlock) the factories for Mineral Extraction and 400×Algae Sludge are both assumed to be crafted in Assembling Machine 1 instead of Filtration Plant and Algae Pit respectively. There is no way to select the correct factory.

Iron Ore via Filtration Plant:

    H4sIAAAAAAAA/+VUTY/iMAz9K6jnFLXd2dGuRvkHe+I6QlVIXYjIR5UmwyDU/75OQguIgpbz9tIkdp7fsx03ZiENZ3JR05NoaKZMA7KuMmIOGizNHOxaC7DP
    yAb99j09xX9dJvfzJiOaKaBZL32zhVxYo3P4dpZxN4PEjdeOlqQzBzQUROithUaAdgg/kM6axvOw/swikrGQrenJHTsMIRyoMdxkJUxFzB+kd8wBYqcYxUA+
    s75D5LwV0oGdx7nxGLHKO6yBWOCiA2S2OutfoXShG/hGGU9SkEKm26P+YhQqjMYgLToae6SnBBPIWBZseSeZnjAS7REBMLPbI30vwkdQBjQIJYUSwYq19BJi
    TqFtIaY0+Vxifwl3xC03uveqi1wwaQm3dsYxidYIWE8p3QBD/5Fp2j3l9/Yr8uNGbQx9m6SWy2qW69Pgt9aBrKpzJaqxEiW5pBBsfmCxqq+XgPU9qI3E7swV
    4zuhIS+fyvx9VYVi+fO/qsMwPQOvMWV7FOesh3h+87ot9MZbnkLECRBXTqjw1L5wG7RnxfJ9WWRnOn9E71aA06Pf0ZbJHtIwqkXo9lTSsK4ejo7bxriMjZlc
    zU2MdL2anRZzEAPBIioWWinlWECkdPeo1y8990BttinXL7fsMHZPGOj/2kZ46a49AqttWDKUieeMc6+8DLuJ1OXoccaNZDbvmAZ5UXN9+PCiA6Zy0FvUenXz
    +nReyvBhwXmrF/UH6OYvNonjtQcHAAA=

Wood via Algae Pit:

    H4sIAAAAAAAA/+1V247aMBD9FZRnByVAq1Yr/0GfeF2tIseZgIUvkS9LEcq/dxzHLCtYtFXVp5aX+DbH55zxDJ1ZSMOZXDT0LDpaKNOBbNYFMUcNlhYe9r0F
    OBSkxXMHR8/Tt6nT8XlSEM0U0GIIcihbw2x3B4CboD2tyWCOuFERoXcWOgHaI+pIBmu6wOP4aExHz/40IKLwoDJ6XC8IUzOO88wDfhNuNY7EAhcDIMJ2prdF
    ZkJ38BOvu2WYbkhBmV6VeQijEbtn3Bt7oucUzeSOQdkzq3J04pdjASXvTrSu4o+4AaBDECmUiLvobZAwiYW+h0lrOvN266vwJ5xyo11Qw8SiGmfcxhvPJO5O
    gE3WTVpgeD5zTLOH/DbfJn7cqNbQzUVkvVzd5frw8ve7I9muZutX2fo6W2/BuXKy8L/3f8f79ez9Onu/mr1vsQS7P/DeOVCtxIotFeN7oaGsH6r8fpWEavnl
    n0rDeGk5QaNlBxTnbYBp/V3Hw3owwfJ0xdQVp5EXKra1V5xG7UW1/LqsipnOD+H8FrCjuj3tmXSQ+nIj4mNPKY3jzU07fV+LqZXe8QdZouuKxdwnU0Tk93xd
    fi+fLMmRPN9/OS+//a7GnOL4B/TZXGPQTQ4jq10cMpSG64zzoIKMswupt6UPZTkjmS0HpkG+qble/DDQA1Ml6B1qvYq8Xr0vZXyy4IPVi+YJdPcLf45zPbcH
    AAA=

**Comment by Helfima** [comment]
fixed in the next release
