### ISSUE TITLE
Window too big on 4k monitors

### ISSUE THREAD

**Issue by abassouk** [Helfima/helmod#139]
The Helmod window is too big and the menus are outside the visible area if the Factorio window is above a certain size (f.e. on a 4k monitor).

Window scaling seems a bit off, as the window is too small and the tabs get cut off if the Factorio window is below a certain size.

**Comment by Helfima** [comment]
you can modify factor size of panel in mod settings
![image](https://user-images.githubusercontent.com/20326713/39770775-45a2b5b2-52f0-11e8-91bf-de1cd9f2d221.png)

**Comment by mageman1842** [comment]
how do i get the production block to drag left right if recipe is too wide to fit?
