### ISSUE TITLE
Add support for multiple identical products in recipes.

### ISSUE THREAD

**Issue by minno726** [Helfima/helmod#141]
In Angel's bioprocessing, there are "seed activation" recipes that take output both a guaranteed five and a 5% chance of one of the same item. Right now Helmod gives an error when you try to add such a recipe to a production block. It might work to handle it by adding together all outputs with the same product, so treating the recipe that says "100% chance of 5 seeds, 5% chance of 1 seed" like it said "5.05 seeds".

**Comment by minno726** [comment]
@Helfima do you mind if I try implementing this and #140 myself?

**Comment by Helfima** [comment]
yes it's a problem
if you want try implementing something, you can do pull requests
for this issue there a 2 way
fix the name of gui element or merge the same product
