### ISSUE TITLE
Helmod window stuck open

### ISSUE THREAD

**Issue by btbenedi** [Helfima/helmod#143]
So I moved Helmod from center to top, and now it won't close, I tried changing it back to center, and now when I hit the open UI key, a new instance opens in center and the top one is still there. Clicking the close icon or key, doesn't do anything to the one stuck to stop.

Is there a console command I could use to clear it?

**Comment by btbenedi** [comment]
I got it, switched to Top, which closed that one and opened the one in center...then put setting back to center, and then i'm able to close that one. But still seems like something that could be address, close UI button should close any active helmod windows

**Comment by Helfima** [comment]
fixed in the next release
