### ISSUE TITLE
Mining recipe result is incorrect for some modded resources

### ISSUE THREAD

**Issue by minno726** [Helfima/helmod#144]
Steps to reproduce:

Install Angel's infinite ores.

Make a production block making iron plated from iron ore.

Add the mining recipe for infinite-iron-ore to the block.

Note that it does not count as satisfying the iron ore needed by the other recipe.

**Comment by minno726** [comment]
Patch to fix this (still no internet connection on my PC):

```diff -Naru helmod_0.7.10/model/RecipePrototype.lua helmod_0.7.11/model/RecipePrototype.lua
--- helmod_0.7.10/model/RecipePrototype.lua     2018-06-02 23:09:48.448180900 -0500
+++ helmod_0.7.11/model/RecipePrototype.lua     2018-06-02 21:45:39.360882400 -0500
@@ -177,7 +177,13 @@
     if lua_type == "recipe" then
       return lua_prototype.products
     elseif lua_type == "resource" then
-      return {{name=lua_prototype.name, type="item", amount=1}}
+      local products = {}
+      if lua_prototype.mineable_properties.products ~= nil then
+        for _,result in pairs(lua_prototype.mineable_properties.products) do
+          table.insert(products, {name=result.name, type="item", amount=1})
+        end
+      end
+      return products
     elseif lua_type == "fluid" then
       return {{name=lua_prototype.name, type="fluid", amount=1}}
     elseif lua_type == "technology" then
```

For modded resources, the name of the ore that is produced is not necessarily the same as the name of the recipe.

**Comment by Helfima** [comment]
be careful I have change some files, I mean your RecipePrototype.lua is out-of-date
but nice idea, I have implemented and the selector propose the choose :)

![image](https://user-images.githubusercontent.com/20326713/40886294-59e0ead6-6735-11e8-90d1-ed2617317477.png)
I push fix soon
