### ISSUE TITLE
Main window opens in wrong position on large resolution screens.

### ISSUE THREAD

**Issue by Stierno** [Helfima/helmod#146]
When playing in windowed mode on a 1440p monitor, the Helmod window is too far to the left (see attached). I have a dual monitor setup with a 1080p monitor, and it looks fine in that with windowed mode. In addition, if Factorio is open on the 1080p screen, and I then proceed to move it to the 1440p screen, the Helmod window also looks fine.

![helmod-bug](https://user-images.githubusercontent.com/40446760/41694098-2e536b40-74ce-11e8-9681-f3fdaf0f2173.PNG)

**Comment by Helfima** [comment]
there are 2 parameters in options/mod/per user if you want reduce size

**Comment by Stierno** [comment]
Ah ok. I'll check that out the next time I play.

**Comment by Stierno** [comment]
Thanks for the tip. I changed the Width Display Scale from default .85 to .8 and that fixed the problem.
