### ISSUE TITLE
Poor performance with many mods loaded

### ISSUE THREAD

**Issue by Pyro93735** [Helfima/helmod#147]
When clicking GUI elements in multiplayer (such as the 'Add a recipe', 'Add Technology') buttons there is a noticeable delay, long enough that when running a server in multiplayer the server instance pauses and "Server is not responding" is displayed at the top. The delay is also observable in singleplayer, it is just not as pronounced. This only occurs when Helmod is loaded alongside a large mod set - removing mods, especially those that add new technologies or recipes reduces the observed delay.

System configuration:
Factorio version 0.16.51
Helmod version 0.7.11
My full mod list: https://pastebin.com/0t9ddK7D
core i5-7600k
16GB DDR3 RAM
2TB SSD
GeForce GTX 970

Steps to reproduce:
1). Load Factorio with all mods enabled
2). Create a new game on "Default" preset
3). Open Helmod main GUI by clicking the icon in the top left
4). Press 'Add a recipe' icon. A slight, but marked delay (~0.5 seconds) should be noticeable
5). Exit to main menu, disable all mods except Helmod. Relaunch Factorio.
6). Repeat steps 2-4. The delay should be significantly less, <0.1 seconds

**Comment by Helfima** [comment]
I know that the display is getting slower with the addition of mod.
unfortunately I can not do better, I added cache but it's still too slow for multiplayer on the generation of selectors.
