### ISSUE TITLE
uncorrect gui 1080+ resolution

### ISSUE THREAD

**Issue by Clor0xD** [Helfima/helmod#148]
I wanted to use your mod for playing with 4k resolution but gui behaves incorrectly. Not centered or scaled

1080 https://www.dropbox.com/s/8u8y79o3cwtpb5g/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202018-06-27%2013.38.15.png?dl=0
4k
https://www.dropbox.com/s/we8tx4h8zwm4yel/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202018-06-27%2013.39.53.png?dl=0

**Comment by Helfima** [comment]
there are 2 parameters in options/mod/per user if you want reduce size when you use 4k
perhaps change 0.85 to 0.8 or lower

**Comment by zoigo** [comment]
Had this issue too.
For example, for my 4K i set those (H/V) to 0.75 and all is fine now (maybe a bit too close to screen border).
(i use windows 10 with 200% UI scaling)
