### ISSUE TITLE
Factory select GUI shows incorrect items

### ISSUE THREAD

**Issue by Moremackles** [Helfima/helmod#149]
Playing with bob's character classes installed alongside Helmod makes Helmod show bob's different players as things that can craft the item you've selected. It would be great if this could be fixed on helmods side of things, but in the meantime is there any way to prevent this from happening? I'm not above editing some code to set it so these aren't the default factories/are on the list at all 
![image](https://user-images.githubusercontent.com/34537855/42427716-0abbdbca-82fe-11e8-91e6-80d07940d6a3.png) Here is the image.

**Comment by Helfima** [comment]
Hello, you can try this

for a quick fix, you can add a excluding rule

Analyzing entity

1. open game options=>Mod settings=>active Display properties tab
2. in game select Properties Tab
3. click on Select Entity
4. choose a bad entity displayed in my selector factory

now you can check properties of entity
i dont know why there are crafting_categories={crafting=true}, this is the problem
see group/subgroup/type (ex: environment/creatures/player)

- if group != production => add a rule on entity-group
- if subgroup != production-machine => add a rule on entity-subgroup
- if type != assembling-machine => add a rule on entity-type
- else add a rule on entity-name

add a new rule

1. open administration tab
2. click Add rule
3. Select Mod=<bobmod>
4. Select Name=production-crafting
5. Select Category=Standard
6. Select Type=entity-group
7. Select Value=>choose the bad item
8. Check Excluded
9. Click Save button

Repeat if necessary on next bad entity
a rule with Category=Standard can be only a excluding rule, you must check Excluded

after it s ok post a screenshot to add your rules in the next release
