### ISSUE TITLE
Production block for inserters

### ISSUE THREAD

**Issue by CzBuCHi** [Helfima/helmod#152]
This can be generalized, but i need to explain it on my special case:

I wanna create production block, that produces inserters and fast inserters. Trouble is when adding fast inserter into block my previously added inserter is consumed by fast inserter and removed from 'output' or marked in 'output' as 'excess product' (which prevents me to change its counts)

What soulf i do, when i wanna to have output of  for ex 4 inserters and 3 fast inserters per sec?

**Comment by Helfima** [comment]
actualy it s impossible
