### ISSUE TITLE
Calculating Output From Input

### ISSUE THREAD

**Issue by changhe3** [Helfima/helmod#154]
I'm recently playing Angel's mods with helmod. I am planning my base for various means of smelting/refining. I can add all the recipes but it seems that only output can be changed. It would be nice if you can get the total output per second given the amount of input and factories.

**Comment by Helfima** [comment]
i not understand what you want!

**Comment by Bubbet** [comment]
He's looking for a way to set a input resource at a rate and have the outputs calculated upon that instead of setting a output rate and having the inputs and other outputs calculated based on that.

I am also looking for that functionality.

**Comment by Firemonkey08** [comment]
Use the max throughput of factories. This is easier to change to get the same input as you want.

**Comment by mafeu102** [comment]
I am having the same problem.

Using the throughput doesn't work if you have a "near-loop" with which I mean I get products I need to put in also out of the process.
I need an input based calculation, so I know how much I need to feed into the "loop" in addition to what I already get out.

It would be nice to have the choice to either calculate by entering input or calculate by defining the output.
Right now I need to tweak the output until I get the desired input.

**Comment by Helfima** [comment]
implemented in v0.9.12
