### ISSUE TITLE
Using the pipette tool over a pinned production block

### ISSUE THREAD

**Issue by TehFreek** [Helfima/helmod#155]
It would be handy if using the pipette tool when hovered over a factory in a pinned production block pulled the factory from inventory.

**Comment by Dimava** [comment]
It also could be a blueprint, like one PickerExtended makes with Ctrl+Q:
(a blueprint with 1 factory with set recipe and modules)

**Comment by Dimava** [comment]
Using pipete tool over *UI* may be impossible, so I would prefer default clicking
I.E. make `assembler icons` in `pinned helmod pane`  buttons that give picker-like blueprint to hand when clicked.

here's blueprint I'm talking about
![img](https://github.com/Nexela/PickerAtheneum/raw/master/web/picker-blueprinter.gif)

**Comment by Dimava** [comment]
Maybe make same for beacons if appliable

**Comment by Helfima** [comment]
set smart pipette is added in v0.9.22
I not sure if I can do better

**Comment by Helfima** [comment]
finally blueprint is use in v0.9.23
