### ISSUE TITLE
Error when trying to have Helmod show coal mining with a burner drill

### ISSUE THREAD

**Issue by Jackalope-Gaming** [Helfima/helmod#156]
I started a Xander's mod run recently and wanted to see what the output of burner mining drills was like, so I brought up Helmod and told it that I wanted coal drilled with a burner mining drill.  It then said in the console that an error occurred where a gui element already had coal in the parent element.  I went about my business and did other things, but when I saved and then pulled the save back up, the game immediately showed the error again and when I click "ok" it simply exits me to the game's main menu.

I have since disabled every other mod besides Helmod and tried again to make Helmod show information about mining coal with a burner drill.  It again showed the exact same error.

The first picture shows what happened with Xander's mod, while the second and third pictures show the errors with only Helmod enabled.

![helmod xander burner drill error](https://user-images.githubusercontent.com/17949121/45853888-251ddb80-bd05-11e8-91af-39478024e2b8.jpg)

![helmod only error1](https://user-images.githubusercontent.com/17949121/45854362-f48b7100-bd07-11e8-8ddd-c1aad6bed690.jpg)

![helmod only error2](https://user-images.githubusercontent.com/17949121/45854368-fce3ac00-bd07-11e8-9f72-239af2b068cd.jpg)

**Comment by Helfima** [comment]
Hello, you have the last version 7.11?

**Comment by Jackalope-Gaming** [comment]
Yes, I am running 7.11.

**Comment by Karmacopper** [comment]
Exact same issue. No other mods, latest versions.

**Comment by Vizjereii** [comment]
oops, seems i made a duplicate issue, https://github.com/Helfima/helmod/issues/161
i included a workaround there too

**Comment by Helfima** [comment]
Fixed in Version 0.8.4
