### ISSUE TITLE
Add info panel that shows number and type of assemblers on a production line or block

### ISSUE THREAD

**Issue by sparky8251** [Helfima/helmod#157]
This tool is great at letting you know how much you need in resource wise to get out the amount you want. It honestly makes stuff so so much easier for me.

That said, if you want Helmod to be a planning assistant there really should to be some way to see how many assemblers of each type each line needs without having to go into each and every menu.

Right now, the process of putting these plans Helmod generates into action is incredibly difficult because there is no easy way to see the assemblers required to obtain the desired output and it involves a lot of busy work that should be necessary.

**Comment by Helfima** [comment]
summary tab shows that for the current production line
but perhaps i can add another right panel

**Comment by alercah** [comment]
It would be cool if you could see how many assemblers were assigned to each recipe, as currently the only way to do this is to look into each block and see.

**Comment by Helfima** [comment]
v0.9.18 Added summary for block (icon near icon for pin panel)
