### ISSUE TITLE
Helfima window off screen

### ISSUE THREAD

**Issue by sctprog** [Helfima/helmod#159]
![untitled](https://user-images.githubusercontent.com/20416661/50577351-ca0b8280-0de3-11e9-8761-f3a88293a9ee.jpg)

The window is nearly entirely off screen and is difficult to close. Really bizarre bug. Only other mod installed is RSO. Not usable in this state.

**Comment by zoigo** [comment]
Look here for a solution: https://github.com/Helfima/helmod/issues/148
"there are 2 parameters in options/mod/per user if you want reduce size when you use 4k
perhaps change 0.85 to 0.8 or lower"

Reason: the scaling for huge resolutions is wrong.
Solution: it is tweakable  in "per player" mod settings.
For example, for my 4K i set those to 0.75 and all is fine now.
(i use windows 10 with 200% UI scaling)
