### ISSUE TITLE
Improved Default Factory logic

### ISSUE THREAD

**Issue by joshstrange** [Helfima/helmod#162]
I am aware of the option in Mod Settings to set the default factory but it only allows for 1, 2, 3, 4, Last. My problem comes from using Bob's mods and there being more tiers so I can't select tier 5 (I don't want 6). 

I understand you cannot be in the business of making your mode work with every other mod but I didn't see an option for default beacon level either and so I'd like to propose 2 possible approaches to this that would also make other parts of this mod easier IMHO.

Option 1
New dropdown option in the Mod Settings for "Best" that would replace the functionality of "Last" and "Last" would be remapped to "Last Selected Factory". (I know this is confusing so different names and not re-mapping would be better but I suck at naming.) This way you store the last clicked factory of each "Type" (furnace, beacon, assembler, chem plant, etc) and when a new recipe is added it defaults to using that factory type (unless you last clicked something like assembler 2 and the thing you are making can only be made in assembler 3, that said this issue will go away in 0.17). 

Option 2
This option would really be Option 1++, in addition to having the default remembered from your last pick it would be nice to be able to save a configuration to a hotbar to the right of the factory/module/beacon selection window. You could "load" the current config to a slot or "read" the hotbar slot (Click to read, shift-click to write). This would be useful for when you are using modules and you want to be able to quickly add all the modules/beacons. Right now this process for me is a ton of clicks (select factory, select modules, select beacon, select modules), late game it becomes 16 clicks per row:

1. Click on factory icon to open sidebar
2. Click on desired factory
3. Click on desired beacon
4. Click on module tab
5. Click on module for factory
6. Click on module for factory
7. Click on module for factory
8. Click on module for factory
9. Click on module for factory (Watch out, we just line-wrapped so you have to move the mouse down)
10. Click on module for factory
11. Click on module for beacon
12. Click on module for beacon
13. Click on module for beacon
14. Click on module for beacon
15. Click on module for beacon (Watch out, we just line-wrapped so you have to move the mouse down)
16. Click on module for beacon
 
TBH I'm really hoping someone comes into this thread and calls me an idiot because there is an easier way but I've read through a number of issues here, the wiki, and the forums and haven't figured out a better way.

Option 2 would allow for doing it all in 3 clicks per row (that is if beacon and factory weren't grouped). It would be really amazing if I could do it for the whole production line. Normally by the time I'm using modules I am putting them in almost everything so I'd love to just "apply" a template to the while production line.

**Comment by rsshurtz** [comment]
Yeah, running into the same frustration playing a Bob's map. I think a shift+right-click shift+left-click would be a nice feature. Or just a way of adjusting what the default Factory/Beacon/Module settings are for any new production lines/blocks/etc.

**Comment by Helfima** [comment]
Added default and propagation factory/module in v0.9.9
