### ISSUE TITLE
Support for 0.17 

### ISSUE THREAD

**Issue by haaakon** [Helfima/helmod#163]
Factorio 0.17 released, would be awesome to have a Helmod version that supports it

**Comment by Igie** [comment]
When loading I get this:

Error loading mods
Failed to load mods: Error while loading gui-style prototype "helmod_textfield" (gui-style$textfield_style): Unknown style name "helmod_textfield" has unknown type: "textfield_style"

**Comment by SakuChou** [comment]
I hope it will be update soon, i can't play without it. Always need the perfect ratio

**Comment by jodli** [comment]
I'm gonna take a look at this 🙈

**Comment by Helfima** [comment]
hello please wait, i work on.

**Comment by SakuChou** [comment]
Okai ,)
I lol use jodli fix (#164) until you got your final version ,)

**Comment by haaakon** [comment]
@SakuChou Is it possible to run that version in a steam version of the game? Just until a stable is released to mod portal

**Comment by SakuChou** [comment]
Yap I did it a hour ago, follow jodli fix in #164 rename your folder and it should work

**Comment by haaakon** [comment]
You mean just rename the fixes locally in my file system?

**Comment by SakuChou** [comment]
Yap, dezip your 0.16 mod, applies fixes, rename the folder why 0.8...something then zip it again

**Comment by jodli** [comment]
You can also just download the repository over [here](https://github.com/jodli/helmod/archive/Factorio_0.17.zip), unzip it and rename the folder to "helmod_0.8.0".
It should also work when it is not zipped at all.

**Comment by OskarPepryk** [comment]
You also need to change mod version in info.json

**Comment by MisterFister2016** [comment]
I note my interest in a mod-portal release of the updated mod would be useful for multiplayer server rentals with embedded mod portal access but slow response times for manual mod updating and / or limited user access to server filesystem.

**Comment by Helfima** [comment]
it's ready to download https://mods.factorio.com/mod/helmod/downloads, the style is not perfect but it works

**Comment by haaakon** [comment]
@Helfima Awesome. I found a small issue in the release though, it seems belt capacity is wrong, it says 13,3333 for yellow belt, 26 for red belt etc. So select container will show wrong numbers

**Comment by Helfima** [comment]
fixed in 0.8.3
