### ISSUE TITLE
Error when loading game with only helmod enabled

### ISSUE THREAD

**Issue by MIZTigerForLife** [Helfima/helmod#165]
Using version 0.8.1, I get this error when trying to load into game even if helmod is the only mod enabled.

__helmod__/control.lua:12: module core.event not found;  no such file __helmod__/core/event.lua no such file __helmod__/core/event.lua no such file D:/Program Files (x86)/Steam/SteamApps/common/Factorio/data/core/lualib/core/event.lua
stack traceback:
	[C]: in function 'require'
	__helmod__/control.lua:12: in main chunk

**Comment by Helfima** [comment]
yes i just fix it
v0.8.2 ready

**Comment by MIZTigerForLife** [comment]
Yes, just downloaded v0.8.2 and that fixed it. 

Thanks.
