### ISSUE TITLE
Desync interacting with UI in multiplayer

### ISSUE THREAD

**Issue by EEsDoNotItNow** [Helfima/helmod#166]
Issue:

After several days of stable game play, helmod suddenly has been causing very consistent desyncs for both players on our server. The following actions have been shown to cause the desyncs. 

- Opening the helmod UI
- Closing the helmod UI
- Adding a production blick
- Removing a production block
- Clicking a different tab within the UI

Desyncs seem to sometimes be for one player, other times for both. Both players are admins if that helps. 

The only connecting event we can point to, is both of us dropped out of multiplayer to work on a creative mod enabled single player world before jumping back into multiplayer. Upon return, both players began to experience very consistent desyncs when interacting with the UI. Rebooting client, deleting achievements, and restarting the server would fix things for a short period of time but eventually desync issue returned. 

Logs:

Log displays no apparent error messages. When set to any level of debug in the Mod Setings menu, a constant stream of 

> Script @helmod/core/logging.lua:80: [ERROR]|HMPlayer|"settings property not found:""debug"

Is displayed during the issues. This happens on any level except "None" as far as I can see. 

Versions:
> Factorio Headless server 0.17.11
> Factorio Windows Client (Steam) 0.17.11
> Factorio Windows Client (Zipped) 0.17.11
> Helmod 0.8.3

Happy to provide more logs or test cases on request.

**Comment by Helfima** [comment]
Hello, you can see nothing with debug mod for desyncs
I have change the event system I mean that the problème
Please wait I work on few changes

**Comment by Helfima** [comment]
Fixed in Version 0.8.4

**Comment by ankenyr** [comment]
This seems to have been reintroduced?
My headless server and client are both at 0.18.79.
helmod is at helmod 0.9.22
Not sure what logs I can provide to help provided the comment above.
When I click on any GUI elements it causes lag where I can no longer move and always results in me desyncing.
To fix this I loaded the save in single player, played a bit with the UI, saved, and transfered the save back to my server. Restarting the server without doing this did not help. This was in a docker container if that helps. I can provide the save if this helps.
