### ISSUE TITLE
scrolling right in recipe

### ISSUE THREAD

**Issue by mageman1842** [Helfima/helmod#167]
is there a way for recipes block to be dragged left or right when the info get's pushed out of the box? i'm trying to see ingredient for Geodes for angel's sorting, but there are 6 products in one recipe and i can not click on the ingredient.

**Comment by Helfima** [comment]
the scroll bar don't appear?
other way in the settings mod you can configure the number recipe

**Comment by dclarkNV** [comment]
I also cannot scroll to the right. It used to work in 0.16

![image](https://user-images.githubusercontent.com/18336112/54800892-939f1000-4c3a-11e9-8d15-670919678667.png)

**Comment by davetclark** [comment]
I also cannot scroll. It worked in 0.16

![image](https://user-images.githubusercontent.com/311092/54800925-bfba9100-4c3a-11e9-8d7a-43dd343cddec.png)

**Comment by SuperSandro2000** [comment]
Does mouse wheel work?

**Comment by davetclark** [comment]
No, mouse wheel doesn't work. While testing the mouse wheel, I discovered that the bottom part of the window marked in red doesn't take mouse events. I can interact with the game behind the window when I'm at the bottom there

![image](https://user-images.githubusercontent.com/311092/54826495-4ea0cb00-4c86-11e9-9733-7c44ddc416f6.png)

**Comment by Helfima** [comment]
Imean is Fixed in Version 0.8.4

**Comment by davetclark** [comment]
👍

**Comment by SuperSandro2000** [comment]
FYI Please use the reaction feature to keep GitHub free of spam.
