### ISSUE TITLE
Error when selecting Computing by Factory

### ISSUE THREAD

**Issue by okradonkey** [Helfima/helmod#172]
This latest version with the updated UI looks great!  I added a gears recipe to my production line, went to the gears production block, clicked the gears line item, checked "Computing by factory" in the right section of the UI, and changed the number of factories to 2.  Clicking on the Update button generated the following error:

\_\_helmod\_\_/edition/ProductBlockEdition.lua:353:attempt to index field 'block' (a nil value)

Thanks!

**Comment by Helfima** [comment]
fixed in v0.8.6
