### ISSUE TITLE
UI doesn't remember current production block

### ISSUE THREAD

**Issue by MatthewSmit** [Helfima/helmod#173]
As of the latest update (0.8.4), when opening the UI, it does not remember what production block was active.

Current Behaviour:
Have a recipe (say, green chips) open in the production block tab.
Close Helmod UI.
Open Helmod UI.
The production line tab is open.

Expected Behaviour:
Have a recipe (say, green chips) open in the production block tab.
Close Helmod UI.
Open Helmod UI.
Have the recipe open on the production block tab.

**Comment by Helfima** [comment]
fixed in v0.8.6
