### ISSUE TITLE
Too many production lines run off the right side of the box

### ISSUE THREAD

**Issue by Razaekel** [Helfima/helmod#175]
The row of production lines doesn't start a second row if there's too many in the first row, causing the button for adding a production line to run off the right side of the box, becoming unselectable.

![image](https://user-images.githubusercontent.com/4242014/55276835-bed6ce80-52ce-11e9-86e0-99f850fd0a8a.png)

**Comment by Helfima** [comment]
can you try v0.8.7

**Comment by Razaekel** [comment]
Confirming fixed in 44f050a
