### ISSUE TITLE
problem when using Helmod with Yuoki Industries

### ISSUE THREAD

**Issue by petrukhnov** [Helfima/helmod#177]
There is problem when using Helmod with Yuoki Industries. When recipe is selected, it is not possible to select amount or producing machine.

Errors: 
 351.660 Script @__helmod__/controller/Controller.lua:317: __helmod__/tab/ProductionLineTab.lua:228: bad argument #1 to 'band' (number expected, got nil)
 357.226 Script @__helmod__/controller/Controller.lua:317: __helmod__/tab/ProductionLineTab.lua:228: bad argument #1 to 'band' (number expected, got nil)
1299.227 Script @__helmod__/controller/Controller.lua:317: __helmod__/tab/ProductionLineTab.lua:228: bad argument #1 to 'band' (number expected, got nil)
1938.993 Script @__helmod__/controller/Controller.lua:317: __helmod__/tab/ProductionLineTab.lua:228: bad argument #1 to 'band' (number expected, got nil)
1940.575 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/ProductBlockEdition.lua:279: bad argument #1 to 'band' (number expected, got nil)
1944.395 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/AbstractEdition.lua:534: attempt to index field 'effects' (a nil value)
1946.462 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/ProductBlockEdition.lua:279: bad argument #1 to 'band' (number expected, got nil)
1947.147 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/AbstractEdition.lua:534: attempt to index field 'effects' (a nil value)
1948.215 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/AbstractEdition.lua:534: attempt to index field 'effects' (a nil value)
1949.475 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/AbstractEdition.lua:534: attempt to index field 'effects' (a nil value)
1950.259 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/AbstractEdition.lua:534: attempt to index field 'effects' (a nil value)
1956.911 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/AbstractEdition.lua:534: attempt to index field 'effects' (a nil value)
2036.053 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/ProductBlockEdition.lua:279: bad argument #1 to 'band' (number expected, got nil)
2062.794 Script @__helmod__/controller/Controller.lua:317: __helmod__/tab/ProductionLineTab.lua:228: bad argument #1 to 'band' (number expected, got nil)
2063.717 Script @__helmod__/controller/Controller.lua:317: __helmod__/model/RecipePrototype.lua:205: attempt to index upvalue 'lua_prototype' (a nil value)
2071.629 Script @__helmod__/controller/Controller.lua:317: __helmod__/model/RecipePrototype.lua:205: attempt to index upvalue 'lua_prototype' (a nil value)
2209.775 Script @__helmod__/controller/Controller.lua:317: __helmod__/model/RecipePrototype.lua:205: attempt to index upvalue 'lua_prototype' (a nil value)
2213.179 Script @__helmod__/controller/Controller.lua:317: __helmod__/model/RecipePrototype.lua:205: attempt to index upvalue 'lua_prototype' (a nil value)
2221.709 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/ProductBlockEdition.lua:279: bad argument #1 to 'band' (number expected, got nil)
2223.043 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/ProductBlockEdition.lua:279: bad argument #1 to 'band' (number expected, got nil)
2225.757 Script @__helmod__/controller/Controller.lua:317: __helmod__/tab/ProductionLineTab.lua:228: bad argument #1 to 'band' (number expected, got nil)
2227.053 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/ProductBlockEdition.lua:279: bad argument #1 to 'band' (number expected, got nil)
2228.778 Script @__helmod__/controller/Controller.lua:317: __helmod__/model/RecipePrototype.lua:205: attempt to index upvalue 'lua_prototype' (a nil value)
2230.808 Script @__helmod__/controller/Controller.lua:317: __helmod__/tab/ProductionLineTab.lua:228: bad argument #1 to 'band' (number expected, got nil)
2232.034 Script @__helmod__/controller/Controller.lua:317: __helmod__/edition/ProductBlockEdition.lua:279: bad argument #1 to 'band' (number expected, got nil)
2235.541 Script @__helmod__/controller/Controller.lua:317: __helmod__/tab/ProductionLineTab.lua:228: bad argument #1 to 'band' (number expected, got nil)
2277.809 Script @__helmod__/controller/Controller.lua:317: __helmod__/tab/ProductionLineTab.lua:228: bad argument #1 to 'band' (number expected, got nil)
2278.749 Script @__helmod__/controller/Controller.lua:317: __helmod__/model/RecipePrototype.lua:205: attempt to index upvalue 'lua_prototype' (a nil value)
2280.716 Script @__helmod__/controller/Controller.lua:317: __helmod__/model/RecipePrototype.lua:205: attempt to index upvalue 'lua_prototype' (a nil value)
2313.077 Script @__helmod__/controller/Controller.lua:317: __helmod__/model/RecipePrototype.lua:205: attempt to index upvalue 'lua_prototype' (a nil value)

**Comment by Helfima** [comment]
Hello, I have try and I dont see nothing
perhaps need more explain
