### ISSUE TITLE
Gui not showing numbers in 0.17.29. helmod v0.8.8

### ISSUE THREAD

**Issue by skofisk** [Helfima/helmod#181]
The gui does not show any numbers when using factorio 0.17.29. Loaded same mods/save in 0.17.28 and the issue is gone.
![image](https://user-images.githubusercontent.com/26026953/56053506-903c0780-5d54-11e9-9c92-ceec41bebbc9.png)

**Comment by FKuerten** [comment]
Also present in 0.17.30.

**Comment by i2um1** [comment]
The issue in style.lua file:
```lua
default_gui["helmod_label_element"] = {
  type = "label_style",
  parent = "label",
  font = "helmod_font_normal",
  top_padding = -5,
  right_padding = 2,
  bottom_padding = -5, -- you have to change -5 to 0
  left_padding = 2
}
```

The bottom_padding value must be 0 for ```helmod_label_element_sm``` style too.

**Comment by Helfima** [comment]
fixed
Version: 0.8.9
Date: 13. 04. 2019
  Bugfixes:
    - Fixed number cut off
    - Fixed pin panel display
