### ISSUE TITLE
Recipe filter only works in cornercases

### ISSUE THREAD

**Issue by manuelthieme** [Helfima/helmod#183]
Using Factorio 0.17.31 with Helmod 0.8.9 but the following started earlier:

* Using recipe filter by typing in searchword and clicking apply clears filter form and does not filter
* Using recipe filter with setting "filter on text changed" shows same behaviour
    * after typing each char, the form field resets
    * being fast enough to write more than one char I can see them stay in the form a few milliseconds before it is cleared
    * filter seems to get applied or at least processed in a strange way since the tab changes when typing different chars. No chance to input full search query though
* Clicking an ingredient opens recipe selector without filter (or with last filter that really got applied)
* Clicking an ingredient twice actually does what you would expect (as far as I can say this is the only way to have a filter applied)
* Clicking a tab when a filter is applied clears filter
* The only way to change tabs after a filter is applied is by clicking the tab, then clicking the ingredient again (since it shows the filter results from the last opened tab)

**Comment by Helfima** [comment]
fixed in v0.8.10
