### ISSUE TITLE
Multiple Outputs

### ISSUE THREAD

**Issue by Ranakastrasz** [Helfima/helmod#185]
Not sure if this is possible and I just can't figure it out, but....

For a singular production block, I would like to be able to set multiple output types, even if one output is a component for another recipe in that block. So I would be able to add copper cable and Circuits, and have it output 15 circuits and 15 copper cable from that block, instead of having to either use two blocks, or manually set the percentage increase thing for the copper cables.

**Comment by Glease** [comment]
Just unlink the block and set your requirement manually.

**Comment by Helfima** [comment]
implemented in v0.9.12
