### ISSUE TITLE
Console error when attempting to open the GUI

### ISSUE THREAD

**Issue by Mustard5** [Helfima/helmod#188]
I updated just a short while ago before installing Helmod in a new game of Bob's.  When I click on the icon to open the GUI this error message appears in console.  The GUI fails to open.

`3037.501 Script @__helmod__/controller/Controller.lua:307: __helmod__/model/Model.lua:543: bad argument #-1 to 'table_size' (table expected, got nil)`

Factorio version 0.17.37 (just updated to this today)

**Comment by Helfima** [comment]
oups it's fixed in v0.8.11
it's not the factorio problem but a bug in my mod :)

**Comment by abesto** [comment]
Confirming the UI opens correctly after upgrading through the _in-game mod manager_ (what a time to be alive), thank you!
