### ISSUE TITLE
Number of factories gets rounded down instead of up

### ISSUE THREAD

**Issue by Razunter** [Helfima/helmod#189]
I think this issue appeared since 0.8.10

Had to enable decimals on factories to get some approximation...

![Screenshot](https://user-images.githubusercontent.com/362900/57549233-09d70d80-7374-11e9-801d-11ed03baaa5b.png)

P.S. There should be a better way to select default factories than abstract "Factory default level". Something like right-clicking on factory in the selection window and a special symbol for currently selected ones.

**Comment by Helfima** [comment]
fixed version 0.8.12
