### ISSUE TITLE
Electric Mining Drills can't use Productivity Modules and have only 2 slots

### ISSUE THREAD

**Issue by GuiltyBystander** [Helfima/helmod#19]
Electric Mining Drills should be allowed to use productivity modules, but helmod doesn't think they can.

They also should have 3 slots, not 2.

**Comment by Helfima** [comment]
yes it's right!
I do not have access to the value in the game, I have to retrieve them.
I reflected on a good solution.

**Comment by Helfima** [comment]
resolve in 0.2.21
you must apply the extractor for the good value now
