### ISSUE TITLE
QOL: Please don't scroll to top on every click

### ISSUE THREAD

**Issue by ianjirka** [Helfima/helmod#191]
Every time I click to add or move a recipe the recipe list scrolls to the top of the production block.  This is really annoying when working with complicated production chains, because I have to keep scrolling down to the bottom.

My main use case is moving rows down, also when adding ingredients in a recursive fashion.

Thanks much!

**Comment by jocker-il** [comment]
I totally agree this is annoying and I just started using it today !

**Comment by Helfima** [comment]
added in v0.8.13
