### ISSUE TITLE
Standalone Client

### ISSUE THREAD

**Issue by jodli** [Helfima/helmod#192]
Hi!
Have you considered developing a standalone client with a similar functionality? 

It would be awesome to use this even when you wanted to do a modless run of the game.

I guess you can still access the game files to read recipes and stuff so I think it would be possible! 

Thanks a lot for the consideration! 

___

Jodli

**Comment by Razunter** [comment]
https://kirkmcdonald.github.io/calc.html

**Comment by Helfima** [comment]
I read the recipes in the game via API, I don't read file
I do not want to make an external application anyway I do not have time
