### ISSUE TITLE
Helmod does not handle catalysts well

### ISSUE THREAD

**Issue by alercah** [Helfima/helmod#194]
Helmod does not handle partial catalysts very well (where the same recipe has input and output of the same ingredient, but less output than input). It seems to generally fail to account for the input required, leading to weird behaviours.

I've found two examples of this. The first is the Kovarex enrichment process, where if you add it in a production block, specifying to produce 100 U-235 per second, it computes an input of 100 U-238 per second and an output of -300 U-238 per second for the block. The -300 U-238 output should be an input, and I genuinely have no idea where the 100 on the input is coming from (since the actual numbers are 500 and 200, 100 shouldn't come out as a difference).

The second is in Angel's bioprocessing; cutting trees into wood takes in 1 saw and gives it back with probability 0.9. The result is effectively consuming 0.1 saws per craft. However, if you make a block with this recipe, the saws are completely ignored and appear as neither inputs nor outputs.

**Comment by Firemonkey08** [comment]
You can handle it with the produce rate in %. Change the value as long as it fits.

**Comment by Helfima** [comment]
it s ok now
![image](https://user-images.githubusercontent.com/20326713/63632692-92d03700-c63b-11e9-84af-38a97738213f.png)
