### ISSUE TITLE
Integrate with global window close shortcut

### ISSUE THREAD

**Issue by alercah** [Helfima/helmod#195]
Currently, Helmod ignores the global "close window" shortcut (default-bound to E), and has its own (currently bound to Escape for me; I forget if that's default or not). This is frustrating because it means that, where other windows including mod windows get closed by E, helmod instead lets both its window and the inventory window be open at the same time. Additionally, the Escape shortcut to close helmod is not prevented from further processing, resulting in the pause menu coming up when I try to close the window with Escape, instead of the normal behaviour which is just to close the window and not pause the game.

**Comment by Helfima** [comment]
you can change the key settings, use the game menu to see

**Comment by alercah** [comment]
Yes, and that's the problem. Helmod has its own "close window"shortcut that
is different from the global one used by Factorio. As a result, Factorio
doesn't realize that Helmod used the shortcut to choose a window, and opens
the pause menu. There shouldn't be a separate one for Helmod.

**Comment by Helfima** [comment]
I not sure if you have understand but you can change settings, me I bind the Clear cursor key
![image](https://user-images.githubusercontent.com/20326713/60550748-5235fa80-9d29-11e9-9d25-6093e5785d8c.png)

in the API, normaly you can use a property for close a window before another menu but with my mod there are more problem that without

**Comment by alercah** [comment]
I understand, yes. If you have that set to escape, and you press escape, the window closes and the game pauses. I don't want the game to pause.
