### ISSUE TITLE
Pinned recipe in one production line shows another recipe when changing to another line

### ISSUE THREAD

**Issue by jocker-il** [Helfima/helmod#197]
If you pin a production block in one production line and then switch lines in the main interface - the recipe changes in the pin dialog window

 looks like a bug to me...

**Comment by Firemonkey08** [comment]
sometimes  the recipe changes too, if in multiplayer someone else switch the line xD

**Comment by Helfima** [comment]
Version: 0.9.14
Date: 22. 11. 2019
  Bugfixes:
    - Fixed event on pin panel
    - Fixed error with logger
