### ISSUE TITLE
Error message in chat: __helmod--/dialog/PinPanel.lua:279:attempt to index global 'factory' (a nil value)

### ISSUE THREAD

**Issue by jocker-il** [Helfima/helmod#198]
When you have a production line with a block with more than one recipe inside it that has a "max per block" set and you pin it, you get this error after the pin panel appears.

![pinpanel error](https://user-images.githubusercontent.com/13031901/59969304-83087980-954a-11e9-9ca8-9caec147cdca.jpg)

 This only happens whenever the panel needs to show the Beacon configuration on the line - if you decrease twice and expand back once - it doesn't show the error and the sub-recipes show

![pinpanel green circuit block 1line](https://user-images.githubusercontent.com/13031901/59969306-9adffd80-954a-11e9-8d09-746e795b52b4.jpg)
![pinpanel green circuit block 2line](https://user-images.githubusercontent.com/13031901/59969308-9ddaee00-954a-11e9-9d69-aba1264cc77d.jpg)

**Comment by Helfima** [comment]
fixed version 0.8.12
