### ISSUE TITLE
Compatability with Creative Mode

### ISSUE THREAD

**Issue by The-Master27** [Helfima/helmod#200]
Using the 250% productivity module, which can go into factories and beacons, I cannot place into factories because it gives me "item-limitation", when trying to place into beacons it says "this item is restriced from being put into this container" when it is not, please fix, thx in advance

**Comment by The-Master27** [comment]
Will this be fixed anytime soon?

**Comment by Helfima** [comment]
if you see that before v0.8.19, use this
[helmod_0.8.18.zip](https://github.com/Helfima/helmod/files/3517265/helmod_0.8.18.zip)

**Comment by The-Master27** [comment]
Thx
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 19/08/2019, 8:00 pm Helfima <notifications@github.com> wrote:
if you see that before v0.8.19, use this
helmod_0.8.18.zip

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Helfima/helmod/issues/200?email_source=notifications\u0026email_token=AJPW6BV7E4CZJGMM46RVIKDQFLUTLA5CNFSM4H55ZQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4T655Q#issuecomment-522710774",
"url": "https://github.com/Helfima/helmod/issues/200?email_source=notifications\u0026email_token=AJPW6BV7E4CZJGMM46RVIKDQFLUTLA5CNFSM4H55ZQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4T655Q#issuecomment-522710774",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by The-Master27** [comment]
Only thing is I updated my helmod to 0.8.18 and the issue still persists
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 19/08/2019, 8:00 pm Helfima <notifications@github.com> wrote:
if you see that before v0.8.19, use this
helmod_0.8.18.zip

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Helfima/helmod/issues/200?email_source=notifications\u0026email_token=AJPW6BV7E4CZJGMM46RVIKDQFLUTLA5CNFSM4H55ZQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4T655Q#issuecomment-522710774",
"url": "https://github.com/Helfima/helmod/issues/200?email_source=notifications\u0026email_token=AJPW6BV7E4CZJGMM46RVIKDQFLUTLA5CNFSM4H55ZQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4T655Q#issuecomment-522710774",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Helfima** [comment]
don't update the mod via factorio use the attached zip or wait v0.8.19 at few day

**Comment by The-Master27** [comment]
Okay thx
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 19/08/2019, 10:36 pm Helfima <notifications@github.com> wrote:
don't update the mod via factorio use the attached zip or wait v0.8.19 at few day

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Helfima/helmod/issues/200?email_source=notifications\u0026email_token=AJPW6BUXBQSLXP6ZGHLBIVDQFMG5BA5CNFSM4H55ZQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4UL3EI#issuecomment-522763665",
"url": "https://github.com/Helfima/helmod/issues/200?email_source=notifications\u0026email_token=AJPW6BUXBQSLXP6ZGHLBIVDQFMG5BA5CNFSM4H55ZQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4UL3EI#issuecomment-522763665",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by The-Master27** [comment]
Used the zip file, although the productivity module works with the creative mod beacon, but unable to place in beacon
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 19/08/2019, 10:36 pm Helfima <notifications@github.com> wrote:
don't update the mod via factorio use the attached zip or wait v0.8.19 at few day

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Helfima/helmod/issues/200?email_source=notifications\u0026email_token=AJPW6BUXBQSLXP6ZGHLBIVDQFMG5BA5CNFSM4H55ZQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4UL3EI#issuecomment-522763665",
"url": "https://github.com/Helfima/helmod/issues/200?email_source=notifications\u0026email_token=AJPW6BUXBQSLXP6ZGHLBIVDQFMG5BA5CNFSM4H55ZQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4UL3EI#issuecomment-522763665",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Helfima** [comment]
I mean is ok in v0.9.0

**Comment by The-Master27** [comment]
I cannot thank you enough for your support. ISSUE CLOSED!
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 23/08/2019, 10:27 pm Helfima <notifications@github.com> wrote:
I mean is ok in v0.9.0

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Helfima/helmod/issues/200?email_source=notifications\u0026email_token=AJPW6BQTTLIC5MXXXDSGJJ3QGBI57A5CNFSM4H55ZQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5BL6IA#issuecomment-524468000",
"url": "https://github.com/Helfima/helmod/issues/200?email_source=notifications\u0026email_token=AJPW6BQTTLIC5MXXXDSGJJ3QGBI57A5CNFSM4H55ZQ62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5BL6IA#issuecomment-524468000",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
