### ISSUE TITLE
bug report- mod incompatibility

### ISSUE THREAD

**Issue by Lincolnmc** [Helfima/helmod#204]
crashes on loading with How It Should Have Started https://mods.factorio.com/mod/how-it-should-have-started
The mod How It Should Have Started caused a non-recoverable error.
Please report this error to the mod author.

Error while running event how-it-should-have-started::on_player_created (ID 24)
The mod Helmod: assistant for planning your base. caused a non-recoverable error.
Please report this error to the mod author.

Error while running event helmod::on_research_finished (ID 18)
helmod/controller/Controller.lua:129: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
[C]: in function 'pairs'
helmod/controller/Controller.lua:129: in function 'resetCaches'
helmod/controller/EventController.lua:113: in function <helmod/controller/EventController.lua:111>
stack traceback:
how-it-should-have-started/control.lua:29: in function <how-it-should-have-started/control.lua:14>
stack traceback:
[C]: in function 'newindex'
__how-it-should-have-started/control.lua:29: in function <how-it-should-have-started/control.lua:14>

**Comment by Helfima** [comment]
fixed in v0.8.14
