### ISSUE TITLE
Message in factorio log - " attempt to index local 'lua_player' (a nil value)"

### ISSUE THREAD

**Issue by jocker-il** [Helfima/helmod#205]
After all the mods Control.lua files are Checksum'd, this error appears in the log:

Script @__helmod__/controller/Controller.lua:307: __helmod__/controller/Controller.lua:681: attempt to index local 'lua_player' (a nil value)

 It doesn't cause any issues with the gameplay, as far as I can tell,

**Comment by Helfima** [comment]
What is you version of mod?

**Comment by jocker-il** [comment]
Was in 0.8.12, now on 0.8.15 and the line number changed:

Script @__helmod__/controller/Controller.lua:324: __helmod__/controller/Controller.lua:653: attempt to index local 'lua_player' (a nil value)

**Comment by Helfima** [comment]
ok it's not a problem but now it's fixed
