### ISSUE TITLE
Matrix solver not working properly

### ISSUE THREAD

**Issue by btg01** [Helfima/helmod#206]
![helmod](https://user-images.githubusercontent.com/50054015/62967359-66602380-bdce-11e9-95d2-73103938a864.png)
![helmod mods list](https://user-images.githubusercontent.com/50054015/62967536-c35bd980-bdce-11e9-8ddb-31ac39d35a2a.png)

When i click on the matrix button it gives me some weird out put for petroleum and light oil.

**Comment by Helfima** [comment]
the solver search optimal solution
the lubricant recipe need 500 heavy oil this is the minimal for petrol recipe after there no need craking for the 2 another fluids is enought
