### ISSUE TITLE
Oil calculations / cracking

### ISSUE THREAD

**Issue by vanatteveldt** [Helfima/helmod#21]
First, thanks for this mod, it really helped plan my base! 
(https://forums.factorio.com/viewtopic.php?f=204&t=38856)

Now, maybe I don't understand how it works, but I can't get helmod to properly calculate the refinery part. 
My base needs 4.5k light oil for rocket fuel, and around 11k PG for sulfur and plastic.

If I add a separate block with 'adv oil processing' as main recipe, it just refines up to 11k PG and 'throws away' the remaining light and heavy oil, and adding cracking recipes gives zero or negative numbers:

![image](https://cloud.githubusercontent.com/assets/1736240/21455263/28d9cf94-c91f-11e6-8c2d-c1d2fee1f2c3.png)

If I add refining and cracking to another production block (e.g. to the plastic block), it assumes that either the refinery should produce all PG (and heavy+light are rest products), or the cracking should produce all PG (and the original PG from the refining becomes a rest product):

![image](https://cloud.githubusercontent.com/assets/1736240/21455292/65c19af4-c91f-11e6-8769-d7e23e99ab38.png)

I understand the difficulty since normally you have a single end product and everything just transforms intermediates until the end product is reached; but here you have 2 end products (fuel+gas) and how much light->pg cracking is needed and the ratio (pg->fuel : light->fuel) depends on the desired ratio between the end products, so the calculation is not as straightforward... but it would be nice to have :)

Give me a shout if you need more information and/or the save file!

**Comment by Helfima** [comment]
Hello,
Currently my algorithm does not like the first recipes to multiple product.
See this example https://forums.factorio.com/viewtopic.php?f=92&t=30465&start=20
I know, i must change the algorithm but it's not easy :)

**Comment by Helfima** [comment]
resolve in 0.4.4
