### ISSUE TITLE
matrix solver: set what to solve?

### ISSUE THREAD

**Issue by vanatteveldt** [Helfima/helmod#214]
First, thanks for the mod! It was always great, but now that I dove into Angel+Bob+Seablock it has become indispensable!

I also love the new (?) matrix solver since in A+B often the chains are not as linear as in vanilla. For example, algae produce (indirectly) charcoal which can be turned into CO2, but also require CO2, so you always need to set charcoal to >100%. Matrix solver does this perfectly.

Sometimes, however, recipes have multiple outputs, and I'm not sure how helmod decides which to take for the production%. For example, many recipes have purified/mineralized water as a rest product, but Helmod sometimes then tries to use that recipe to produce all needed purified water, overproducing the thing I really wanted to produce.

The same I come across in the matrix solver. For example, here is a production chain for nitric acid:
![image](https://user-images.githubusercontent.com/1736240/67491282-f5ae7080-f674-11e9-8b88-ac2a4ed243f4.png)

Bottom to top: 
- pure water is electrolysed to H2 (white) and O2 (red) 
- Air is separated into N2 (blue) and O2, 
- Ammonia (NH3) is synthesized from N2 and H2  [using a catalyst]
- NO is synthesized from ammonia and O2  (the water mysteriously disappearing)
- NO2 is produced from NO and O2
- Nitric Acid (HNO3) is produced from NO2 and H20.

Now, since step 1 and 2 both produce oxygen and the ratios don't add up, this is going to have rest products and I will flare off, either O2 (if splitting too much air) or H2 (if electrolysing too much water). Electrolysis is expensive and air separation is cheap, so I want to use the electrolysis as little as possible (ie only to produce the H2 that is  needed) and produce all extra O2 from the air splitting. So, my prefered solution is to set air separation to produce 89% (slightly underproducing O2) and let the electrolysis run 100% to produce the H2 and extra O2. This overproduces N2 which I can then flare off. 

However, as shown above the matrix solver does the opposite, using the separation as little as possible and overproducing on the electrolysis, which is much more expensive in terms of power and buildings used. It does not matter which I put higher in the chain.

Question (or feature request): (how) can I tell the matrix solver which rest products are OK, and which I would like to avoid? 

And similar Question: (How) can I tell Helmod that I would like it to set 100% production relative to a specific output if there are multiple outputs?

Thanks!

**Comment by Helfima** [comment]
Hello, it's a good question
the matrix solver use the simplex method (https://en.wikipedia.org/wiki/Simplex_algorithm)
I am not a specialist to solve the linear problem at this point there no way to choose something when you use matrix solver, the solution is the best and the algorithm is the master :)
Before I have try another way with determinant but we need a square matrix, it is not well.
If you known a better algorithm I take

I understand your question, sometimes we want to give an orientation to the solution
I had an idea, if we could choose the lines using the matrix solver, as in the following picture (it's a sample)
![image](https://user-images.githubusercontent.com/20326713/67533930-18b83f00-f6cc-11e9-98c4-6461de2769b0.png)
I not sure if a good way and the mod already requires a lot of time, build a computing with normal and matrix solver mix requires a lot of time.

actually, you can disable solver matrix after the first computing and set your % production where you want.
the matrix solver is just to find the right % production after the normal solver must do the same result

When I check your question, I have found a problem we can't use voider, It will ok in next release

**Comment by vanatteveldt** [comment]
Sorry for the late reply, thanks for the explanations. Looking forward to the release, I guess voiders will allow the matrix solver to understand what the important outputs are. 

As always, thanks for the great mod!!
