### ISSUE TITLE
Module preferences missing remove button

### ISSUE THREAD

**Issue by CzBuCHi** [Helfima/helmod#217]
Maybe im just missing something, but i think "Module preferences" dialog is missing remove button:
![helmod](https://user-images.githubusercontent.com/12444673/69918595-5a2ecd80-1474-11ea-807d-6c9502699c2a.png)

(also too many presets will mess up layout - i creates 7 of them and not i cannot see 7th button ...

**Comment by Helfima** [comment]
Hello
yes I must add a remove button :)
normaly in the version 0.9.17 you can see the 7th
in fact I must also allow to choose between putting the modules one by one or with a priority

**Comment by CzBuCHi** [comment]
do you know where these settings is stored so it can be removed manually?

**Comment by Helfima** [comment]
you can use that in the consol

> /c helmod ResetUserUI

**Comment by CzBuCHi** [comment]
just tested console command - correctly it is 
    /helmod ResetUserUI

**Comment by Helfima** [comment]
v0.9.18 Added remove button on preference priority
