### ISSUE TITLE
Wrong automatic input when mixing input blocks and output blocks using the same ingredient

### ISSUE THREAD

**Issue by deciton666** [Helfima/helmod#220]
HelMod version: 0.9.18

I am currently playing seablock and will use an example from that modpack.

* Block #1 (Production input, required output is 1 Elendilomone)
  - 1 Elendilomone FROM 0.23 Mud, 0.12 Elendilomone Seed, 1.12 Viscous Mud Water

* Block #2 (Production input, Linked)
  - 0.12 Elendilomone Seed FROM 0.21 Elendilomone 

* Block #3 (Ingredient input, Linked)
  - 1.21 Elendilomone TO 0.97 Nuts

Wanted usage of Elendilomone in #3: 1 (From #1) - 0.21 (From #2) = 0.79
Current usage of Elendilomone in #3: 1 (From #1) + 0.21 (From #2) = 1.21

There seems to be a +- error when calculating the amount of Elendilomone used by Block #3.

**Comment by Helfima** [comment]
hello thx for this report
resolve in v0.9.20

![image](https://user-images.githubusercontent.com/20326713/71678659-facf2080-2d85-11ea-991e-73f179060dec.png)

**Comment by deciton666** [comment]
Great work.

The tool is only getting better and better :)
