### ISSUE TITLE
With many mods preferences window is too tall

### ISSUE THREAD

**Issue by taralx** [Helfima/helmod#222]
I'm running bobmodules and the preferences are very very tall because of all the modules. It doesn't have a scroll bar.

**Comment by Helfima** [comment]
thx for this report
fixed in Version: 0.9.21
![image](https://user-images.githubusercontent.com/20326713/71783330-9ad6b500-2fe5-11ea-98e2-54f334e27e76.png)

**Comment by taralx** [comment]
Thank you! I tried to fix it myself by wrapping the whole Form content panel in a scroll area but it resulted in a weird gap at the edge. 🙂

**Comment by Helfima** [comment]
:)
