### ISSUE TITLE
Nominal speed of drills is incorrect?

### ISSUE THREAD

**Issue by daves20** [Helfima/helmod#23]
when I view the summary of the production line you can see how many extractors you need. it defaults to electric mining drills, it says to the right that the nominal speed of the electric mining drill is 0.5, which is correct, but when you change the factory type to burner mining drill or when you click to change to electric mining drill, the value changes to an incorrect value. the nominal speed value of electric mining drills suddenly becomes 1.5 and the value of burner mining drills becomes 0.88.

This is annoying because sometimes I like to mess around with burner inserters for extraction, but I can't change the values or else the nominal speed gets messed up and the calculations get messed up.

**Comment by Helfima** [comment]
the initial value is not exact
for mining drill i use this formula to use same function that factory
`speed_nominal = mining_power * mining_speed`
i didn't tested the formula is right or need another factor

**Comment by Helfima** [comment]
i need fixe the first value of machine

**Comment by Helfima** [comment]
resolve in 0.4.1
