### ISSUE TITLE
Unable to create hew production lines.

### ISSUE THREAD

**Issue by Althrretha** [Helfima/helmod#231]
I am unable to add recipes to existing or new production lines. The recipe selection window appears to be minimized. I see the error 

_ _ helmod _ _ /model/Player.lua: 721: attempt to index local 'prototype' (a nil value)

This error does not happen if I start a new game.

I am running most of the Bob's mods suite (except for Bob's enemies, warfare, and vehicle equipment). Other mods are:
Advanced Solar
Aircraft
Big Storage Tank-Store your fluids
Dectorio
Disco Science
Even Distribution
Factorio Standard Library
Flare Stack
Helmod
Infinizoom
Long Reach
LTN - Logistic Train Network
Nanobots - Early Bots
Optera's Library
Picker Atheneum [core]
Picker Dollies
Power Armor MK3 
Power Armor MK4
Rail Signal Planner
Resource Spawner Overhaul
ShinyBobGfx
ShinyIcons
Squeak Through
Teleporters
Todo List
Vehicle Snap

There is a link to my save file:

https://drive.google.com/file/d/1YVPTGRV2ce7nbKSHzd5Ja3K50QWeplIg/view?usp=sharing

![Helmod Error](https://user-images.githubusercontent.com/60458252/73419756-ec711780-42e5-11ea-99a1-067c331a539a.png)

**Comment by Althrretha** [comment]
I am running version 0.9.28 of Helmod.

**Comment by Althrretha** [comment]
I tried to update to .18, but so many mods are not updated yet, so I reverted back to .17.79.  Now this problem is gone.

**Comment by Helfima** [comment]
hello
something was renamed
use this command /helmod resetcaches

I mean few mod was updated with helmod and the cache was not reset
it will fix that in the next release
