### ISSUE TITLE
Multiplayer Desync: "Wait for translate"

### ISSUE THREAD

**Issue by Capsup** [Helfima/helmod#233]
```This seems to have been reintroduced?
My headless server and client are both at 0.18.79.
helmod is at helmod 0.9.22
Not sure what logs I can provide to help provided the comment above.
When I click on any GUI elements it causes lag where I can no longer move and always results in me desyncing.
To fix this I loaded the save in single player, played a bit with the UI, saved, and transfered the save back to my server. Restarting the server without doing this did not help. This was in a docker container if that helps. I can provide the save if this helps.

_Originally posted by @ankenyr in https://github.com/Helfima/helmod/issues/166#issuecomment-575706493_
```

Referencing existing post because I have the same issue.

This only occurs when trying to open Helmod in a multiplayer world, but not singleplayer. Tried updating to 0.9.30 and running with Helmod only, happens as soon as you try to add a new recipe. I guess something times out when trying to get translated names?

Fixed the issue the same way as recommended above, loading save into singleplayer, closing the Helmod window, then uploading save to server again.

**Comment by Capsup** [comment]
[desync-report-2020-02-14_21-46-24.zip](https://github.com/Helfima/helmod/files/4207215/desync-report-2020-02-14_21-46-24.zip)

Attached is Desync report.

**Comment by Helfima** [comment]
hello, can you try last release
