### ISSUE TITLE
Bob's Mod Steam Assembling Machine

### ISSUE THREAD

**Issue by FrancoisH** [Helfima/helmod#237]
When using a steam Assembling Machine, it shows off the choice of the fluid used and offers every oil available (or other piped fuel). It should ask for the boiler type (which decide which speed the steam machine will run to, or the steam's temperature.

![Factorio Screenshot 2020 02 22 - 23 12 55 79](https://user-images.githubusercontent.com/3524681/75100320-5cfd1280-55cc-11ea-81db-dff1b1adb7f6.png)

**Comment by Helfima** [comment]
try v0.10.6

**Comment by vvv444** [comment]
@Helfima Happens to me on 0.12.5.
