### ISSUE TITLE
update log ?

### ISSUE THREAD

**Issue by SGZ-TW-TY-20** [Helfima/helmod#243]
no more changelog for 0.17 it do still have update ? as am going from mod V 0.9.29 - 0.9.33

**Comment by Helfima** [comment]
hello the factorio web site display only the greater version

---------------------------------------------------------------------------------------------------
Version: 0.9.33
Date: 28. 02. 2020
  Changes:
    - added a new block for energy consumption
    - added a debug panel when debug is activated
    - added energy source prototypes (not perfect only available in 0.18.7)
    - removed energy tab
    - modified property tab
    - changed fluid recipe, now there are hidden except water and steam
    - removed ingredient for ressource recipes and water recipe
  Bugfixes:
    - fixed width internal panel of edit recipe
    - fixed a bug in RecipePrototype
    - fixed cap negative productivity
    - fixed energy source in recipe
    - fixed crash new game

https://github.com/Helfima/helmod/blob/0.17/changelog.txt
