### ISSUE TITLE
Cant add ingredient recipe since 10.9

### ISSUE THREAD

**Issue by hasezoey** [Helfima/helmod#244]
Since updating to 10.9 i cant click on an ingredient-recipe anymore to add it (dialog with recipe search works, but clicking on it does nothing

here is the log file, but i couldnt find any error/warning logs for helmod
[factorio.log](https://github.com/Helfima/helmod/files/4280210/factorio.log)
Factorio: 18.9
System: Linux Mint 19.3
Singleplayer world

Update: i downgraded to 10.8 again and now i cant add an recipe there anymore too (with the save made with 10.9)

**Comment by hasezoey** [comment]
Another Update:
it seems like this only happens on recipes that were already existing before upgrading to 10.9 (from 10.8), new recipes are fine

...Another Update:
after i added an new production block in the new version, everything is fine now again with the old recipes

(i dont know if this is wanted to be kept open for further investigation, but it seems fixed now)

**Comment by Helfima** [comment]
hello
probably a little bug, sometimes you have to shake the interface
open/close or refresh model
