### ISSUE TITLE
Factorio 0.18.10 Server Crash

### ISSUE THREAD

**Issue by Speiger** [Helfima/helmod#245]
Since Factorio Update to Beta Version 10 Helmod is causing desyncs when doing any change to the planners.
You still can read the plans but editing them causes = desync

We are running factorio on a dedicated server right now.

This is the report that I got.
[log.txt](https://github.com/Helfima/helmod/files/4308834/log.txt)

I hope that log helps because it makes the mod unusable right now.

If you need anymore description I like to provide as much as possible to fix this issue.

**Comment by Helfima** [comment]
can I test the saved game file?

**Comment by Speiger** [comment]
https://www.dropbox.com/s/s2z4mylexhtzhhy/BugTestSave.zip?dl=0
I hope you can find the issue.

**Comment by Helfima** [comment]
I have try with 2 factorio on my PC and the are no error
but you can try to refresh cache in the panel admin of my mod
![image](https://user-images.githubusercontent.com/20326713/76687452-4d4d7880-6624-11ea-8425-33ca766fe0c4.png)

**Comment by Speiger** [comment]
Nope after reseting those two and then adding a module to the beacons the server desynced.
I am not the admin but I might can ask the server admin if you can join. Though you would be required to download a modified mod. (We changed trainspeeds in 1 of our mods)

**Comment by Helfima** [comment]
try v0.10.10 but not sure if this resolve your problem

**Comment by Speiger** [comment]
thanks. I will report back as soon the server was updated

**Comment by Speiger** [comment]
yeah we stopped playing that is the issue. I assume its fixed basically. Sorry for the long wait on this...
