### ISSUE TITLE
DispatcherController regression

### ISSUE THREAD

**Issue by polski-g** [Helfima/helmod#248]
Getting error below as of 4pm today. Was not getting this last night. Problem occurs when I open a production entry using Bob's Steam-powered drill as the source for the Iron ore.

```
1218.444 Script @__helmod__/controller/DispatcherController.lua:71: __helmod__/model/EnergySourcePrototype.lua:329: attempt to call method 'getFluidUsage' (a nil value)
```

**Comment by Helfima** [comment]
the error is in EnergySourcePrototype
i will fix in v0.10.11
