### ISSUE TITLE
Mod support & suggestion

### ISSUE THREAD

**Issue by Halmex** [Helfima/helmod#25]
Hi Helfima thanks for this amazing mod.
I found a problem with Angels, where cushed Ores can't be selected to make the final ores in the furnace.
Also I would like to ask if it's possible to implement the option select ratio besides poduction/time. For example 2 circuit assembler for 3 copper string assembler. And the option to fill for example a entire yellwo belt.

Thanks Halmex

**Comment by Helfima** [comment]
Hi Halmex
i'm not sure i have understand the problem.
![final_ore](https://cloud.githubusercontent.com/assets/20326713/23671921/47d6aa06-036d-11e7-961a-5e48b65983d6.PNG)
and for ratio you can use limit block
![ratio](https://cloud.githubusercontent.com/assets/20326713/23671951/5cf3ea84-036d-11e7-9383-8956cf4baa66.PNG)

**Comment by Halmex** [comment]
Yeah you understood everything. After starting the game today the recipes worked fine, probably I was just stupid yesterday or the game had a problem with loading the recipes. Anyhow its working fine now, and for the ratios, I feel stupid, I have played around with this option but I haven't understood the meaning. Thanks for your help and sorry for annoying you ;).

I am now a bit wiser :D 
Halmex
