### ISSUE TITLE
Overwrite output / input

### ISSUE THREAD

**Issue by hasezoey** [Helfima/helmod#250]
type: question / feature request

Is there currently a way to overwrite input's / output's? (like for py combustion tower the energy output (shown by helmod) is 756kw, but actually it is 24.6mw (on 60 fluid consumption per second))

(#241 might be related)

**Comment by Helfima** [comment]
you can give more explain
normaly the calculation is right but I can check that

**Comment by hasezoey** [comment]
i mean like manually overwrite what something produces / consumes in cases where helmod dosnt get the right values automatically, like for the "combustion tower" in py's mods, there it says it produces "756kw" with 60 fluid consumption, but actually it is "24.6mw" on 60 fluid consumption and it depends on the temperature of the fluid put in (it ranges from ~500°C to ~800°C (a guess))

**Comment by Helfima** [comment]
I need explain how work the process, I don't know PY and i can't check
![image](https://user-images.githubusercontent.com/20326713/77458363-5d244400-6dfe-11ea-9013-f31499effe5b.png)

**Comment by hasezoey** [comment]
@Helfima sorry, i meant in general not just this one "case" i just took it as an example because it is where i noticed it would be good to have an manual overwrite

if you want the process, here it is for the early to mid game of fluid production:
you have as an starting input coal putting this in an `Destructive Distillation` building for `Coal Gas`(yellow), then in an `Gasifier`(i dont know the exact name) an "transform" it into `Syngas` and then in an `Power House` to `Combustion Mixture`, and when im not wrong this specific recipe outputs the fluid at `550°C`, which should produce ~`24.6mw` (at least not `756kw` on full load)
-> but there are many other ways to get `Combustion Mixture` with differing temperatures

PS: i dont know what exact process you wanted explanation on
(i will comment an image on what my current power production is with some helmod proof when i start factorio again)

**Comment by hasezoey** [comment]
Overview of the Factory:
![Screenshot from 2020-03-24 19-36-29](https://user-images.githubusercontent.com/10911626/77464357-55b56880-6e07-11ea-9506-5ab013ad7862.png)
Energy with factory window open:
![Screenshot from 2020-03-24 19-38-45](https://user-images.githubusercontent.com/10911626/77464391-606ffd80-6e07-11ea-8402-398c19ab8ccb.png)
Combustion Mixture Production block:
![Screenshot from 2020-03-24 19-39-14](https://user-images.githubusercontent.com/10911626/77464396-6239c100-6e07-11ea-9bcc-4cb2afb22229.png)
the output of the C-M Production block should be able to supply 6 combustion towers (60/s consumption * 6)

<details>
  <summary>Download Code</summary>
  
```txt
H4sIAAAAAAAA/+VZ227bOBD9lcLPlEDqRgqFHvcH8roIDFmiHSG6GLo0cQP9+w4l0iJlOrGDtimw6kNEmTMczpw5HE7z5lvZZGn5bZu8FXmyqZqcl1ufbFDz
UvM22TylHf/Z8NMG7WDic5e8TX+33jxfDjaoTiuebLpTfUg7J2uq3dD1RVNb9GTNUPcJQcfmBX6I44CymKKiPrQ8L3jdwxJZ88yTt1mleN+g/nSE96LnlVKA
UdenPU+8Ec2rKoF5pET25VDkaxkyohf42yqRaWCVIIwSN9Yetiz7L9iWlo5Y7HGxVn55b3mQbV5PB14rqXn0kYzQra9j84pHXUrAo16EWRSHUUjP8iM6tk0+
ZMLBwnQVIqcqXvuh5UTfxeWPNuP8MDacEwcQx+MAP0Saq7uep9U5OmJgdzWJY6urQUXaPSkF8GrduMtCigP/vHeqGXArPkI3YqCCMAYq4B8JuUMCqcgfUZ+e
IQOvVhUeic0IxIsdnwYMFrJFC+FoXoucL9LaN1uKuMwngeaTKFiMuSfHYP2nU942GmTV2O4EpsXubqhjgGrLs+LIIWYPkmgegGOKOuevMO0q18xKZ9kFGH5s
PioPQARctPqReWifZn3TnpTFE085T83QnX0ELFX0ZyqjLjF1+IgD5x1OiYfFg7oj5zkwXllUhdgmkOxQis2NiO/3fMrIeQ4+2/YDFoBh1tTdUB1nW4Eyy3KY
30d94GJM5JrbvumBJrS56gtMoheG7gdeyviPaMdTWE/tex7ZYSH3F7BpfyIETRKcHUdcz7pXw8D1+DaDR/TgS0D4ChDEAIT3GRgQF5vPBQpAc7EvllPiVgj4
fw4CeA1l08MeiSZTbvAzDb8WDHea+hBKSIQKEj6ys+saE9Q8LD0DE2sI5AXQTJnCJzsImHvBtn8fCII48H1i9ezqsAiiLwbBfaY+UAkCqkDgrUDg7NumcvSz
zoQDdgOzhIgi86jANCLUj4mvJoX3QsRzPRZ6ixL2F/JExMJQ7Nzids+0nsZfi5D7LH1gEiBMASRA9lrGhAVxg9XR8S5L8BKi1Dbl6SdUDdUzJnYkhC4NrVFI
2JcVDYGoeq/Qbrg292tDf5+pIyq6f2Yb9mnZ8XPhMNRlUT+DD/t24DZlPgZl0QIlgsCzVSrCPZtf8Ok6pReJj+9UjrpfwIWqqrhWZaymL/RynXB0ETLdUi8R
+fghWHUt0ahiLW7/twYdhJZgjqvM6pryB+xaeH2cGwtbX28o+KqhAA6B6+euqPls3QfdBGz2EX7RNZeQKIrcaHmY9VItUa5cO42W5J9HUmFA5zJTXpeXsbo1
6TcggiVxEby+A63dY10sDtxAf6J3+euaSp28LCrl5mkY/Qny8l0chED/Ho0Jo4xQwh0c3nKjCGMPqsuQeTgKvBhEP8Fjv/PGc2mfRl4TSykEfMhdl7qs5GUG
/H0YGOQSh7+cGMRmb0rgdYV3ayL72EzkcyNQngghur8jqDpzUgXTys7bWnRTtnfN0GbCJ8qgHLanzinDDsPCq23KVVqnXcerHSDm4FRp9gRxda4ktwZzlaKX
0P6NWQPuhK0dxITNDs7DzJH7lg1oQDFIpweevOmrqfbi9JPTp/XzcjhMi2zlaBSkLU6LKUX7AsQIgtOoE8SywW7selQutoUg+JKJxTvBFro3mxA30f65J2rW
off0RmVPdFagUHtzb1S2Mmdpiu5taV62I2dNMfpkW1LvL0p/kivF+brRCNH8P5Zk6EtpW+W0+t8b41rhA68SOJPhR7ifYQJwOYj5wiUgnGbZUA2Gy7RPVvzi
qQEORWPaOse05uXiLv2jTTSYRUVmObw+gGM0Wf2rdV2NmUX+e+P3loN/62/b77zO/wOwbJ2cPRsAAA==
```
</details>

**Comment by hasezoey** [comment]
i need to correct myself, 24.6mw is for the highest temperature of the fluid, with 550°C fluid it is at max 13.5mw, but this shouldnt be anything major because helmod just shows 756kw (way lower than 500°C fluid)

**Comment by Helfima** [comment]
I have found a error in my code, better but It's not correct
![image](https://user-images.githubusercontent.com/20326713/77549272-ed6e9180-6eaf-11ea-83f2-5dc2974a67d2.png)

**Comment by Helfima** [comment]
there are a factor 5
  | Tmin °c | Tmax °c | delta power | Fluid Usage per tick | Fluid usage | J (200J/unit) | Effectivity | Power MW | Power max in Game | factor
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
gasturbinemk01 | 15 | 1000 | 985 | 1 | 60 | 11820000 | 0,42 | 4,9644 | 24,82 | 4,999597132
gasturbinemk02 | 15 | 1000 | 985 | 1 | 60 | 11820000 | 0,95 | 11,229 | 56,15 | 5,000445276
gasturbinemk03 | 15 | 1000 | 985 | 1,5 | 90 | 17730000 | 1,47 | 26,0631 | 130 | 4,987894763

**Comment by Helfima** [comment]
finally I have found the factor 5
![image](https://user-images.githubusercontent.com/20326713/80045215-05fdb600-8507-11ea-82a3-136039791457.png)
for water, the heat capacity is 200J and another fluid can be 1000J
