### ISSUE TITLE
Floating precision is broken?

### ISSUE THREAD

**Issue by Ryozuki** [Helfima/helmod#251]
![image](https://user-images.githubusercontent.com/15859336/77430366-5c2deb00-6ddb-11ea-8f83-3b134ee6746d.png)

The number is larger than what it shows there too: it's 52.2727272727273

If i'm not wrong it should have a precision of 1 according to my settings:
![image](https://user-images.githubusercontent.com/15859336/77430450-854e7b80-6ddb-11ea-81a0-f7174c0a143c.png)

I'm on 0.18, helmod version is 0.10.11

**Comment by Helfima** [comment]
it's not broken, it's a missing :)
I will fix soon

**Comment by Helfima** [comment]
fixed in v0.10.12
