### ISSUE TITLE
[0.18.18] Desync when open on a Multiplayer [Can't join the server anymore]

### ISSUE THREAD

**Issue by UnDeadClank** [Helfima/helmod#254]
Hey, i found a bug.
Me and my friend where playing Factorio.
When i did open the Mod, the mod wants to load all recipes. 
That created a desync for me and i got kicked from the server.
Now when i join the Server Hellmod is open and wants to load the recipes, that created a desync again and i got kicked again. This happens every time i join and i cant close Hellmod.

We have some mods installed (Bob's & Angel's), i don't know maybe thats many recipes, but for my friend it works perfectly.

When did it happen for me, i opened the Hellmod and clicked on the "Recipe selector" after that it desynced.

![Factorio _Moment](https://user-images.githubusercontent.com/2830011/78910658-92c75f00-7a85-11ea-9fa7-59d0f0e5f313.jpg)

**Comment by Helfima** [comment]
you can try the last version of helmod v0.10.13
normaly I removed the continue loop when you join game
I mean there a infinity loop

probably there are a problem with translated string
if you can join the game try this before open Recipe Selector
`/helmod ResetTranslate`
if you can't use the admin can try
`/helmod ResetUserAllUI`

if the bug persists
![image](https://user-images.githubusercontent.com/20326713/78955660-304f7c80-7ae0-11ea-8c51-5e70b33bf784.png)
the Admin can try that
1) Remove your caches
2) Refresh caches for Recipe Selector
