### ISSUE TITLE
Progress tracking during building ("Implemented" checkbox)

### ISSUE THREAD

**Issue by andreasferber** [Helfima/helmod#256]
It would be nice to have some sort of "Done" marker (for example a simple checkbox) that you can put on parts of a production line/block as you are building it.

With highly modded games like Bob's+Angel's you often have very complex production lines with multiple different side chains. As you are building them, you don't necessarily build them in the same order that they are in the recipe plan, and it is sometimes hard to keep track of which parts have already been built and which parts still need to be done. A simple marker to keep track would help with that.

The marker wouldn't have any influence at all on any of the calculations, it's simply meant as an aid during building.

**Comment by Helfima** [comment]
added
