### ISSUE TITLE
Linked block not updated

### ISSUE THREAD

**Issue by danyax** [Helfima/helmod#257]
To reproduce open linked production block. Switch from "product input" to "Ingredient input" - block numbers are not updated. If you turn off and then on "linked block" setting, all data are updated correctly.

**Comment by Helfima** [comment]
I tried to reproduce but failed
could you export your case? (use Upload Production Line button)

**Comment by danyax** [comment]
Open solid fuel block, click product input or ingredient input. Values not updating. Turn on and off "linked block" - values are updated

Vanilla, no mods except helmod


H4sIAAAAAAAA/81W227bPAx+lcLXcuBTTxh8+b9AL1cUhmozqVDZ8mSpnVH43UdZlk9xsqAdtt83kRh9pEh+pFiIKy5yyq+y9IMVqVeKAngWeUS8VyBT7/sb
yPZAPfKMx16b9KP/zUJ7eth4pKIlpN4L0LfWF4z7uaT5K6sOx3pyoSuVhqQW7yhP4iTAj+BRCQWDSqGJXFCefliVZu0R1da4ZgpKpyAKSKOogjTqyONk2Hty
wEk0oPdcs8LBHTrscAG0dKh+s4kIg8liR2opCp2by37CeBjPzD96nB1e1BI/ibbwyQJeg5KCgy79A20mFUvxlppoUtMRCTmrAf15iGxqH5ADrCrgJ8ZqSoXP
2Q8Ne5orJiqn1WJHtS44eALzbM4K2bprGXJI2DMkRevwmHWm2inQBPDfQzuQgzQ1QIGaOCuZyRxSVHNz1Y7Afg99FuyZYDT9hgpxm4uq0WXdXwX/FJxru+7m
m11wv/zuhhtkSiikoiPpCBnkwW6NizBktTY+dOQZKJp3ftvdFpMnd+96K7kon0WakBpk5oIX7K7n+8z4pSiC482ozC8fdJ92BmnBmv/s5faUNzASQlecVa8Y
cSU1XBQXTENJDQ2sCwz60lmw4ekcR+YRw+i68JqGdGmcETQFCRW0Y3h7LxZc7my/y+J5n4tdn2sEZ4W/18D9vRSlPyv38+1u1ei+1LiWTWi60qRpJtvk3dTO
pupPhupP1tV/xuetLhCc7QL5C5QMXx2/5sji7T4w1kUU3v6lNnCz+sJVKR0z/X9b5lt3PVHO4VTOVnyEPFG9qyw+nc/uuha/XMBL2mE5D1m3Xhhvj4cK63FC
fjdcjGOBBdyQC8aDvo4aoWVu89OXfL9SDMEhwZ7QGKZ52CB38fUwU2VYb/FQgWadnB4uXL4uHDKOhguLj8hlQ8bmcGFVxOTyIcOoWXYnq+P2qLGcSrqLqolO
+KdfEvKPebwcdhbdaeNFJgdznKLfiKV5rkvNzc5ZnYm2/XXpoNKvabV6LUbhFnTIpKkAH6oDxnSGnUs3wPdd132ToLSsrrJvUBW/AFbbL3t3DAAA

**Comment by danyax** [comment]
![image](https://user-images.githubusercontent.com/61344188/79063686-bbc93900-7cab-11ea-840c-7857b687bb66.png)
