### ISSUE TITLE
Improvement - bring recipe selector and edit recipe windows to top

### ISSUE THREAD

**Issue by danyax** [Helfima/helmod#258]
Probably the biggest pain for me switching from old UI to new one with independent windows.

Main window, recipe selector and edit recipe windows does not fit all on my monitor. In the old UI recipe selector and edit recipe were occupying same space and dynamically replaced each other - perfect!

Now I can manually put them in roughly the same space. But it does not work in reality for two reasons

1) the is no way to bring window to top, like clicking on its captions
2) when clicking on ingredients recipe window is not brought to top. Same for clicking on factory line and recipe window. 

So the only way to see covered windows is to close another one.

My suggestion is to bring corresponding window on top when one clicks on recipe or ingredient. Clicking on caption also should change z-order.

**Comment by Helfima** [comment]
hello, we can't change the z-order
I will try reproduce the old UI

**Comment by danyax** [comment]
Thank you very much!

**Comment by Helfima** [comment]
fix in v0.10.15

**Comment by danyax** [comment]
Autoclose options works fine. Thank you!

However, with both new options turned off it looks like behavior of windows is changes. Both recipe selected and edit recipe windows always appear glued to left side of the screen - they no longer retain previous position.

With above bus present, I can't deduce how glue option intended to work. Actually, for me it does not change anything - windows always stick to left side of the screen

**Comment by danyax** [comment]
![20200414183855_1](https://user-images.githubusercontent.com/61344188/79244242-56c63c80-7e7f-11ea-8e1e-0ed61c36dfd9.jpg)

**Comment by Helfima** [comment]
![image](https://user-images.githubusercontent.com/20326713/79285363-a75c8a80-7ebd-11ea-84a2-e97d321b8085.png)
the glue put the panel at 500 of the right side of the main panel
but if a panel have the left top corner is out off red rectangle, it is relocate at x=0 y=50

what is your screen size, I can test to do better
I will put another option for auto relocate

**Comment by Helfima** [comment]
oups I did a error :)
I take not the screen size to relocate but size screen x factor
increase the width factor to avoid relocation while waiting for the next release

**Comment by Helfima** [comment]
or even better with the modification, try this
[helmod_0.10.15.zip](https://github.com/Helfima/helmod/files/4478433/helmod_0.10.15.zip)

**Comment by danyax** [comment]
Tested dev version. Autoclose work like charm, all positions are properly retained.

Glue option works well at UI Scale 100%, but does not respect UI Scales != 100%. 

See 2 below screenshots, offset = 0, first UI scale 100%, second 125%.

**Comment by danyax** [comment]
![20200415102019_1](https://user-images.githubusercontent.com/61344188/79309407-e95bef80-7f02-11ea-8ada-a56ca27e2e6b.jpg)
![20200415102034_1](https://user-images.githubusercontent.com/61344188/79309411-ea8d1c80-7f02-11ea-8c21-0d2ad365773a.jpg)
![20200415102044_1](https://user-images.githubusercontent.com/61344188/79309413-ea8d1c80-7f02-11ea-82b6-70c971a4635d.jpg)

**Comment by danyax** [comment]
A suggestions - don't use pixels for defining offset, use relative screen width 0..1 like you do in mod settings for main window width.

**Comment by danyax** [comment]
Update - even with UI scale = 100% and offset = 0 sattelite windows not always properly positioned.

If you open satellite window, then move open window, then reopen satellite window, the latter will use old position of main window.
