### ISSUE TITLE
display size options

### ISSUE THREAD

**Issue by Mimahu** [Helfima/helmod#26]
I mostly play Factorio on a Leptop with a max resolution of 1366x768. With the currently supported display sizes the mod is unplayable because most of the buttons are unreachable. Could a display size option for 1366*768 be added?

Befor clicking "Add Production Block":

![20170310173658_1](https://cloud.githubusercontent.com/assets/15746689/23803976/9b8005ba-05b8-11e7-8067-fde7e5a01848.jpg)

After clicking "Add Production Block":

![20170310173712_1](https://cloud.githubusercontent.com/assets/15746689/23803975/9b73829a-05b8-11e7-91a7-714f9c661a6e.jpg)

**Comment by Helfima** [comment]
download last Version 0.2.25
to close main panel
``/c remote.call("helmod","close")``
to change display size
``/c remote.call("helmod","display_size","1360x768")``
If you want you can adjust the size "WIDTHxHEIGHT" by the command

selectable display size
1920x1200, 1920x1080, 1680x1050, 1680x900, 1440x900, 1360x768
