### ISSUE TITLE
Boiler fuel consumption is wrong

### ISSUE THREAD

**Issue by Grundik** [Helfima/helmod#260]
As shown on screenshot, helmod tells that 27 coal/second is required to make 60 steam/second:

![Screenshot_20200429_194723](https://user-images.githubusercontent.com/220951/80623210-887bfd80-8a52-11ea-9ba1-e09f2d8c3bc6.png)

It looks that error in steam production ratio in recipe: 0.45 coal required not for 1 steam, but for 60 (1 second of steam generation, not 1 unit of steam). So real number is not 27 coal/second, but 27/60 = 0.39 coal/second.

Factorio version: 0.18.21
Helmod version: 0.10.15

**Comment by Helfima** [comment]
fixed in v0.10.16

**Comment by Grundik** [comment]
Thank you very much!
