### ISSUE TITLE
Assembler quantity displays count rounded down

### ISSUE THREAD

**Issue by sdobz** [Helfima/helmod#264]
When designing a production block the number displayed in the factory column is rounded down.

"3.4" assemblers displays as 3,
"0.4" assemblers displays as 0
"2.7" displays as 2

The tooltip shows a more precise value

![img](https://i.imgur.com/KykStqB.png)

Should this round up instead? 3.1 assemblers would require 4 to fully match

**Comment by Helfima** [comment]
hello, yes I have change something in the rounded value and I have do a error
it will fix in the next release

**Comment by Helfima** [comment]
fixed in v0.10.17
