### ISSUE TITLE
Unit test failure; but results show success

### ISSUE THREAD

**Issue by prs9tb** [Helfima/helmod#269]
**Note:** I am using Krastorio 2 + Helmod together  (updated as of today)

Krastorio2's offshore pump is failing a unit test.  However the reasoning given for the failure is: "Failed, value 1 251 must be 1 251"

One of these is the likely source of the error:
  - Unit test is not doing a correct comparison (precision error?  or wrong comparison operator?)
  - Strange spacing in failure message might indicate the numbers are not being treated as numbers.  

![image](https://user-images.githubusercontent.com/5963862/81480170-da144d00-91f5-11ea-92ba-ce200f0ec501.png)

**Comment by Helfima** [comment]
Hello
yes I saw
it's not a problem, it's just laughable
the value must be a float value with decimal

**Comment by prs9tb** [comment]
Yes, it is a very minor issue.  Based on my debugging, your guess looks to be right: 

![image](https://user-images.githubusercontent.com/5963862/81489195-e4a80400-9240-11ea-84c4-8507028ee0e6.png)

I am not sure if you want to adjust the test setup, the testing comparisons, or just leave it be.  I can ignore it.
