### ISSUE TITLE
Fractional values not supported

### ISSUE THREAD

**Issue by thurn** [Helfima/helmod#27]
It seems that all recipe inputs are rounded to the nearest whole number. This can lead to inaccurate results if you're clicking through a bunch of recipes. In this example, I wanted 2 solder/second, which will require 0.5 resin/second. I am incorrectly told that I will need 10 assembly machines producing resin, when in fact I only require 5 assembly machines.

<img width="1383" alt="screen shot 2017-03-14 at 8 20 55 am" src="https://cloud.githubusercontent.com/assets/166344/23907695/2d3e38c2-088f-11e7-8e04-e0c1358486a6.png">

**Comment by Helfima** [comment]
I look at this after work unless I have the screen of the recipe edition on the resin

**Comment by Helfima** [comment]
ok i have no the same bob mod
what is version of mymod and get list of bob mods

**Comment by thurn** [comment]
This is a direct clone from github yesterday with bob's electronics 0.14, but I think you should be able to reproduce with basically any recipe that produces its output item in multiples.

**Comment by Helfima** [comment]
i try with my bob mod and i have not the same result
could you make a screen of recipe edition of resin

**Comment by Helfima** [comment]
i mean you must use the limit block see my sample
http://i.imgur.com/KKtojzG.png

**Comment by Helfima** [comment]
decimal is changed in 0.3.0 of my mod
