### ISSUE TITLE
Negative pollution values result in error

### ISSUE THREAD

**Issue by greenskye** [Helfima/helmod#270]
When utilizing Bob's god modules, it's very easy to get to a negative pollution modifier. This seems to break Helmod and it refuses to add the module to the production block. The game seems to work with  this fine, so it's a valid set up.

Error message is:

"__helmod__/data/ModelCompute.lua:786 attempt to index field 'polution' (a nil value)

**Comment by Helfima** [comment]
hello, helmod version?

**Comment by Helfima** [comment]
ok I reproduced the error and I saw another problem
this zip file fix the error
[helmod_0.10.19.zip](https://github.com/Helfima/helmod/files/4605126/helmod_0.10.19.zip)

**Comment by Lexanius** [comment]
Hello,

i have same error still in my savegame. Version is 0.10.19 via regular update.

If i remove the mod and load the savegame i still get this message. 
Also I also get the message still after disable the god modules.
What should i do?

**Comment by Helfima** [comment]
fixed in v0.10.20
