### ISSUE TITLE
Krastorio2 recipe causes fatal error.  Fix already found. 

### ISSUE THREAD

**Issue by prs9tb** [Helfima/helmod#271]
I believe I've already found an easy fix for this error.  

With Krastorio2 and Helmod installed, clicking on a recipe in Helmod has no effect, and instead shows this game message: 
`__helmod__/model/RecipePrototype.lua:327: attempt to index field 'effects' (a nil value)`

Looking into the mod code, I simply added a check in model/RecipePrototype.lua before accessing factory.effects on line 327.  This appears to solve the issue on my end.  Adding or changing recipes with this change works normally now.  

    if factory ~= nil then
      speed_factory = factory.speed
      if factory.effects ~= nil then  -- << THE FIX
        consumption_effect = 1 + (factory.effects.consumption or 0)
      end
    end

**Comment by Helfima** [comment]
duplicate #268 
fixed v0.10.19
thx for report
