### ISSUE TITLE
Beacons are not preserved by "upload"/"download" of production line

### ISSUE THREAD

**Issue by RalfJung** [Helfima/helmod#274]
For a multiplayer game, I have set up a production line in an offline copy of the game that I wanted to move into the main online game (which is hosted by someone else) by "uploading"/exporting the entire production line to a string, and then "downloading"/importing that string in the online game.

Unfortunately, the beacon settings were lost in that transition, so I had to re-configure all beacons. Looks like somehow either the beacon information is not encoded in the string, or is not imported properly.

This is using 0.10.19 with Factorio 0.18.24. I also have Krastorio2 version  0.9.17 installed, and a bunch of minor mods.

PS: Thanks for this mod, it is awesome. :)

**Comment by Helfima** [comment]
fixed in v0.11.7

**Comment by RalfJung** [comment]
Thanks :)
