### ISSUE TITLE
Cyclic recipes broken

### ISSUE THREAD

**Issue by andreasferber** [Helfima/helmod#275]
The latest update (0.10.20) seems to have seriously broken the handling of cyclic recipes.

For example this biter breeding cycle from Angel's Bio Processing:
![Helmod_Crystals_0 10 20](https://user-images.githubusercontent.com/4956110/82484285-007d9680-9ada-11ea-85d1-d75bc487e97b.png)

Switching between matrix and algebraic solver has no effect, neither has applying the new capability of declaring master and excluded products in various combinations.

Same recipes with 0.10.19 matrix solver instead:
![Helmod_Crystals_0 10 19](https://user-images.githubusercontent.com/4956110/82484977-0627ac00-9adb-11ea-9ead-788f23a001de.png)

None of the mods providing those recipes updated in the last few days, and downgrading Helmod to an earlier version fixes it, so I can rule out that it's caused by any recipe changes. And a build based on the ratios given by 0.10.19 is currently working in my base, so the results are definitely right, while the 0.10.20 results are obviously wrong (it almost looks to me as if it doesn't consider outputs from a production block as valid inputs for that block anymore)

**Comment by Helfima** [comment]
Hello
The solver is not broken but the input data changed
I rollback that in next release

**Comment by Helfima** [comment]
fixed in v0.10.21
