### ISSUE TITLE
Base productivity of machines is ignored

### ISSUE THREAD

**Issue by skraman2002** [Helfima/helmod#276]
Title is self explanatory. Only relevant to a select few mods, but I imagine it would be pretty easy to implement.

Awesome mod, thanks for all your work!

**Comment by Helfima** [comment]
hello
you are a sample, a mod and a machine
I must test

**Comment by skraman2002** [comment]
Attached is a mod that gives the vanilla entity "assembling-machine-3"  a base productivity of 50.

[helmod-test-mod_0.1.1.zip](https://github.com/Helfima/helmod/files/4663482/helmod-test-mod_0.1.1.zip)
%.

When selecting the assembler type to make a recipe, mousing over the assembler mk3 shows the tooltip with the correct base productivity (under the crafting speed, power usage etc), however helmod does not take the base productivity into account for the recipe

**Comment by Helfima** [comment]
fixed in v0.10.21
