### ISSUE TITLE
[Bug] New base game focusing causes helmod windows to be hidden

### ISSUE THREAD

**Issue by evandy0** [Helfima/helmod#278]
With the recent update to the base game, if you click the main helmod dialog while any of the sub-dialogs are open, the main helmod window now occludes the subsidiary dialogs (recipe editor, recipe selector, etc.).

Either one of the following 3 fixes should be employed:

1. dialogs are closed when they lose focus
2. dialogs should be forced to "stay-on-top" which was the old base-game behavior
3. pressing the button to reopen the dialogs should bring them back to the front.

**Comment by Helfima** [comment]
hello
I know, this change without solution to choose the depth destroyed the operating logic

1. impossible with API there are no event on lose focus and the dev say: never
2. impossible, actually there are nothing to do that with style or API
3. I don't like that

probably I add a close event on my open event :)

**Comment by Helfima** [comment]
fixed in v0.10.21

when event open form, it's rebuilt to go front
