### ISSUE TITLE
Beacons: [Amount, affecting one] is not correctly stored in defaults/copies/exports

### ISSUE THREAD

**Issue by alexkaratarakis** [Helfima/helmod#280]
Repro steps:
1) Create any recipe and add a beacon with "Amount, affecting one" = 7 (anything other than the default 4).

A) Copies
2) Copy paste the recipe: "Amount, affecting one" will be 4, instead of 7

B) Export-Import
2) Export the recipe (Upload Production Line)
3) Import the recipe (Download Production Line): "Amount, affecting one" will be 4, instead of 7

C) Defaults
2) Under "Active Modules", click the first button to "Set Default".
3) Add the same recipe again: "Amount, affecting one" will be 4, instead of 7

Other beacon properties work fine:
- "Beacon by factory"
- "Constant Beacon"
- The module types selected for the beacon

so, it is just "Amount, affecting one" that doesn't propagate correctly.

Helmod 0.10.23.

**Comment by Helfima** [comment]
I must review that
