### ISSUE TITLE
Helmod with pyblock, moss farm eroor

### ISSUE THREAD

**Issue by WarlordFTW** [Helfima/helmod#288]
I am using Helmod with pyanodons suite with pyalienlife and pyblock, and without any update to either, helmod started throwing this error:
![image](https://user-images.githubusercontent.com/69766179/90340954-3d660600-dfc1-11ea-9a54-9f2a5aad01b7.png)
and shows no modules.
I have already tried uninstalling and reinstalling helmod
Thanks

**Comment by Helfima** [comment]
no response
