### ISSUE TITLE
Missing purple Production Science packs in recipe selector

### ISSUE THREAD

**Issue by Lethann** [Helfima/helmod#289]
Factario 1.0.0 (build 54899, win64, steam)

Helmod v0.10.25

---

I haven't seen this mentioned anywhere but I finally got my latest game up to making the purple science packs and it's not showing up in Helmod at all.

**Comment by Lethann** [comment]
I didn't have that selected, but it was already researched. In fact both purple and yellow were not showing up and both were researched. After this latest update that was pushed today they both show up just fine. (sorry for not responding sooner but my notifications were not coming through from github)

**Comment by Helfima** [comment]
no problem
that's ok now
