### ISSUE TITLE
Broken Rendering for Products and Ingredients

### ISSUE THREAD

**Issue by Recon419A** [Helfima/helmod#290]
There is currently (0.11.1) broken rendering of products and ingredients - at least with the set of mods I'm using. To my knowledge, nothing in here should be screwing with Helmod, but I'll include the modlist just in case.

![Capture](https://user-images.githubusercontent.com/16583234/91669650-0cff8b00-eadc-11ea-8a48-405db2065fb9.PNG)

**Comment by Recon419A** [comment]
Here's the modlist: https://pastebin.com/t6VbQjPx

**Comment by Helfima** [comment]
hello, could you put a new saved game, I have no enought time to check mod list.

**Comment by Recon419A** [comment]
[Default.zip](https://github.com/Helfima/helmod/files/5151337/Default.zip)

Here's the save file exhibiting the issue.

**Comment by Helfima** [comment]
[helmod_0.11.1.zip](https://github.com/Helfima/helmod/files/5152802/helmod_0.11.1.zip)
this version fix your problem
I will investigate more for the next version

**Comment by Recon419A** [comment]
Awesome, thanks!

**Comment by Helfima** [comment]
fixed in v0.11.2
