### ISSUE TITLE
Cannot open Helmod window in 0.11.4

### ISSUE THREAD

**Issue by Neerti** [Helfima/helmod#295]
Details:
OS: Ubuntu 18.04.5 LTS x86_64
Factorio Version `1.0.0 (Build 54889, linux64)`, tested both with Steam version and standalone.
Helmod Version `0.11.4`
Ran into this while playing the Seablock pack but the error is reproducible even if Helmod is the only mod loaded.

Pressing the button to open the Helmod window causes the error `__helmod__/data/Model.lua:152: attempt to index local 'models' (a nil value)` to display in the chat log, and the window to not open, effectively breaking the entire mod.

This happened in both the latest Steam release and the standalone executable downloaded from the official factorio site. This error does not happen on version `0.11.3`. Since 0.11.4 came out yesterday as of the time of this bug report, I assume a change broke it, so I thought this would be something you would want to know about.

**Comment by Helfima** [comment]
hello, it was a stupid error fixed in v0.11.5
