### ISSUE TITLE
"Ingredient input" setting is forgotten on copy-paste

### ISSUE THREAD

**Issue by RalfJung** [Helfima/helmod#303]
To reproduce:
* set up a large production line where some production blocks are marked as "linked block" and "ingredient input"
* copy the entire production line
* create a new production line, and paste
* open the "linked block" "ingredient input" block and notice that "product input" is selected instead of "ingredient input"

Expected behavior:
* "ingredient input" setting should be preserved by copy-paste

**Comment by Helfima** [comment]
normaly it's fixed in v0.11.13
