### ISSUE TITLE
Clicking the toggle buttons (product input / ingredient input, and others) toggles them back immediately 

### ISSUE THREAD

**Issue by RalfJung** [Helfima/helmod#304]
Steps to reproduce:
* Open Helmod, and open any production block
* Click the toggle button thing for "product input / ingredient input" (do *not* click the text, but the button between the two labels)

Expected behavior:
* The button toggles from one state to another

Actual behavior:
* The button toggles from one state to another and then immediately snaps back again. I thought I was doing something wrong here, there was some error that made helmod take back the toggle. It took me a few minutes of being increasingly irritated until, by mere accident, I clicked the text instead of the button, and that worked.

**Comment by Helfima** [comment]
hello, 
yes it's a old bug
it will fix in next release

**Comment by Helfima** [comment]
fixed in v0.11.14
