### ISSUE TITLE
Еrror with add module from py-addon

### ISSUE THREAD

**Issue by ko5h** [Helfima/helmod#313]
![img](https://i.imgur.com/02wxmUg.png)
7 modules can be added to fish farm, but the helmod does not allow

**Comment by Helfima** [comment]
Hello, yes I saw too this error today ;)
a quick fix
[helmod_0.11.19.zip](https://github.com/Helfima/helmod/files/5568931/helmod_0.11.19.zip)

**Comment by Helfima** [comment]
fixed in v0.11.20
