### ISSUE TITLE
Production modules not allowed

### ISSUE THREAD

**Issue by Helfima** [Helfima/helmod#316]
Hello,

I am playing a PyAlienLife game and without Helmod i would be lost, so thank you.
Enough with the sappiness, I am using the "Productive Pyanodon" mod and bob's modules (using god's modules) and for some reason helmod thinks I am not allowed to use production modules on any recipe, even if the machine and recipe take them.
Am I using some settings incorrectly? Is there some tweak I can do to make helmod use productivity modules?
I have another game in which I had no problems, but I was not using Productive Pyanodon nor god's modules, if this helps somehow...

Thank you again!

source: https://mods.factorio.com/mod/helmod/discussion/5fbaf30ad6996deffc1373c2

**Comment by KiwiHawk** [comment]
This appears to be working correctly. Maybe it was fixed by #357 ?
