### ISSUE TITLE
Desync on MP when closing a pinned window 

### ISSUE THREAD

**Issue by Xelan255** [Helfima/helmod#32]
Hi,
first of all: great mod, just perfect for those big bases with quadzillions of different (mod) products and I just love to plan my next production line ahead and min-max the shit out of it :)
Unfortunately I had to notice a rather annoying thing. I play on a headless server with a friend and sometimes (not every time, but often enough) when I close my pinned production line window I'll get a desync and have to restart the game. I attached my log file from such a desync, maybe you can look into it? Oh and I once had the same desync issue multiple times in a row while trying to select another production building for a given recipe, so maybe it's not just related to the pinned window.
[factorio-previous.txt](https://github.com/Helfima/helmod/files/858755/factorio-previous.txt)

**Comment by Helfima** [comment]
Yes there seems to be a small error pinned production, on the other hand concerning the desynchronizations I play in MP I never had a problem but I think it can come from the connection between the players, the data of the mod that transit are may be too large

**Comment by Xelan255** [comment]
well that sounds solvable. I have to add though, that I often had this problem when I was alone on the server, so there was only one other entity to transmit data to and that is the server itself. Then again, I guess the server is treated like just another player, isn't?

**Comment by Helfima** [comment]
For you is exactly same, if the connexion between player and server is too lower you can have desynchronizations.

![factorio_server_player](https://cloud.githubusercontent.com/assets/20326713/24214146/f832a576-0f34-11e7-99e6-f3d2420be25b.PNG)
![factorio_server](https://cloud.githubusercontent.com/assets/20326713/24214155/00bde462-0f35-11e7-9978-d860722ed0d5.PNG)

is the same for player 2 but different for player 1

**Comment by Xelan255** [comment]
Yeah, thought so. Question is: can you do something about the problem?^^

**Comment by Helfima** [comment]
i go analyze my code this weekend, I work in week :)

**Comment by Xelan255** [comment]
Wow,I just saw your edited post today. Kinda expected a new post, so I would receive an email^^ I've turned the debugging on, but as of now I wasn't able to recreate a desync. Figured. If you want something to crash it doesn't. What I noticed so far though was a "server not responding" every time a opened the planner and sometimes when switching to another category (like summary or ressources). Not sure if that was the case with debugging turned off.
I don't have the time for further testing right now, but I'll get to it again later today or tomorrow

**Comment by Xelan255** [comment]
Finally. Hadn't had much time for Factorio the last couple of days, but here you go. Happened relativly fast this time, had multiple tests with 175MB+ log file.

[factorio desync crash logged.txt](https://github.com/Helfima/helmod/files/883929/factorio.desync.crash.logged.txt)

**Comment by Helfima** [comment]
i can't reproduce and i have never problem in my MP games
