### ISSUE TITLE
Disabled recipe smart filtering

### ISSUE THREAD

**Issue by danyax** [Helfima/helmod#321]
When playing Angel Bob game, lots of Bob recipes are disabled for good - they are replaced by equivalent Angel recipes and will never be enabled by research. 

Would it possible to filter these "permanently disabled" recipes for option "Show disabled" mechanics?

**Comment by Helfima** [comment]
hello,
you have a sample?

**Comment by danyax** [comment]
Wrong recipe, never unlocked
![20201201220208_1](https://user-images.githubusercontent.com/61344188/100784961-0b1dce80-3421-11eb-8fa7-1332e614207e.jpg)
Correct recipe
![20201201220215_1](https://user-images.githubusercontent.com/61344188/100784978-0fe28280-3421-11eb-9466-462bf6149ee4.jpg)
This how crafting window locks with all tech unlocked
![20201201220250_1](https://user-images.githubusercontent.com/61344188/100784985-13760980-3421-11eb-9306-87788d14cc54.jpg)

**Comment by Helfima** [comment]
I don't know how detect when recipe is not use
![image](https://user-images.githubusercontent.com/20326713/100805963-e67d2300-342f-11eb-8568-c116167d9e58.png)
for me, angel Mod will not have to add the recipe if it is not used

**Comment by danyax** [comment]
I think the easeit way is to check if recipe is unlocked by some non-hidden technology, as in A&B game lots of Bob techs are hidden for good.

Angels does not add those recipes, they are added in Bob mods, Angel just disables them and never unlock by new tech tree

I do not understand what [R] means. red-circuit-loaded is definitely unlocked by tech. You might not enables "component overhaul" and "tech overhaul" options which change tech tree extensively.

**Comment by Helfima** [comment]
added in next release v0.12.2
