### ISSUE TITLE
Crash when attempting to use Angels clarifiers recipe

### ISSUE THREAD

**Issue by Nagapito** [Helfima/helmod#33]
![capture](https://cloud.githubusercontent.com/assets/4959346/24322568/859ca684-115e-11e7-9b9d-3064af26cdcc.PNG)
 
This was on a headless server, so when I stopped it, it saved the game with the clarifier recipe already added to helmod. So, after restart, if I try to open helmod, recipe is there and keeps crashing....

**Comment by Helfima** [comment]
ok, i can't reproduce but i see a NaN value
i fix it soon

**Comment by Helfima** [comment]
try version 0.3.1 normaly it is resolve

**Comment by Nagapito** [comment]
Doest crash anymore.

Electrical consumption says NaN GW and if I change the output amount it then shows Inf  GW.

but... I understand adding void recipes to the production block might not make much sense.... (Was trying to void the water, so it didnt showed on the outputs....) At least, now, it doesnt crash the game when added by mistake.

Thanks for the quick fix

**Comment by Helfima** [comment]
I just fix the crash, not the problem
Normally there will be a value
i must add a output command for see the model :)
