### ISSUE TITLE
Matrix Solver - Space Exploration loop and marking as main produces incorrect results

### ISSUE THREAD

**Issue by MarcBridner** [Helfima/helmod#330]
Hi

Helmod: 0.12.3
Space Exploration: 0.5.33

Trying to make a production line for "Broad Deep Space Catalogue" in Helmod:

1. Enable Matrix Solver
2. Add "Broad Deep Space Catalogue" and set target output to 1000 per minute.
3. Click "Timespace Anomaly Data" in the Ingredients column. "Timespace Anomaly Data" is now added, production is 100% and 1000 "Timespace Anomaly Data" are produced with by-products, including "Blank Data Card", which is correct
4. CTRL+Click "Timespace Anomaly Data" in Products column to mark it as main product
5. Click "Singularity Data" in the Ingredients column. Output is still correct.
![helmod1](https://user-images.githubusercontent.com/3307536/106242429-88b15100-61bc-11eb-8cb1-f6ac759f721f.PNG)
6. Click "Annihilation Data" in the Ingredients column. "Timespace Anomaly Data" now at 200% production and suddenly produces 2000 units instead of 1000 due to the "Blank Data Card" being produced by "Timespace Anomaly Data" being used to fill the "Blank Data Card" demand for "Singularity Data" and "Annihilation Data"
![helmod2](https://user-images.githubusercontent.com/3307536/106242439-8b13ab00-61bc-11eb-9c40-a099f74f7a95.PNG)

I do not want it to try to fill the demand for "Blank Data Card" by increasing production when "Timespace Anomaly Data" is marked as main. It should add "Blank Data Card" to the Input list instead.

Have attached production line. [helmod.txt](https://github.com/Helfima/helmod/files/5892084/helmod.txt)

**Comment by Helfima** [comment]
hello
Matrix Solver ignore the main or exclude product
main or exclude product added for the other solver
I not sure if it's possible to add that in matrix solver.

**Comment by MarcBridner** [comment]
Ah, that definitely makes more sense.

Is there any way to force Helmod to NOT double the "Timespace Anomaly Data" in this case?
Adding "Blank Data card" as a recipe does nothing, it gets 0'ed out, regardless of what position I put it in

**Comment by Helfima** [comment]
probably in your case you dont need matrix solver
![image](https://user-images.githubusercontent.com/20326713/106386480-76f6c600-63d5-11eb-93f2-c8e0f210c377.png)
you have a large screen, you can change the line display
![image](https://user-images.githubusercontent.com/20326713/106386533-b7eeda80-63d5-11eb-918e-031797e40e3c.png)

**Comment by MarcBridner** [comment]
You're right that I don't need the matrix solver in this particular example. I tried to simplify the reproduction case as much as possible, in my real configuration definitely need this in a matrix solver (and there's 18 blocks with over 100 steps)

If it's not possible to give the matrix solver a hint on what to ignore or what not to double, that's okay - I can try separating it into multiple blocks/production lines

Thanks for the tip about the row display!
