### ISSUE TITLE
1.1 Version.

### ISSUE THREAD

**Issue by BeebBeebBoob** [Helfima/helmod#331]
I know it is stupid question but i'm very worried seeing that the mod is marked red and says it's not compatible with 1.1. Is it okay to play 1.1 or it's gonna crash? If it will crash is there a hope to update helmod?

**Comment by Helfima** [comment]
no there are'nt no risk.
helmod v0.11.x is for factorio 1.0
helmod v0.12.x is for factorio 1.1
if the mod is red, update him. you can up or down version
