### ISSUE TITLE
Copy Paste Issue

### ISSUE THREAD

**Issue by Firemonkey08** [Helfima/helmod#333]
If I try to copy and paste a block or a line, it pastes one specific block every time. I tried to copy another block, but it´s every time this one block it copies. Reload or restart doesn´t help. If I start a new game, I can´t copy and paste anything. It simply doesn´t do anything.

Edit: Same with upload/download. It download the specific block no matter which code I use.
If I delete the specific block which would be copied, I can´t copy/paste anything too.

**Comment by Helfima** [comment]
hello, I try and I have no problem
what version of helmod?
if you can give me your game to check the problem

**Comment by Firemonkey08** [comment]
Helmod v0.12.5. My friend has the same problem. Savegame or log or which file do you need? Upload to a normal upload site?

**Comment by Firemonkey08** [comment]
I used 0.12.4. But with 0.12.5 the problem is solved. Strange.

**Comment by Helfima** [comment]
oh yes it's strange, probably a problem with a cache
