### ISSUE TITLE
Bug when calculating number of nuclear reactors needed for a given heat output

### ISSUE THREAD

**Issue by nick4333** [Helfima/helmod#340]
I'm not sure if this is solvable currently, and I have not looked at the code because I'm not familiar with LUA. The screen should read, 4 nuclear reactors as when you put two reactors next to each other you get a bonus for heat production. 
![Bug](https://user-images.githubusercontent.com/34627440/113257819-c3089e80-9290-11eb-8632-f6f1a28a1bd1.png)

**Comment by Helfima** [comment]
hello you can choose 1, 2, 4 or 8 reactors settings in the recipe edition
it's enougth?
