### ISSUE TITLE
Recipe Selector screen from Helmod opening up with Trains window.

### ISSUE THREAD

**Issue by Dark-Wynd** [Helfima/helmod#341]
Whenever I open up the Trains overview window (With the 'O' key) the Recipe Selector window from Helmod keeps opening up at the same time.

This makes it very annoying to adjust my trains schedules.

Is a particular action bound the the key 'o' with Helmod ?
Can it be changed to another key binding ?

**Comment by Helfima** [comment]
you can change the binding key in the game settings, check where you can change the control key
