### ISSUE TITLE
Heat Exchanger uses way more heat then its maximum consumption

### ISSUE THREAD

**Issue by sandervdbosch** [Helfima/helmod#342]
When trying to calculate the output of nuclear reactors I found a problem with the steam generation through heat exchangers.
When I set one heat exchanger to full production per hour I get three times the amount of steam and the heat input is way to high as the maximum intake should be 10MW while the ingredients suggest I need 3.4GW.
![Screenshot 2021-04-26 172931](https://user-images.githubusercontent.com/24452621/116109404-04844200-a6b5-11eb-94d6-d355f40ffcd2.png)

**Comment by Helfima** [comment]
hello it's normal, heat is joule but in factorio we use W, 1J=1W
you can read 3.4GJ
