### ISSUE TITLE
Angels plastic propene chain doesnt update correctly

### ISSUE THREAD

**Issue by Nagapito** [Helfima/helmod#35]
After I create the full chain for producing plastic with propene from natural gas, using Angels Petrochem, if I increase the output amount of plastic, the chain updates correctly. 

But if I then reduce the amount of plastic, the steam cracking methane does not update and does not reduce the amount produced.  

This happens on 0.3.1 and 0.3.0

**Comment by Helfima** [comment]
Could put the screens, it's easier to understand
and push the log (factorio-current.log)

**Comment by Nagapito** [comment]
Set the recipe for the first time to output 100 plastic:
![capture](https://cloud.githubusercontent.com/assets/4959346/24331245/09d0c6c8-1228-11e7-95e3-c6dcc0371800.PNG)
Changed it to output 200:
![capture2](https://cloud.githubusercontent.com/assets/4959346/24331251/11bb469c-1228-11e7-871d-0e9f26f3cccd.PNG)
Changed back to 100:
![capture3](https://cloud.githubusercontent.com/assets/4959346/24331252/1900d41c-1228-11e7-9c7a-0e18a74bcb21.PNG)

The metanol ammount and the rest of the chain didnt recalculate and now I have a surplus of methanol 


[factorio-current.zip](https://github.com/Helfima/helmod/files/870736/factorio-current.zip)

**Comment by Helfima** [comment]
it's fixed in 0.3.2
