### ISSUE TITLE
Migration crash in 0.3.0 migration script

### ISSUE THREAD

**Issue by cpw** [Helfima/helmod#36]
I have a migration crash with the 0.3.0 upgrade script. It seems that "model" is a number on line 322 of helmod.lua in some circumstances. I had some "empty" production lines.

My fix was to wrap the rest of the loop with an "if type(model) == "table"" statement, however, I'm pretty sure that's not really very good. I can supply a save that'll crash, if you need it.

Note: I'm running 0.3.2, migrating from last version before 0.3.0.

**Comment by Helfima** [comment]
hello thx
i must add a test on model variable

**Comment by Helfima** [comment]
When loading the game saved with version 0.2.25, a crash occurs with an error:

Error while running the on_configuration_changed: helmod / helmod.lua: 322: attempt to index local 'model' (a number value)
