### ISSUE TITLE
Error on opening Pin Panel (0.12.6)

### ISSUE THREAD

**Issue by KiwiHawk** [Helfima/helmod#360]
![image](https://user-images.githubusercontent.com/59639/133983003-1db4f749-f9da-4776-b93e-1899b1029f1e.png)

Press pin button. Pin panel opens but does not show details. Error message: 

`Script @__helmod__/controller/DispatcherController.lua:74: __helmod__/gui/GuiElement.lua:131: bad argument #1 of 3 to 'concat' (table expected, got nil)`

Issue does not occur in release version (0.12.5) but only in GitHub version. 

I believe the issue was caused by commit 9fd0341c5cbe00c404c164d8eb0379d6178a6e45 changing gui\GuiCell.lua from

```lua
function GuiCell:mask(mask)
  self.m_mask = mask
  return self
end
```
to
```lua
function GuiCell:mask(mask)
  self.m_mask = mask
  return GuiCell
end
```

A similar change was made to gui\GuiSlider.lua

**Comment by Helfima** [comment]
fixed in v0.12.6
