### ISSUE TITLE
plans to update to factorio 0.15?

### ISSUE THREAD

**Issue by vanatteveldt** [Helfima/helmod#38]
Are there any plans to update this to factorio 0.15? I guess the dynamic recipe cost could make it more difficult...

**Comment by Helfima** [comment]
yes please wait few days, i work on but 0.15 have break the solution to expose data raw

**Comment by Helfima** [comment]
is fixed for 0.15 u can download

**Comment by vanatteveldt** [comment]
Thanks! I can use the help figuring out the new ratios and science packs :)
