### ISSUE TITLE
Bobs Mining Mod Steam Powered Mining Drills do not scale mining speed correctly

### ISSUE THREAD

**Issue by Blu3wolf** [Helfima/helmod#388]
Bobs Mining Mod adds steam powered mining drills, which scale their mining speed based on steam temperature. With low temperature steam, they should have a speed of 0.4, while at max temperature they should have a speed of 2.

Helmod doesnt account for this, and displays the mining speed as 2 regardless of the selected steam temperature in the recipe. As a result it is not currently possible to calculate with Helmod how many steam mining drills are required unless steam temperature is at max already. 

Related to #237, #359 and #365

**Comment by Blu3wolf** [comment]
This also appears to affect steam powered inserters, which have a similar scaling behavior. As the logistics window in Helmod does not appear to have a way to select fuel used by inserters, this would not appear to have a simple fix.

**Comment by KiwiHawk** [comment]
I should be able to fix the first part. Probably going to ignore the steam inserters though sorry.

**Comment by Blu3wolf** [comment]
I suspected that might be the case for the inserters! 

Perhaps this could be reviewed for a future improvement to the logistics section of the mod? A few times Ive wanted to know "How many inserters do I need per building" or "how many inserters do I need for 2 out of 3 products", etc. 

If thats the case, it could probably be better served by being split into its own issue.

**Comment by KiwiHawk** [comment]
Yeah, definitely separate. The required number of inserters should be considered an estimate at best. There are a lot of factors that affect inserter item throughput:
- Inserter rotation speed
- Picking up / dropping off to belt vs chest
- Belt speed
- Available space on belt
- Inserter capacity research (+ override)

Additionally if using Bob's Adjustable inserters or similar mod:
- Inserter angle
- Offset
- Change in arm length
