### ISSUE TITLE
Stone furnaces throw off energy calculation

### ISSUE THREAD

**Issue by helpiminabox** [Helfima/helmod#39]
So, I was messing around with the mod, seeing what a hypothetical smelting line would require. Apparently the mod doesn't know that stone furnaces don't get power from the electrical grid, because it recommended I power the furnaces with 77 steam engines.

**Comment by Helfima** [comment]
There has been a change in the 0.15 that produces this, I have to integrate a new test

**Comment by Helfima** [comment]
resolve in 0.4.1
