### ISSUE TITLE
Inserters comsuption in block

### ISSUE THREAD

**Issue by slasherbane** [Helfima/helmod#392]
Hi , i 'm very interesting in your mod for planning my base , but i didn't find a way
to add the energy comsuption of all of my inserts into a block or production line .

There is a way todo that or no ?

Thks

**Comment by KiwiHawk** [comment]
Currently, there's no way to do this sorry!

**Comment by EdwardMcCants** [comment]
Personally, I would appreciate the capability to compute and balance energy consumption and production.  This would be a necessary feature for that capability.

**Comment by KiwiHawk** [comment]
> Personally, I would appreciate the capability to compute and balance energy consumption and production.  This would be a necessary feature for that capability.

You can already compute energy production. Most energy consumption is calculated, except for inserters. If there's something else that you believe is missing, can you please explain it in detail in a new issue? Thanks!
