### ISSUE TITLE
Assembly machine selection not possible when using Bob's electronics recipes

### ISSUE THREAD

**Issue by Liquid5n0w** [Helfima/helmod#4]
When using helmod with bob's mods, if you pick one of his electronics recipes you don't get the option of selecting an assembly machine.

![image](https://cloud.githubusercontent.com/assets/9867874/18352113/1518c3b0-75ab-11e6-8641-c1421df7eff6.png)

**Comment by Helfima** [comment]
remove filter on factory in Options menu https://github.com/Helfima/helmod/wiki#options
the filter is not perfect for MOD i need resolve
