### ISSUE TITLE
Automatic calculation not respecting minimum products produced per recipe

### ISSUE THREAD

**Issue by helpiminabox** [Helfima/helmod#41]
I'm setting up a block for all of my science production. Decided to include red and green science as well as the requirements for assembly (so, inserters, gear wheels, circuits, etc.). For iron gears it's telling me I should put in 5 iron plates for 2.5 iron gears instead of the expected 6 for 3, because the concept of 0.5 gear wheels is silly.

**Comment by Helfima** [comment]
je suis en parti d'accord mais cela fausse les autres calculs.
it removed at this issue https://github.com/Helfima/helmod/issues/27
