### ISSUE TITLE
Output quantity is wrong

### ISSUE THREAD

**Issue by KiwiHawk** [Helfima/helmod#414]
Mod list
- Helmod
- Omnimatter
- Omniwater

In the following screenshot, output of Omnic Waste should be 0, not 170.3

![image](https://user-images.githubusercontent.com/59639/178140756-8aa7734b-4113-49de-9559-3e084053f64e.png)

<details>
  <summary>Import string</summary>
H4sIAAAAAAAA/91Xz2+jPBD9VyrODjK/qSruK+2t11UVOeBkrRqMwDQbVfzvO8YYTCHdNt/la5GlYGfm2fPmeTIpxB0XOeF3++yVFZlTioLyfeAgca5okzk/
2Zn9IOdnBx3A7rnNXofPvafNx4mDKlLSzBFlxfLdmbSS7hqaX3LOqtMGVi66SmYeqsUZvsAIrBpaMFpJ2OCXDeM8Za8rbAfJSw1LR96xwqBh1EoiaYZ7WCDc
uKl3Y88kLSdzF+MkjUPPm0YQjRA+kgx8vR7NZ5G0WZ9FLW6dxQ/dwA+n4d+HK2QFAQsW4BzX8pyh78XWiNK3WD2qG1F0+ZK8Tx3YkOf3aDAyftc9PKzSVnf6
TXt7G7x9Kodegl0/wfOIR+RgjhV0xWoKoT6OGnwE+bGqoH9g/3kbMNPx7gZuG5JLJqodMftqmJllP3nzGFLBC4CP4C+aiwnk0DWVDS0mkkDDTF5mXC9Ilw+i
4Hm6KNqwYq6mtIANOCuZygNcwI6r8HpEj0c6JFXb4OlEL7ADTHNRtV1ZDyeELwXnnX6HG0DqW9ysiYuTaDzqXgoJF8qyNSsu9nDoxdYToWNH+XjtenSgBLab
WBtmmyo3rITpwEouyoPIQlTTZm+ox25kz/cqDknAOdgkb3H0ftTPLRH16NEfleYbpeH3C962xEIc2SPxbInhdyRW/+bidE1ga1RD5f9dYPcLnuP4I9kJkkUx
TMMvr7dVRKC3aNRbZPTmv6lsVj1f1rfimvhwEHmLES/U56ZJGlgj9P9DyUui2B7freQFywDTLy/BVUTwM2vqXFdBSXsGUmXTUdQK/gLdwfC+1Nm42QZ6DLSG
ETbD9xDkoiRKWYeO8QIqJsSjQ2R06GE2tPb0bx3a7PqqB1mV0C2QRXG1IVSzodOnut6PZhWc5pQAwGVK5pHwlg7Mbja7Y7+meY/RzY3m2wZTAybolkbTarpa
0TW51tmYahBCq+6Ng917N4jmJkz/KWDqimt1qPfIalLHFnNZ2t5vNa82lhokWP8ef7TBnGKcVPktpYisuzYWHrwsfqt72qOTsiQQFyCQPO/KjquZ2dta2j4A
BA4VgzS7mlSUzzHbi1cdJSXljlYnVln/IBar20H3Dw2VQOrd/oFWxV8kQMsp4Q4AAA==
</details>

**Comment by KiwiHawk** [comment]
I don't think matrix solver should be able to calculate this. The percentage for the first recipe can't be set as there is no demand for Omnic Water at that stage.

I would expect it to look like this:
![image](https://user-images.githubusercontent.com/59639/178141439-82522a1f-649f-471f-bc2f-40935b04a503.png)

**Comment by KiwiHawk** [comment]
Problem is in `SolverSimplex:lineCompute`. Production and Coefficient are both being set to 0 as Z demand is 0:
https://github.com/Helfima/helmod/blob/2123046d00ccd1141448a2ec75dc99168808cbc5/math/SolverSimplex.lua#L195


Because of this, Z running total is not updated:
https://github.com/Helfima/helmod/blob/2123046d00ccd1141448a2ec75dc99168808cbc5/math/SolverSimplex.lua#L213


![image](https://user-images.githubusercontent.com/59639/178239742-eec54936-1d61-4489-bd7e-6e3b09e48a96.png)

**Comment by Helfima** [comment]
same issue Matrix solver with omni fuel #415
the input must be the primal recipe we can do better
![image](https://github.com/Helfima/helmod/assets/20326713/6ee9cba3-b09c-4b16-a954-bf44a7c06a83)
