### ISSUE TITLE
Matrix solver with omni fuel

### ISSUE THREAD

**Issue by KiwiHawk** [Helfima/helmod#415]
Mod list
- Helmod
- Omnimatter
- Omniwater

Picking an omni item as fuel causes matrix solver to calculate strangely
![image](https://user-images.githubusercontent.com/59639/178141016-f5d882e7-fc8b-4ce5-a8cb-87d264d9a0ae.png)

Works as expected when picking a vanilla fuel item or switching to electric machines
![image](https://user-images.githubusercontent.com/59639/178141042-9b1af06b-ae4e-41d1-939d-1587ae9380e6.png)

<details>
  <summary>Import string</summary>
H4sIAAAAAAAA/91WTW/jIBD9K5XPJMJOnA9Vvq+0t16ryiI2yaJisGxoNqr833cwxsaJk1bZPaziS4Awj5k3j2Fy+cRlRvhTmnyyPAkKmVOeLgIkj4JWSfCT
HdkPcnwP0A72vdfJZ/ubhnZ7NwmQIAVNAlkIVtFsdiSKVjMzUxXJFJNiRiYgM6mFSkJUyiP8gRETh4rmjAoF57y2aB1W8JZ8Dke4RaROJSztuWa5Q8OoVvBn
EjXoNcgqXf+iufWEDiBn6x0ODIseZo4X281qG21CvIzXcbhahD6yc6P2Yf3FW77hBtmTfcNrfizX29G36d1oUFnJXGeGrZYQB3ednRAblkttRxYovDuecOMw
Fj7GnflqEEiHlRSieenk9QLKYiKnv2HbdxRm8S3MwGC0Pvscb2AF6tuDvaxOzuGdroQPLXu/QZdMnQbccLEZf4iC5eFkuMWG3pLSHA7grGAmULhbmpvwGkT3
e9rmze7BvUcfcAJMMylqXZSth/Cn5FzbcYMyUt5j5k3meB13rqZKKsL9vW5ljkH44cr7YrTXlF9cngbtKIGDe/7a2aSWHT/LTctPJoudTJaopFXqkoDnsT9P
TUSKgPFiksZREA1SDDwI74mtQS9Rp7nIaS5EF9dgBto6ZRwK1RWx+dLCN6RV/uLycEVYPU3/u4y2Iw5Xq6+ZfxgJgV7iTi+x00t0VqO80jeuVPm1SoWX/6g0
RQ9Wih6q9sTw1LlXTQsoJu9AoKo0RbXkH/CMt+OxQjr0CbgoPi/TwHtBjGp2mvEcahUo08bEaNtYTejo7WuN+XS2PdBFOZsCGRW6UUYalz3TVH43jWA05AAA
Tn329oTXtGV21ERetoCW+hj9TSs4NHAWbY3uaOTajqeWusqsorocgwJqczkCPN/OF/HwGtlmm5l7bGVhxvFlEzh+vW42gxOt32Ut+6IFhDB6xT2kzJB3j7oq
gsdF7OIONuhgdhKICxBIlulCczNzZ3tL0w5A4FANSDUriaB8iNlfvGqoKClmVByY8Lr50ep00M1zRRWQ+pQ+U5H/AekogSEcDgAA
</details>

**Comment by Helfima** [comment]
add a another row choose in the solver to limit order impact
![image](https://github.com/Helfima/helmod/assets/20326713/3ccc1026-500e-4740-be9a-52e7eb02e487)
if the row is not in the same order that take the greater value in the green column
