### ISSUE TITLE
suggestion: allow simple math in some number fields

### ISSUE THREAD

**Issue by DeadlyKitten37** [Helfima/helmod#420]
The main one I want this for is the product output field

I am thinking nothing more the basic +-*/

example use case
the current product amount uses 2.687 machines, if I do 
(current output) /2.687 then 
(new output) * 3
I will have exactly 3 machines required

example 2
the current product amount required 20 items per sec in, if i do
(current output) / 1.333
then I will input exactly 1 belt.

**Comment by KiwiHawk** [comment]
You can already do this

If I want it to use 3 machines, rather than 8:
![image](https://user-images.githubusercontent.com/59639/181429011-83cf5512-aa81-475d-accf-9e7b5207060b.png)

**Comment by KiwiHawk** [comment]
You can already do this

If I want it to use 3 machines, rather than 8:
![image](https://user-images.githubusercontent.com/59639/181429011-83cf5512-aa81-475d-accf-9e7b5207060b.png)
