### ISSUE TITLE
suggestion: allow multiple outputs from sublevel

### ISSUE THREAD

**Issue by DeadlyKitten37** [Helfima/helmod#421]
this is a suggestion to allow multiple outputs from sublevel (level 2,3 ect)

I am imaging that in a sublevel one of the hotkeys (maybe alt leftclick) will result in that recipe trying to fulfill requests both in the subfloor and above it

example use case
a circuit sublevel that outputs all 3 circuit tiers

2nd example
inside the subfloor needs 20 light oil (for solid fuel) and 200 heavy oil (for lube)
outside the subfloor needs 200 light oil 
if Advanced Oil Processing can see outside the sub floor it will try to satisfy 220 light oil and 200 heavy oil.

**Comment by KiwiHawk** [comment]
You can already do this

Block 1 needs green and red circuits
![image](https://user-images.githubusercontent.com/59639/181429443-700826c9-b1a7-4d42-9051-89dcd5d6d370.png)

To make block 2 produce the green circuits for block 1 as well as for the red circuits:
1. Click on the filter icon (circled) to unhide the 0 output products
2. Ctrl + Click on the green circuits (circled)

![image](https://user-images.githubusercontent.com/59639/181429677-323778f2-3d3b-4ddb-9adf-38a0c56f81eb.png)
