### ISSUE TITLE
Matrix solver plastic bug

### ISSUE THREAD

**Issue by Niklisto** [Helfima/helmod#425]
Hi. I found strange behavior in matrix solver mode. If i put sulfur in front of plastic all ok:

![20220831121255_1](https://user-images.githubusercontent.com/6880842/187644810-c9cd27c2-8c06-4ae5-ba62-9e2490f59b7a.jpg)

But if i put plastic in front of sulfur i get this:

![20220831121259_1](https://user-images.githubusercontent.com/6880842/187644852-97ccd195-85a7-4015-99c6-32410b7dc4ad.jpg)

Or this:

![20220831121241_1](https://user-images.githubusercontent.com/6880842/187645869-f4825527-8beb-4391-b5ec-7087a6adaaf4.jpg)

I think it is a bug.

Vanilla game + helmod only.

Thank you for the mod )

**Comment by Helfima** [comment]
same issue Matrix solver with omni fuel #415
and solve in next release
