### ISSUE TITLE
steam output of modded heat exchanger and reactor

### ISSUE THREAD

**Issue by kingarthur91** [Helfima/helmod#427]
was looking at ratios for steam output from the vanilla heat exchanger with vanilla reactor. there seems to be something off about the numbers reported as they dont seem to quite match up with testing. also checked with yafc and it also reports different ratio so im unsure if ether calculator is correct.

these numbers are with the latest py alternative energy dev files from the git.
![helmod](https://user-images.githubusercontent.com/29772132/189576949-48e61891-7953-425c-843f-ca7208af6ede.png)
![steam from reactor](https://user-images.githubusercontent.com/29772132/189576966-1757abe6-8f17-4984-894b-e0daed2ce9f2.png)
[helmod vs yafc.zip](https://github.com/Helfima/helmod/files/9544720/helmod.vs.yafc.zip)

**Comment by KiwiHawk** [comment]
All looks to be working correctly to me.

In game testing: 1 reactor produces ~118k steam/min = ~1967 steam/sec

![image](https://user-images.githubusercontent.com/59639/189588109-09cd0857-4045-4487-90bf-8f315fbe191e.png)
![image](https://user-images.githubusercontent.com/59639/189588480-2ff6768e-b292-4b6d-9703-691b65ac1883.png)
![image](https://user-images.githubusercontent.com/59639/189588145-26678e2e-cbe8-4edd-80df-6935997e448f.png)
![image](https://user-images.githubusercontent.com/59639/189588401-9a0892f8-e389-4746-af5c-8935322080f1.png)
