### ISSUE TITLE
Full Power Balancing

### ISSUE THREAD

**Issue by EdwardMcCants** [Helfima/helmod#431]
I've been playing through a SeaBlock run where I upgrade my base after researching a new technology, and what I would like is a way to determine if a factory build will be strictly resource and power positive.

What I (now) think is part of my problem is that I've been using a 1 minute base time, which messes up the power generation calculation.  When I switched my base time to 1 sec it seems to actually balance correctly (I just have to convert my charcoal/sec to a Power value (W) and then verify that my inserters are consuming less power.

The specific bug seems to be that when I have a base time of 1 sec my 240 Wind Turbines produce 3.6 MW, however when I change to a base time of 1 minute, they produce 216 MW (i.e. 60 times what they produce).  This causes helmod to 'think' that I don't need any charcoal for my steam engine boilers.

**Comment by KiwiHawk** [comment]
Fixed by #426
