### ISSUE TITLE
[FR] Preserve list scroll position on item delete

### ISSUE THREAD

**Issue by JC3** [Helfima/helmod#434]
Hi;

Currently, when deleting a recipe from a production block, the scroll position of the list is reset to the top.

Would it be possible to preserve the scroll position when an item is deleted?

This would make it a lot easier to delete many recipes from a block with a long list of recipes, since you wouldn't have to re-scroll down from the top every time.

Thanks!!

**Comment by KiwiHawk** [comment]
Duplicate of #389
