### ISSUE TITLE
Space Science Production is wrong

### ISSUE THREAD

**Issue by KiwiHawk** [Helfima/helmod#438]
### Test 1
One silo, no modules
![image](https://user-images.githubusercontent.com/59639/202650420-697f0478-d043-42e4-a75f-4b433ee4da09.png)
![image](https://user-images.githubusercontent.com/59639/202650442-96c8fc12-3671-44a6-b514-ceb663ceed96.png)

### Test 2
One silo, 4 * Productivity module 3
20 * Beacon * 2 * Speed Module 3
![image](https://user-images.githubusercontent.com/59639/202650836-752c7589-401b-4292-af6d-70513e3efed9.png)
![image](https://user-images.githubusercontent.com/59639/202650849-eae9a031-ad3c-4256-825e-72b2285c3851.png)

**Comment by KiwiHawk** [comment]
In `Player.buildRocketRecipe`, `15` is being added for the launch time. It should actually be `2434 / 60`. Also, the launch time needs to be excluded from module / beacon effects.
https://wiki.factorio.com/Rocket_silo#Conclusions

**Comment by Helfima** [comment]
a made another test with different values is ok
