### ISSUE TITLE
Munda's Big Machine incorrect speed bug

### ISSUE THREAD

**Issue by LORD0DANZILA** [Helfima/helmod#444]
Hi, was playing with [Munda's Big Machine](https://mods.factorio.com/mod/Munda_Big_Machine), noticed when calculating machine speed caped on 30 speed(it has way more speed)
![изображение](https://user-images.githubusercontent.com/32709177/212464745-12b8cb50-1718-4ceb-8df9-02cba83f4209.png)
![изображение](https://user-images.githubusercontent.com/32709177/212465184-ea5da946-89e4-441d-8722-fbc5338c8c0d.png)

Playing SE+Krastorio 2

**Comment by LORD0DANZILA** [comment]
Addition, is there a hard cap at 30 crafting speed? Was looking around and noticed that Space manufactory from SE has same problem
![изображение](https://user-images.githubusercontent.com/32709177/212465559-7b4be67e-3bed-4ca1-a82e-ee451fa6103a.png)
![изображение](https://user-images.githubusercontent.com/32709177/212465575-a6389147-ccaa-4edc-af9e-0ba649a28c83.png)

**Comment by KiwiHawk** [comment]
Factorio has a recipe speed cap of 1 recipe completion per tick (60/s). So the speed limit depends on the recipe time. In this case, 30 as the recipe time 0.5s.

If you set up a test machine and look at the production graph, you'll see that the numbers match Helmod.

Note that this 1/tick limit doesn't apply to productivity. Productivity is calculated as if this limit doesn't exist. So for recipes that take Prod Modules, any speed increases beyond the 1/tick limit will give you items for free.
