### ISSUE TITLE
Incompatible with <~1.1.57 or so; "burns_fluid"

### ISSUE THREAD

**Issue by FauxFaux** [Helfima/helmod#448]
I tried to add the latest version of helmod to my py game, which is stuck on 1.1.53.

Suspect this was broken by #385. But, I also see that you were planning to pin it to >1.1.57, in:

> https://mods.factorio.com/mod/helmod/discussion/62e8fcfd9eb528644002d151
> Next version of helmod will require minimum base game version of 1.1.57

... which doesn't seem to have happened?

I'd recommend not supporting old versions if you have multiple problems, and just letting me install old versions of mods; I'm used to it by now. :)

```
Error while running event helmod::on_init()
LuaEntityPrototype doesn't contain key burns_fluid.
stack traceback:
	[C]: in function '__index'
	__helmod__/model/EntityPrototype.lua:324: in function 'getFluidFuelPrototype'
	__helmod__/model/EntityPrototype.lua:181: in function 'getEnergyProduction'
	__helmod__/model/RecipePrototype.lua:236: in function <__helmod__/model/RecipePrototype.lua:203>
	(...tail calls...)
	__helmod__/selector/RecipeSelector.lua:56: in function 'appendGroups'
	__helmod__/selector/RecipeSelector.lua:109: in function 'updateGroups'
	__helmod__/selector/AbstractSelector.lua:367: in function 'prepare'
	__helmod__/controller/Controller.lua:129: in function 'on_init'
	__helmod__/controller/EventController.lua:101: in function <__helmod__/controller/EventController.lua:99>
```

**Comment by KiwiHawk** [comment]
The latest versions of Helmod do require base game >= 1.1.57 . The latest version of Helmod is 0.12.14
If you haven't updated your base game, you won't see these newer Helmod versions in the in-game mod portal. I can't add the minimum version to anything that had already been uploaded to the portal unfortunately.

So in summary, there's nothing left that I can do.

**Comment by KiwiHawk** [comment]
I suggest you either update your base game version. Or download an older version of Helmod from the mod portal website. Sorry I can't do more to streamline it.
