### ISSUE TITLE
Dialog scaled incorrectly

### ISSUE THREAD

**Issue by KiwiHawk** [Helfima/helmod#456]
Edit recipe dialog, factory section is being compressed too small with some Py recipes.

Use a machine that takes fuel and a recipe with at least five ingredients.

> I found it specifcally for electric engine unit when the default assemling machine was set to burner assembling machine Mk2.
> That is an error in itself, because you cannot make electric engine units in burner assembly machines. But if burner assembly mk2 is default it wil set it anyway.

https://discord.com/channels/560199483065892894/1082163716952436746/1090691397776060466

![image-1.png](https://user-images.githubusercontent.com/59639/228676438-085c3f72-bd2a-490d-b32c-3e64e5334a55.png)

![image.png](https://user-images.githubusercontent.com/59639/228676449-046f83e7-c0ea-479b-9715-802f54e55995.png)

**Comment by espenst** [comment]
Good. I found the error, and we talked on discord. Just contact me if you need any assistance.

**Comment by espenst** [comment]
Also found it for Tin-chromium alloy in a Smelter Mk1. It seems that factories with no module slots might be a problem. This also has just three ingredients.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/42481865/228678196-4b94fb76-2332-4c8a-b3ea-45cdc864ecc2.png">

**Comment by KiwiHawk** [comment]
@espenst Which version of Helmod are you using? I haven't been able to recreate the UI scaling issue.

The only way I have found to get Burner assembling machine MK 02 selected for the Electric engine unit recipe is to a different recipe that does support Burner machines and press the apply to block or apply to line buttons (">", ">>"). I've fixed this.

Adding a recipe line (e.g. Electric engine unit) that doesn't support Burner machines is not selecting an invalid machine. Not even if a burner assembly machine is set as default.

![image](https://user-images.githubusercontent.com/59639/229266626-4b75fb97-ebfe-4f76-a9f7-83f92f343946.png)
![image](https://user-images.githubusercontent.com/59639/229266640-0d4806f5-b199-4f5c-a999-aada4484d483.png)
![image](https://user-images.githubusercontent.com/59639/229266648-0551bbb1-9879-414e-b30d-54f366d6ffea.png)

**Comment by espenst** [comment]
Sorry for the late reply. Vacations has started here, and I have been travelling today. I was using the latest helmod (0.12.15) on a 4K monitor running factorio in windowed full-screen mode if that can be related in any way.

I tested again today on my laptop (also 4K monitor, windowed factorio, full screen). Even though I set the recipe back to automated factory, it was today reverted to burner assembly. (This might be my default setting). When i opened the electric engine unit recipe, I could reproduce the error:
![image](https://user-images.githubusercontent.com/42481865/229311010-12d2f762-2e95-434a-bd6b-1079c20e9a01.png)

These are my factorio settings:
![image](https://user-images.githubusercontent.com/42481865/229311084-e158e03e-1dbf-4bb6-a381-a8bdf4d4c8ba.png)
![image](https://user-images.githubusercontent.com/42481865/229311094-df849c81-7550-43ba-9882-688e9f572e27.png)

Can the 200% UI scale cause this issue?

**Comment by KiwiHawk** [comment]
Yes! I was able to reproduce the issue by setting my UI scale to 150%. Thanks for the help!

![image](https://user-images.githubusercontent.com/59639/229323911-0425ce6a-e5b5-4f4d-a5a9-1fa5c721bf66.png)

Setting it to 200% actually works fine for me as it then splits over two tabs. This was a surprise to me!

![image](https://user-images.githubusercontent.com/59639/229323943-23b8d573-e3d0-40a7-ae0c-3f3b371bace5.png)
![image](https://user-images.githubusercontent.com/59639/229323948-318cf73e-5268-4ade-93d8-bdd1ca3d4775.png)

**Comment by espenst** [comment]
Happy to help. Thanks for working on this excellent mod. Great work!

Call out if I can be of any more assist

**Comment by Helfima** [comment]
I added a menu to switch, the default is automatic

![image](https://github.com/Helfima/helmod/assets/20326713/1329814c-cb34-438c-962c-8448e833f21f)
