### ISSUE TITLE
Pinned line doesn't obey assembler limitation toggle

### ISSUE THREAD

**Issue by lieronet** [Helfima/helmod#460]
If you turn on the assembler limit, put a limit in place, then turn the limit off by clicking the button again, the line will no longer behave as if it were assembler-limited. The pinned line summary, however, still displays information as if the assembler limitation is in place. The line summary will only display a non-limited line if no production steps have an assembler limit placed on them.

**Comment by Helfima** [comment]
fixed in the next release
