### ISSUE TITLE
Linked matrix solved line with extra outputs doesn't automatically update

### ISSUE THREAD

**Issue by lieronet** [Helfima/helmod#464]
If you shift-click to designate extra outputs in a line, link that line to other lines downstream, and have your extra-output line on matrix solver mode, it won't update itself properly as you make changes in the block. It will revert to solving for only its nominal output until you go back into the block and flip it off and back onto matrix solver. Included is my block that demonstrates the behavior, vanilla Factorio.

[helmod bug line.txt](https://github.com/Helfima/helmod/files/11772811/helmod.bug.line.txt)

**Comment by Helfima** [comment]
can you put image to explain your problem? (you can paste image)

**Comment by lieronet** [comment]
Sure. 

Oil line, matrix solved with extra outputs:
![image](https://github.com/Helfima/helmod/assets/28401732/425a8bd7-7649-4b3c-86f8-5a641c07ac41)

Go do something else in another line:
![image](https://github.com/Helfima/helmod/assets/28401732/8139f233-b5e1-4aba-847a-f8d5bbef856f)

Oil block recalculates, incorrectly:
![image](https://github.com/Helfima/helmod/assets/28401732/f6442b8e-6680-43bd-94c6-02ae24f80813)

Flicking back and forth fixes, but it's annoying:
![image](https://github.com/Helfima/helmod/assets/28401732/3b05fd1e-9d91-4f81-97ea-3b9cf40b0e53)
![image](https://github.com/Helfima/helmod/assets/28401732/ea7b5e89-4671-4abb-ab94-d018ca20d7d2)

**Comment by Helfima** [comment]
ok I see the bug, use the refresh button
![image](https://github.com/Helfima/helmod/assets/20326713/1064f4b7-6628-42cb-9682-fa63fff9c3a6)

**Comment by Helfima** [comment]
fixed in next release
