### ISSUE TITLE
"Convert this recipe to a block" button giving an error message

### ISSUE THREAD

**Issue by k4gi** [Helfima/helmod#469]
the error message is `__helmod__/data/ModelCompute.lua:244: attempt to index field 'products' (a nil value)`

closing and reopening the planner, the new block is there but there's something wrong with the UI

![Screenshot 2023-07-20 181035](https://github.com/Helfima/helmod/assets/26471575/11d99df3-6905-4df1-9c38-1b2c3570f9b8)
![Screenshot 2023-07-20 181209](https://github.com/Helfima/helmod/assets/26471575/0bfbc736-ffcf-45a0-a5f7-fa599957f80c)

I haven't used this mod before so maybe I did something wrong.

**Steps to reproduce**
- start a new game with helmod enabled
- open the planner
- click the "add a recipe" button
- click "iron plate (recipe)" and confirm
- click "+add this recipe - iron ore" in the production block
- click "convert this recipe to a block" on the iron ore entry
- aforementioned error appears
- click the button again, another error appears, `__helmod__/data/Model.loa:191: attempt to index local 'recipe' (a nil value)`

using Helmod 0.12.17 and Factorio 1.1.87

**Comment by KiwiHawk** [comment]
Please update to Helmod 0.12.18
This issue should already be fixed
