### ISSUE TITLE
Deeper Layers (blocks within blocks) Feature

### ISSUE THREAD

**Issue by Krydax** [Helfima/helmod#474]
Writing this here because KiwiHawk asked me to!

So this is a big one. I know FP can do this, YAFC can do this. Hell, Microsoft Word can do this. Jokes aside, we need to indent more!

I'll start with a primary case where you run into this, and you can imagine many more. Pyanodons science. I haven't played Factorio in months since I got burnt out a bit, so apologies if I remember something wrong, but my overall point stands regardless :)

I'll use my circuits in py as an example. Below you can see the full production line, with 3 blocks in it.
![image](https://github.com/Helfima/helmod/assets/93162034/7ec59417-411c-45d6-a63a-b1bd92cc2363)

Going into the "circuits" block, you can see the issue. There are SO many components. I would WANT to separate some of these into a sub-block!.
![image](https://github.com/Helfima/helmod/assets/93162034/7c6a8e35-b004-4b3e-89f8-32f1dc533145)

For example, I would want to make the Printed Circuit Substrate section its own block. 
![image](https://github.com/Helfima/helmod/assets/93162034/eafc8c94-2bbf-4eaf-b269-41468be46a13)

A sub block would perform to a block the same way a block performs to a line. Linking sub blocks to other sub blocks would work exactly like linking blocks works within a line. All of the exact same logic, just one layer deeper. This would allow for much larger builds to be "feasible" in helmod. Currently the lack of sub-blocks (or even sub-sub-blocks) is preventing us from *really* planning out entire builds in helmod. Rather, we are forced to make many separate lines that technically are all part of the same overall "thing". But you can't combine lines in helmod. So the solution is that we need to be able to go deeper within a line!

Here's an idea for a "plus button" that could expand all sub-blocks within a block. Maybe too much feature creep. Even just showing sub blocks directly below the block (and not being able to expand/collapse) would be fine!
![image](https://github.com/Helfima/helmod/assets/93162034/79d36a17-13bf-4ad4-b594-db7cfee45e65)

EDIT: Currently it looks like a line can ONLY have blocks, and blocks can only have recipes. To stick with that theme, we could make it so that if a block is to have sub-blocks, it cannot have any normal recipes (basically making it a sub-line). 

For example you could have:

Production line 1
->Block 1
-->Recipe 1
-->Recipe 2
-->Recipe 3
->Block 2/Sub-Line 2 (we designate this block to be a sub-line, rather than a block. This means it can only contain sub-blocks, and those sub-blocks will contain the recipes themselves.)
-->Sub-Block 1
--->Recipe 4
--->Recipe 5
-->Sub-Block 2
--->Recipe 6
--->Recipe 7.

This way you're never mixing regular recipes and also the bigger "blocks" which contain recipes.

EDIT2: I do think in the IDEAL world, you can mix recipes and sub-blocks. So you could have like a 4 ingredient thing, 3 of the ingredients you plug in normally (maybe your factory already has them), and the fourth requires a whole build for it, so you make that one a sub block, right alongside the 3 regular recipes. This would be the best functionality, but could be much more difficult to program/make it work right, not sure.

**Comment by Helfima** [comment]
I work on this options
![image](https://github.com/Helfima/helmod/assets/20326713/dcd1c30d-4820-419f-8461-7cb5d003ae5b)
I've wanted to do it for a long time, it requires reworking a lot of code so you'll have to be patient

**Comment by Helfima** [comment]
implemented in v1.0.x
