### ISSUE TITLE
GUI Sizing breaks when Logistical Artillery by Digra is installed

### ISSUE THREAD

**Issue by rwaltr** [Helfima/helmod#477]
# Summary
![image](https://github.com/Helfima/helmod/assets/11428125/3a13a0f6-bae0-409c-92af-94d8302de769)
When using Helmod, The UI will break if https://mods.factorio.com/mod/logistic-artillery-digra is installed as well.

# How to replicate
- Install Helmod, and Logistical Artillery
- Start a fresh game
- Open the Helmod screen.

**Comment by rwaltr** [comment]
Digra uploaded a new version with a changelog for a fix, I'll test it then close this issue if resolved

**Comment by DiGra** [comment]
Hi everyone here. Just fixed this issue in 1.0.7 update. Unfortunately I uses "inside_deep_frame" and that's break GUI on Helmode side. I renamed it on my side to prevent similar issues in future

**Comment by rwaltr** [comment]
Tested and confirm fixed with my original test setup, Closing issue as resolved

**Comment by KiwiHawk** [comment]
> Hi everyone here. Just fixed this issue in 1.0.7 update. Unfortunately I uses "inside_deep_frame" and that's break GUI on Helmode side. I renamed it on my side to prevent similar issues in future 

Thanks for the quick fix!
