### ISSUE TITLE
Use object_name instead of parsing help() string in logging

### ISSUE THREAD

**Issue by Bilka2** [Helfima/helmod#485]
There is `object_name` now, which should be easier than this: https://github.com/Helfima/helmod/blob/52140e4d5728827334f4f0a7fa397dd47e8075b7/core/logging.lua#L120

**Comment by KiwiHawk** [comment]
Thanks! That's much cleaner. Do you know what version this was added?

**Comment by Bilka2** [comment]
It looks like it was added in 0.18.0.
