### ISSUE TITLE
Difference between recipes in helmod windown and game recipes

### ISSUE THREAD

**Issue by Matpewka** [Helfima/helmod#486]
Hi, i am using [paranoidal modpack](https://gitlab.com/paranoidal) and found diff between helmod recipes and game recipes.

At screenshoot game told me what ia can _sort crashed saphirite_ for 2 seconds if i give 20 crashed saphirite per 2 second  for each factory => for 2 factory 20 crashed saphirite per second, by in helmod window for 2 factories using only 15 
![image](https://github.com/Helfima/helmod/assets/2772816/ff6e410b-de4f-4ba4-ab0d-f1beb5a99aa6)

How can i fix it locally fast?

**Comment by KiwiHawk** [comment]
Helmod's numbers are correct. The Ore Sorting Facility has a speed of 0.75

**Comment by Matpewka** [comment]
Oh, sorry, of you right. 
my fail.

Issue can be closed.
