### ISSUE TITLE
Zero values when using linked recipe

### ISSUE THREAD

**Issue by Matpewka** [Helfima/helmod#488]
![image](https://github.com/Helfima/helmod/assets/2772816/dd128a8f-e4d0-402f-85ef-26f6da4f776f)
Here all is ok.

When making linked recipe 
![image](https://github.com/Helfima/helmod/assets/2772816/e10055fa-bc63-4c62-8e30-4028b2463405)
and when i selected "coke" recipe tier 1 got zero values:
![image](https://github.com/Helfima/helmod/assets/2772816/530c9f63-0a89-4d10-a244-d79d14b1da29)
that reproduce also if add "coke" recipe tier 2:
![image](https://github.com/Helfima/helmod/assets/2772816/af98e84f-57f5-462e-ab74-e25411790375)
but when i remove "coke" tier 1 from recipe all is ok again:
![image](https://github.com/Helfima/helmod/assets/2772816/2022c1d5-93e2-4a18-8547-01b9b8b602cd)

**Comment by Matpewka** [comment]
Upd.
Same behavior if change fuel from coal  ( all is ok ):
![image](https://github.com/Helfima/helmod/assets/2772816/549a3fb2-5ba6-4f08-b5ed-f77b764fcd76)

to carbon ( all again zero ):
![image](https://github.com/Helfima/helmod/assets/2772816/d55d4263-37d9-438b-8529-645d0517c958)

**Comment by KiwiHawk** [comment]
This looks like it's working as designed.

If an item/fluid is both produced and consumed in the same block, then by default it won't link outside the block. To override this, Ctrl+Click on the product in the Outputs section at the top of the block.

**Comment by Matpewka** [comment]
Thx, it`s help me!

Should better read the docs
