### ISSUE TITLE
Improve name / explanation beacon "combo" and "factory"

### ISSUE THREAD

**Issue by vanatteveldt** [Helfima/helmod#49]
The names "combo" and "factory" in the beacon panel are not very intuitive and I've noticed some people asking about it on reddit and the forums. Maybe just call them "beacons per assembler" and "total ratio assemblers:beacons" or something like that, or provide a tooltip or label for explanation?

**Comment by Helfima** [comment]
i mean add a help panel :)

**Comment by Helfima** [comment]
i have change label and add a tooltip in version 0.4.6
