### ISSUE TITLE
Crash when trying to add Angel processing recipe

### ISSUE THREAD

**Issue by Liquid5n0w** [Helfima/helmod#5]
When trying to add the recipe for Hydro refining. I suspect that the cause is that recipe has fractionnal outputs.

![image](https://cloud.githubusercontent.com/assets/9867874/18357071/81f6cdd0-75bd-11e6-893f-761a165b022e.png)

![image](https://cloud.githubusercontent.com/assets/9867874/18357081/891efa88-75bd-11e6-827c-0cc1b6c495ce.png)

**Comment by Helfima** [comment]
what version u play? v0.13 or 0.14 of factorio.

**Comment by Liquid5n0w** [comment]
I am currently on 0.13.20

**Comment by Helfima** [comment]
Have u modified the version of my MOD in zip to use in 0.13.20? or factorio use my version for 0.14.x?

**Comment by Liquid5n0w** [comment]
I forgot, yes I had unzipped it and changed the info.json so it would work with 0.13.20

**Comment by Helfima** [comment]
I have find the problem
http://lua-api.factorio.com/latest/Concepts.html#Product
some product have probability and have not amount
it will fix in next pre-release

**Comment by Helfima** [comment]
commited
