### ISSUE TITLE
Factory Number Format

### ISSUE THREAD

**Issue by KiwiHawk** [Helfima/helmod#508]
Helmod v1.0.4

Number of machines required is always being shown with decimal places, ignoring the setting Factory Number Format.

https://github.com/Helfima/helmod/blob/a6cbda80421748f1dd66f94ff1379a08f5548ddc/gui/GuiCell.lua#L454

![image](https://github.com/Helfima/helmod/assets/59639/7d2de9c6-f4eb-4656-861b-f82f68c5e30b)

![image](https://github.com/Helfima/helmod/assets/59639/e7c5b587-339c-47c0-a888-dc1629646c5d)

**Comment by Helfima** [comment]
fixed Version: 1.0.5
