### ISSUE TITLE
Replacement of the performance rate from the calculated one per unit/second

### ISSUE THREAD

**Issue by Alekseikovtun** [Helfima/helmod#509]
![General production line](https://github.com/Helfima/helmod/assets/112760679/eb71d100-2e85-47d8-8d8b-5d0f76c495ee)
![Creating a branch](https://github.com/Helfima/helmod/assets/112760679/6114b1d9-5529-498b-8be8-adfb59d0c5fa)
When adding a branch from the main branch of production, the capacity is recalculated to produce 1 unit of product / second, and not to produce the required amount, which is why i have to change everything manually. Thank you in advance for correcting or indicating where this can be changed.

**Comment by Helfima** [comment]
this is how it currently works
duplicate #510
