### ISSUE TITLE
Error on adding mod to existing save

### ISSUE THREAD

**Issue by jforr** [Helfima/helmod#51]
Downloaded the mod and loaded an existing save game and got the error below.  Starting a fresh game does not result in an error.

The is on version 0.4.4 of helmod and version 0.15.9 of Factorio.

Error while running event helmod::on_tick (ID 0)
__helmod__/helmod.lua:135: attempt to index field 'users' (a nil value)

**Comment by Helfima** [comment]
could you try the attached file
[helmod_0.4.4.zip](https://github.com/Helfima/helmod/files/985619/helmod_0.4.4.zip)

in game use the command
`/c remote.call("helmod","export_data")`
after send me Factorio\script-output\helmod\data.json
