### ISSUE TITLE
Remove/option to disable block quantities

### ISSUE THREAD

**Issue by Demiu** [Helfima/helmod#510]
Look at this

![image](https://github.com/Helfima/helmod/assets/7906172/56d030ad-c586-48d3-a65b-0001790f8600)

What's a 0.04 of a 75 machine factory? What's a 0.15 of a 4 machine factory?

When the user inputs 1 wood per second they want the calculations and the ratios for **exactly** one wood a second. Calculating perfect ratios and is simple, people use planers to calculate the imperfect ratios for them. If I wanted a block to produce 7 wood / s, I'd put 7 as the top-level output.

**Comment by Helfima** [comment]
see #509

![image](https://github.com/Helfima/helmod/assets/20326713/8900ff2c-bb51-47e3-b9c6-e060083128c3)
Recursive blocks see a block as a recipe, the solver cannot know in advance the quantity, a quantity of block is based on a base value.
Block B,C,D are calculated first
Block A see B,C,D as few recipe

That need post process to set block at 1
