### ISSUE TITLE
Production line broken ?

### ISSUE THREAD

**Issue by Paraplegix** [Helfima/helmod#511]
Using helmod 1.0.4 coming from helmod 0.12.19

The production line have a weird behavior when having many sub block that share product/input between or in them.

I'm playing with Pyanodon, so I need quite a lot of blocks with many product and byproduct. I originally used production line as "group" of blocks, like all the plants in a line, all the animals in a line etc... And within this line there was many unlinked production block for most item I had unlocked.  The block can either be as "By factory" or "Matrix solver". This is quite mandatory for me because I can quickly glance at how much of certain items I can make, and grossly estimate if I have enough or not, but I cannot do the same with current version.

For example, in my production line for plants, I have wood and moss. Moss is quite straight forward but wood require many things including moss at some point.

Here how to reproduce on a new game of helmod with full pyanodon suite.
1. Starting with this moss recipe in "by factory" mode
![image](https://github.com/Helfima/helmod/assets/12891208/d40518b4-126d-49bb-9e35-86904750158e)
And with this wood recipe matrix solver mode (further down the line, wood is required for two other things)
![image](https://github.com/Helfima/helmod/assets/12891208/c18a3f96-45a9-4dbc-b507-d7dbd8716f3d)
This gives me the following production line view 
![image](https://github.com/Helfima/helmod/assets/12891208/076ef219-27ad-4361-bb1e-9dd41c96fb1d)
Which has 1800 wood and 240 moss, the same as inside the production blocks. (1 min base time)

2. However if I add the recipe for tree seedlings in the wood block like so, requiring 257.2 moss:  
![image](https://github.com/Helfima/helmod/assets/12891208/e475651c-f148-4dfe-bb99-9fe05ccde8b2)
It adds moss to the recipe, and now in the production line view the moss act like it's linked and should make 257.2 moss while it's not marked as linked (and shouldn' be able because it's in by factory)
![image](https://github.com/Helfima/helmod/assets/12891208/b9172006-d9a7-4899-bdb2-18429d5c59fd)
Changing the production line "computing" mode to matrix solver keep the same values in the view, and by factory turn it to 0. (should you be able to do by factory in a Line/block that has sub blocks ?)
The moss block itself doesn't change the values and inside it's still in By factory producing 240 moss.

3. Now on the wood production I add the seed recipe which consume woods 
![image](https://github.com/Helfima/helmod/assets/12891208/68dad8cd-0400-4bad-b6e7-8b712d8874f3)
As you can see the matrix solving computes correctly, the block now requires 267.1 moss, produce 1870 wood to ouptut 1800, great !
However the production line view now show 0 on every recipes....
![image](https://github.com/Helfima/helmod/assets/12891208/b18be426-0147-43ef-9d1a-e82a5fb46bab)

I can manually request 1800 wood on the line, but the moss will still show as producing only what's needed for moss...

**Comment by Paraplegix** [comment]
Just tested with helmod v1.0.7. First step is now broken too ?

With both line set up the same, in the "main block"/"line" view as configured in step 1, the moss is now shown a 0
![image](https://github.com/Helfima/helmod/assets/12891208/aceb63b2-15f4-4707-9093-3e6a248b05b9)
I expect the total input/output inside block to be visible in the recap line of the main block (like it was before)

Step 2 and 3 are the same as before (still not what is expected?)

**Comment by Helfima** [comment]
can you try V1.0.10

**Comment by Paraplegix** [comment]
Quick update right now, 

The production link / unlink seem to be fixed. But there are some step that need to be manually done to avoid some quack appearing

Starting with same setup as last step of last screenshot. (IE step 2 of first report)
Moss block is configured inside as 240
![image](https://github.com/Helfima/helmod/assets/12891208/7f1cafd5-414e-449c-b85f-8de4d943226c)
The unlinked block is now shown as 240 so good ✅
![image](https://github.com/Helfima/helmod/assets/12891208/94e94c81-0329-45b4-8e79-74e9f9451469)

But if I toggle linked block on moss, I still see the "1.1" factory?. 
![image](https://github.com/Helfima/helmod/assets/12891208/38a48581-ef60-4594-a4cf-3462f1b69846)

In the moss block the block is still configured as 240. 
![image](https://github.com/Helfima/helmod/assets/12891208/908d4559-3137-46e9-90a6-aa9391df5371)

It seems there is new behaviors : Linked or unlinked, a block can still define its own output targets ? From memory, when a block was linked, the output where completely controlled by the other lines. Ie in there if moss was linked, it's output would be force set to 257.
![image](https://github.com/Helfima/helmod/assets/12891208/e465eb98-0b78-4694-8f48-445474a8765f)
On this screenshot, this shouldn't this not be 240 "*" with green background and forced to 257 and blue background?
This indeed give some flexibility and is nice to have the option, I don't know what would be preferable, but could be confusing if not understood correctly? (and maybe i didn't understand either)


Other little problem that is probably easy to fix: If you have a block in compute by elements that is already linked, and you switch the block to compute by factory, the "link/unlink" button is disabled, but the block stay linked 
![image](https://github.com/Helfima/helmod/assets/12891208/0b163ec8-530e-49b1-9713-1551c95b3dae)




There are still is weird behavior with "looping" recipes (might be related to the amount defined etc):
This block on matrix solver or compute by element "should" output 1800 wood (but it's in red background?)
![image](https://github.com/Helfima/helmod/assets/12891208/b9c5e172-0b5c-4c3b-985f-852d860ddd4b)
And in the block above it's shown as 0 
![image](https://github.com/Helfima/helmod/assets/12891208/e77dcf0b-67eb-448a-9d77-64a052b450e2)
But if I manually ask for the volume in the above block (see 1800 "*" wood), the number becomes correct. (this wasn't possible when i tested with version 1.0.4/1.0.7 i think)
![image](https://github.com/Helfima/helmod/assets/12891208/68d0a21f-ba2d-43d1-bea0-3fb6d1e3efb8)

You do need to have 1800 setup in both block. If I remove the 1800 from the sub block and keeping it in the top block, it goes back to nothing 
![image](https://github.com/Helfima/helmod/assets/12891208/ae069d9d-1f5a-427f-93f3-bb8496155101)
But with the same setting if i remove the last product (tree seed) that make the recipe "looping", the number becomes correct without having the 1800 defined inside de sub block
![image](https://github.com/Helfima/helmod/assets/12891208/d57a4321-b93d-453c-99bb-b01603e6b7b8)

I've tried replicating the problem by adding a top recipe on the top block that required 1800 wood input, but it was not showing the correct number either.

**Comment by Paraplegix** [comment]
Et question à part, tu préfères des bugs report en français ou anglais ?

**Comment by Helfima** [comment]
non ca ira, c'est plus du temps qu'il me faudrait :)
globalement je corrige au fur et à mesure.
la solution du problème hiérarchique est un vrai casse tête, entre les valeurs définies ou pas ect...
ce qui faut bien comprendre c'est que dès qu'on met une valeur en input dans le block lié ou pas ca défini la valeur de base, en gros tu défini ta macro recette (le block) le block étant considéré comme une recette dans son block parent.
alors parfois faut bidouiller pour ajuster les valeurs. moi je multiplie/divise souvent mes inputs pour ajuster mes calculs.

**Comment by Paraplegix** [comment]
Old message, most problem described are probably fixed by now
