### ISSUE TITLE
Incorrect calculation of the number of required factories

### ISSUE THREAD

**Issue by Dilise** [Helfima/helmod#517]
Добрый день.
На мой взгляд, количество фабрик считается некорректно.
Если просуммировать столбец, то для строительства производственной цепочки понадобится 11 фабрик ни больше, ни меньше, в то же время в сводной информации обозначено 9,81 и 10, что является неверным значением.
Версия мода: 1.0.7
![image](https://github.com/Helfima/helmod/assets/16350731/45fc2d42-f0c2-43d3-8c4c-54b4bd2a6237)

Good afternoon.
In my opinion, the number of factories is calculated incorrectly.
If you sum up the column, then to build the production chain you will need 11 factories, no more, no less, at the same time, the summary information indicates 9,81 and 10, which is an incorrect value.

**Comment by Dilise** [comment]
Еще один пример с установленным ограничением сборщиков.
Должно быть 7, а вместо этого 5 и те же 9,81!!!
![image](https://github.com/Helfima/helmod/assets/16350731/23d2818a-cb5a-427e-8381-a3ff0de59432)

**Comment by Helfima** [comment]
fixed in next v1.0.11
