### ISSUE TITLE
factory display issue

### ISSUE THREAD

**Issue by jernun** [Helfima/helmod#521]
in the first image i specifically ask the factory planner to make glass with 12 foundry, but the the display tell me i need 13 of them (in red).
i also ask to use 2 productivity module for each foundry, which the display should give me 24 module needed (12f x 2m = 24) however the display show me i need 25 of them (in blue).
this is most likely a rounding error because i see no other reason the game would add 1 foundry and only 1 module 

![capture_240403_151605](https://github.com/Helfima/helmod/assets/165912064/b6c20d67-26d2-4f23-8b26-40a8ced106c4)

in the second image the factory planner tell me i need 7 assembler for purple science and 3 assembler for lamps, which mean i need 10 assembler, however the display gives me 9 assembler needed.
this issue is most likely there because, instead of adding 7+3 the game adds the "true" number of assembler, because i don't acctualy need 7 and 3 assembler but more likely 6,5 and 2,5 assembler which equals 9

 ![capture_240403_151735](https://github.com/Helfima/helmod/assets/165912064/d6b7a80a-8daf-4cf2-ba0e-5d6cfc46301a)

**Comment by Helfima** [comment]
fixed in next v1.0.11
