### ISSUE TITLE
Link/unlinked block are ignored.

### ISSUE THREAD

**Issue by Paraplegix** [Helfima/helmod#522]
Following #511 with version 1.0.8. But now i'm not sure if 511 is relevant anymore.

So starting with similar setup as 511 step 1. 
* One main block (in compute by element by default), one minute base time
  * First sub block with wood , compute by element, configured inside the block for 1900 wood
  * second sub block with moss, compute by factory, 50 factory producing 240 wood per minute
  
Moss sublock isn't linked as it's by factory.

But if I add a step in the wood sub block that require 257.2 moss, value for the moss sub block get changed too, even if it's unlinked and computed "by factory".

In the "main block" view, the value of moss is changed to 257.2. Also now different than before, the number of factory get bumped to 54 and the "block count" stay at 1. While before, building count stayed at 50, but "block count"/"recipe" went to 1.08.
![image](https://github.com/Helfima/helmod/assets/12891208/a333fb4d-a392-4def-975c-722941308644)

In the moss sub block view, the value of moss is changed to 257.2. The total number of factory is 54, but the line still is configured with 50 factory.
![image](https://github.com/Helfima/helmod/assets/12891208/c68059db-e250-4721-8c6d-c0bbf7555ccf)

If change the moss block to be "By element" and manually set it to 240 moss (for 50 buildings).
In the main block view it will show 1.1 "blocks count"/"recipe", 50 factory and 257.2 moss wether the block is linked or unlinked.
![image](https://github.com/Helfima/helmod/assets/12891208/e579f200-4fbe-42ec-a895-1de9a14301ae)
![image](https://github.com/Helfima/helmod/assets/12891208/dcb89df1-7e7c-4b3b-b9ee-678b2fc7576f)

Inside the block it will show the value 240 output, 50 factory even when the block is supposed to be "linked"
![image](https://github.com/Helfima/helmod/assets/12891208/1c488d43-6fac-4b5c-a9b8-b7997a44b1be)

Also noticed some inconsistency in usage of word "Factory" and "Building" to describe same thing ? Hovering above a cell fo the "Factory" columns show a tooltip with "Building information". Notably the "count" of different building in the block, yet the "buildings" number inside the block are shown in the column "Factory".
![image](https://github.com/Helfima/helmod/assets/12891208/a8ad9521-b80a-44f0-8dbe-10feee3cf004)

**Comment by Helfima** [comment]
fixed in v1.0.10
