### ISSUE TITLE
Indicate factory utilization percentage

### ISSUE THREAD

**Issue by vanatteveldt** [Helfima/helmod#53]
[Hey Helfima, thanks for your great mod! I'm just putting down some ideas that might make it even better, feel free (obviously) to ignore me :)]

Helmod rounds up the # of factories required (which makes sense). It would be nice to see to what % the factories are used, i.e. if I have 4 red circuits it requires 1 green, but that is only used 67% of capacity.

There is a percentage next to each recipe, but that seems to always be 100%, so maybe this was a planned feature?

![image](https://cloud.githubusercontent.com/assets/1736240/25888877/61d7f004-359a-11e7-93cb-75d4bdc61746.png)

E.g. in this screenshot, it would be great if the percentage next to the green circuit plant said 67%.

**Comment by Helfima** [comment]
Sometimes you need to adjust production of recipe
@see https://forums.factorio.com/viewtopic.php?f=92&t=30465&start=20#p230475

**Comment by vanatteveldt** [comment]
A right. I would still like to see the utilization percentage, now I often just multiply my desired output by 10 or 100 to get an idea... If I need e.g. 4.1 factories I could decided that 4 is enough.

**Comment by Helfima** [comment]
In the next version we will have the choice of displaying the decimal
