### ISSUE TITLE
Linked/unlinked block display issue with first block 

### ISSUE THREAD

**Issue by Paraplegix** [Helfima/helmod#530]
When showing the tab of the first sub block, the link unlink button on the top will always shown "unlinked" and be disabled :

This is ok because it's the "line" and not a block. The first block of the line is marked as linked.
![image](https://github.com/Helfima/helmod/assets/12891208/c26e5a94-6eda-4941-ba57-53da45dfa3c5)

But showing the panel of the sub block will have the button in the top disabled and shown as unlinked
![image](https://github.com/Helfima/helmod/assets/12891208/e311a4ab-66de-492a-8f85-85c039349c37)

**Comment by Helfima** [comment]
fixed in next v1.0.11
