### ISSUE TITLE
Block in ingredient input mode doesn't show it's input/output in the parent block

### ISSUE THREAD

**Issue by Paraplegix** [Helfima/helmod#531]
Tested in helmod 1.0.10 with no other mods (but same with full pyanodon suit)

A block configured in ingredient input (configure how much goes in to see how much gets out) like following :
![image](https://github.com/Helfima/helmod/assets/12891208/d219d814-af58-4270-9c1c-64d015a49077)

Will show 0 ingredients/products in parent block (block being linked or not, parent block in ingredient or product input doesn't change)
![image](https://github.com/Helfima/helmod/assets/12891208/f71eede3-859b-4d8c-9a87-3101ba0f1175)

I expect to see the value in the block to be seen in the line of the parent block (100 ore, 14.4 coal and 20 steel plate)

production line code:
`eNrlV02PmzAQ/Ssrzl5kSJrdVcSlh94qVblWFXJgsksXMDIm3Sjiv3eMbTCETdNouz0sF/DXeGbee2ac8pucJyy/iaNjkrO6jryvPIXcI1kaeYX6jEOP8F8liMj7xgSrcnjMXjyyxXXPMc5amk/BueyNfFZd2ogeDbBRpvASUVKyAiIvE7y8rXImYdZ8wptSRgGp+C8corj4UUCaQSnr6PjdXf0jOp5alIdK9UgoPMKKzhYltcSxiLZonOV2lfo+Oz9sidmPi+luquf82pZUgqdNot2uJUA+9dvtPGcs6B25NnCM/CnLUwFldNSwhK8jFk4Rm/FTQJJV5wCk/wDA8EIAg6W/eBg9J4m8HNGAqhCqRn9ZO2+AbnjKs2vT4sK7WfXIbgxICtrN6i9QTayDJsiMl6jIHUskF4fe/Bfd9np7vITbXSNKlvQWEfVMHoZkrgggYR4P0QOlKp0VQIqm86zIVEB47jQ5YE5bArsddOnVcwZf9mgQmwkv66aoOt8U2fK80d+YDFZds6xbEUsukWKBO+TTxeQxUZjJjh3b43+artA5XYRUf8U65KGdAlTKiy0w5WN07PXZddgsb01rNr3UZnd536U34cWW4zldgYgteuia247VZpIp12ZRGMdpte2GMAkAI2A1xDJDbwOiXysnQdbV0wzN7WX2mGSpP1u6d++HbvVTLH4B9Vfjx3FHrz07xRrM9uo/5wrxRKYY/eZuXn93Vn8BeU3dY/mp4+at9bfwQzp6wo+ix4CO8b37yIKcocGMQE9TNs3yWUWoH2o7ciygbyrj+z/L+P5ExurPPTCJNGWelc9IzB3LayAVw3+ojEfVq0ncE6tjXQdI0QDh25+gWAxDUWNqimc4uCXFnuUNqNCHmkHLeQzZJSlwhidnE0qoYOpo2DZYB2DFFa2WlNiGWTfqMgs16TIwZYx7gjiFzJmDRRNQmXbjGdpjFVmT86K5jMxWjq0ji3bMK3ipGJ61aXQcCtMONlx+iA0KGvIJHxwC9Heg8eF8QgfNnDEfJgVhR4lRvaVZEdJ2opD/wwPV8z5MwOa7ciFwATcMUMKuh3sQOjS6orREQM0bkegD1+C9B1Fr3doqGqmC/kvsj47X/xzVbopYinIP5qKBMazN5Rxv5+069rXPvnXZdHQ3b9+W/nZ0LUAiQjfxGsr0NwNzoaU=`

**Comment by Paraplegix** [comment]
No idea if it can help but changing the code in file [SolverLinkedMatrix.lua line 264](https://github.com/Helfima/helmod/blob/46685e5b3de4ec2d6e1835355692027da5513ce4/math/SolverLinkedMatrix.lua#L264) to `child.count = 1` seem to fix this issue

**Comment by Helfima** [comment]
It's more complex but I change that
https://github.com/Helfima/helmod/commit/eb8d74bfe92655f52ff2ab9a7dd9c7265082e0a2#diff-86fcd155f347675bf8887246c204acd241782450dc725ad2407b280a6007cacd
I need add option consumer on the block before plublish

**Comment by Paraplegix** [comment]
Seems to be fixed, and the output summary is ok too
