### ISSUE TITLE
interface gives wrong machine number for yellow factories

### ISSUE THREAD

**Issue by crasher925** [Helfima/helmod#532]
I discovered this issue while testing some stuff in a test world. when setting the factory to yellow assemblers (assembler 3s) the interface gives an erroneous answer when set to fill a blue belt.

![image](https://github.com/Helfima/helmod/assets/25976752/3943a4ea-5a3a-4a9d-8f95-ea9808d4935e)

The top factory uses 18 assembler 3s the bottom uses 46 assembler 1s and DOES saturate the blue belt

![image](https://github.com/Helfima/helmod/assets/25976752/8639def6-d7f6-4dcf-aed7-3f18661ddad0)

**Comment by crasher925** [comment]
nvm it was a throughput issue

**Comment by Paraplegix** [comment]
FIY (if you didn't know), you can enable "logistics" info that will tell you how much inserter/train you need. Top bar on the right, clic on the small truck. In this case, you would have seen that you need 37 red inserter across the 18 assembling machines.
