### ISSUE TITLE
See throughput effect of maximizing a plant number

### ISSUE THREAD

**Issue by vanatteveldt** [Helfima/helmod#54]
It would be nice to be able to specify a maximum number of factories per row, and then see what that does to input/output.

Explanation: Suppose I am making a red circuit plant, requiring also green circuits and cables.Now, the ideal ratio is 6 red : 1 green : 7 cable (2 for the reds, 5 for the green). 

![image](https://cloud.githubusercontent.com/assets/1736240/25888993/df98dda0-359a-11e7-8b4d-692787071c5b.png)

Now, I have a cool design that can only fit in 6 cable plants. What will that do to my output? 

Maybe this is a stupid idea, feel free (obviously) to close ;-)

**Comment by Helfima** [comment]
you can use "max per block" field in the recipe edition to limit the factory
