### ISSUE TITLE
[request] better calculation in Pyanadons

### ISSUE THREAD

**Issue by i-make-robots** [Helfima/helmod#540]
Pyanadons recipes seem to make Helmod go nuts.  Yesterday I wanted a full belt of lead plate and it said I'd need thousands of mining machines.  Apparently the regular Py players all know it's wonky and use a 3rd party app instead.  Sus!  Beautiful familiar Helmod should be good enough.

**Comment by Paraplegix** [comment]
I'm a regular Py player, never heard what you're talking about.

Base pyanodon recipe take 6 ore into 1 plate in 10 second.

Yellow belts are 15 items per second
To get 15 lead plate per second you need 15*10 = 150 stone furnace (using the base one) and 90 lead ore (15*6)
Getting 90 lead ore per second from fluid mining drill that have .5 speed mean you need 90/.5 = 180 mining drills.

Testing this in helmod give the correct results.

**Comment by Helfima** [comment]
you need more explanation of your problem
