### ISSUE TITLE
Multi output production lines and manual value for a dependance that is output too.

### ISSUE THREAD

**Issue by YPetremann** [Helfima/helmod#55]
The concept is simple, I need to setup a production line with yellow and red belts, underground belts and splitter as output. Once a recipe dependency is put, it's value is automatically set, but if the recipe is put a second time, it should let this one to be set manually

**Comment by Helfima** [comment]
I have already implemented an unlock, I think we have to think more

**Comment by YPetremann** [comment]
In that case, I think that is a locked recipe already exist, it should be unlocked by default.

**Comment by Helfima** [comment]
ready in version 0.4.7
![auto_unlink](https://cloud.githubusercontent.com/assets/20326713/26002279/73fecd84-372f-11e7-831e-59cf9fe90d6a.PNG)
blue: recipe added
red: is unliked beacause same name
green: recipe added but is linked with last recipe
