### ISSUE TITLE
Production % refuses to be set

### ISSUE THREAD

**Issue by i-make-robots** [Helfima/helmod#550]
Pyanadons + Alien life 2.1.42
Factorio 1.1.110
Helmod 1.0.14

Trying to split work evenly between two recipes.
click either one...
![image](https://github.com/user-attachments/assets/2472a417-f8b0-474b-bdaa-02969310940f)

then adjust production %...
![image](https://github.com/user-attachments/assets/6efbd510-2341-46d7-aa5d-a275ca880ac1)

Press enter -> value returns to 100%

Press tab -> value stays at 30%.  Close window, value is still 100%.  Reopen window, value is 100%.

**Comment by i-make-robots** [comment]
Eh, I meant to point the arrow to either of the last two recipes (fatty acids, pyanadons mod).  The problem is the same.

**Comment by Helfima** [comment]
hello matrix solver set the % production if you want change it use "computing by element"
![image](https://github.com/user-attachments/assets/4df81040-deeb-4585-966a-d15ae6e37f6e)
