### ISSUE TITLE
Copy & paste functions reverting some production line settings

### ISSUE THREAD

**Issue by pedter** [Helfima/helmod#553]
When copying and pasting a production line into a new, empty production line:
- All production blocks in the production line are set to _linked_ even if they were set to _unlinked_ in the original production line.
- All production blocks in the production line are set to _producer_ even if they were set to _consumer_ in the original production line.
- All production blocks in the production line are set to _computing by element_ even if they were set to _matrix solver_ in the original production line.

Options for _assembler limitation_ and _ingredient/product input_ appear to properly copy & paste as expected.

Editing to add on to this:
- Manually assigned production values are reset (for example: 1/6 blue science was reset to 1)
- Manually assigned main products are reset; this was supposedly fixed with #318 (for example: multi-phase oil was reset to carbon dioxide based on demand from prior recipes)
![Untitled](https://github.com/user-attachments/assets/99117273-4cc9-4365-9a6b-06c3df2d2239)

The general chaos shown in outputs & inputs of the pasted production line is a result of all other manually assigned production values also being reset. Manually correcting the information forgotten by copy/paste returns the pasted production line to intended design.

**Comment by Helfima** [comment]
fixed in v2.0.5
you can confirm is ok in last version

**Comment by pedter** [comment]
Originally I reported loss of data with copy/paste using v1.0.14, installed with the full Sea Block Pack. Today I am checking copy/paste data loss using v2.0.6 and only the default Spage Age installation.

(✗) Still broken / not working (not fixed between v1.0.14 and v2.0.6):
- Producer Block is still being reset to Consumer Block
- Matrix Solver is still being reset to Computing by Element
![Untitled](https://github.com/user-attachments/assets/201f91c3-2696-40f5-a4d8-11edfd172942)

(✓) Now working properly (fixed between v1.0.14 and v2.0.6):
- Manually-assigned production values are now properly retained
- Linked/unlinked recipe setting is now properly retained
- Manually-assigned main products are now properly retained

(✓) Still working properly (same behavior with v1.0.14 or v2.0.6):
- Ingredient Input/Output setting is still properly retained
- Assembler Limitation setting and values are still properly retained

**Comment by Helfima** [comment]
fixed in next version v2.0.7

**Comment by pedter** [comment]
Finally testing these (with 2.0.11) - all 7 of the original checks are now functioning as expected. Thanks!
