### ISSUE TITLE
Solar Energy Calculation

### ISSUE THREAD

**Issue by sub-kek** [Helfima/helmod#564]
I remember that before in this mod it was easy to calculate the required number of solar panels and accumulators. Now it is not and when I try to select the recipe “Accumulator” in the helmod tab I get an error.

![image](https://github.com/user-attachments/assets/13891d6c-76f7-401d-9400-5f14a8d4e19b)
![image](https://github.com/user-attachments/assets/9f73d641-b4aa-4e6c-8faa-075d492d31cf)

Is that the way it's designed or not?

commit: 10593f60f725e4ef4085c5069d72b9f461245a8f

**Comment by Helfima** [comment]
fixed in v2.0.5
