### ISSUE TITLE
Doesn't handle specific resolutions

### ISSUE THREAD

**Issue by YPetremann** [Helfima/helmod#57]
I usually play factorio on a 1280x1024 monitor and helmod is made with really specific resolutions in mind.

You should either way let the user set a custom resolution and let them choose if helmod would display in gui.center or gui.left (which would solve some problems where the helmod window could fit but is a bit out of the factorio window)

**Comment by Helfima** [comment]
yes it s a problem for the low resolution.
It is very complicated to have a consistent display and easy to use
in the next version you can choose left or center

**Comment by Helfima** [comment]
ready in version 0.4.7
You can choose location of panel and specific resolution
