### ISSUE TITLE
Minor issue - T1 assembling machines and beacon calculation v2.0.7

### ISSUE THREAD

**Issue by liqo-CZ** [Helfima/helmod#572]
When applying module priority on whole block/line, beacons get added even to T1 Assembling Machines, which I've recently found out can not be beaconed. Which results in following behavior: total number of beacons per block/line get (needlessly) increased, efficiency modules doesn't decrease T1 AMs el. consumption (correct), speed modules increase T1 AMs speed and el. consumption (incorrect). 

I understand that this is a minor issue and there aren't many people that use T1 Assembly Machines in late game, but I noticed this behavior and thought I let you know. Anyway love your mod and can not imagine playing without it anymore. <3 

![helmod_production_line](https://github.com/user-attachments/assets/2608ef5d-1677-4a46-917b-37b0200b737b)

**Comment by Helfima** [comment]
Fixed in v2.0.12
