### ISSUE TITLE
Recyling recipes seems to set some outputs to their minimum values

### ISSUE THREAD

**Issue by kotarou3** [Helfima/helmod#578]
![image](https://github.com/user-attachments/assets/c5046e35-cbd3-4a95-8f29-11645e58790c)

I only spot checked a few recipes, so it probably applies to other recycling recipes too.
But with the above examples, I would have expected output to be their average values rather than the minimum, resulting in:
 - Red circuit: **50** green circuit + **50** plastic + 100 copper wire
 - Blue circuit: 500 green circuit + **50** red circuit
 - LDS: **50** steel + 500 copper + **150** plastic

**Comment by Helfima** [comment]
Fixed in v2.0.12
