### ISSUE TITLE
Biolab 50% drain is not accounted for

### ISSUE THREAD

**Issue by jd284** [Helfima/helmod#579]
I usually have an infinite research at the top of a production block. Then I set it to 1000 science per time frame and size the factory accordingly.

When calculating the science packs needed, that means also 1000 each. That's correct for the standard lab, but Biolabs require only 50% as many packs (0.5 drain instead of 1), so it should be 500 instead. Helmod v2.0.12 still shows 1000 being needed however.

It's easy to correct for, but also easy to forget...

**Comment by Helfima** [comment]
fixed in v2.0.13
