### ISSUE TITLE
"Too many parameters" error when opening factory configuration to set modules

### ISSUE THREAD

**Issue by jcantara** [Helfima/helmod#580]
I seem to have gotten helmod into a state where it shows the below error when trying to configure the modules on some factories (but not all). I'm not 100% sure of what I did to create it in the first place; but I believe I was trying to configure module priorities (I didn't notice until quite a while later). So unfortunately I don't have a good "steps to reproduce". 

I also see the same error string in the "Administration" panel in the "Global" tab as the first item under "storage" (screenshot below). 

I'm running the latest version of factorio (2.0.23), with the space-age DLC, and latest version of helmod (2.0.12). Only a couple other mods are enabled: 

* VehicleSnap (2.0.0)
* Disco Science (2.0.1)

I have tried uninstalling/reinstalling the mod (within the factorio UI, and also removing the zip from local disk and having it completely re-download). 

Full error is: 
```
Too many parameters for localised string: 22 > 20 (limit). in property tree at ROOT.tooltip
```
Screenshots:
![helmod_bug](https://github.com/user-attachments/assets/ccdcf5a4-b2e7-45a2-8e2b-5ee0c11d5570)

![helmod_bug_2](https://github.com/user-attachments/assets/7bece2d0-357b-4c60-86c2-d3b7f435ddeb)

**Comment by Helfima** [comment]
you can use wrench icon for report bug
can you share your game? I need check where a tooltip has too many elements (probably)
after that you can user command `/helmod resetuserui`

**Comment by jcantara** [comment]
Hm, is there a good way to share a large save file? Github won't let me upload the zip larger than 25 MB (it's a 31 MB save file). I'll make a backup of the save, and try the other suggestions as well, thank you :)

**Comment by jcantara** [comment]
Here's the output of the bug report: 
```
---- Error ----
Too many parameters for localised string: 22 > 20 (limit). in property tree at ROOT.tooltip
---- Feature Flags ----
expansion_shaders:true
freezing:true
quality:true
rail_bridges:true
segmented_units:true
space_travel:true
spoiling:true
---- Mods ----
base:2.0.23
VehicleSnap:2.0.0
DiscoScience:2.0.1
elevated-rails:2.0.23
helmod:2.0.12
quality:2.0.23
space-age:2.0.23
```

**Comment by jcantara** [comment]
The command `/helmod resetuserui` did not seem to change anything, as well.

**Comment by jcantara** [comment]
Here's a google drive link to the file, if that's acceptable: https://drive.google.com/file/d/12YYwuj6zSl8iiPVYLrOMZn5rfmwUFkS4/view?usp=drive_link

**Comment by jcantara** [comment]
To reproduce the issue within the save, try to configure the factory settings on the red science (Automation science pack). Other production lines sometimes seem to work.

**Comment by Helfima** [comment]
I found the problem
![image](https://github.com/user-attachments/assets/972a152e-6ef6-418d-bc32-2972a6972297)
You have a priority module with 20 rows and that displayed in the default tooltip
After the command `/helmod resetuserui` you have clean all parameters, if you delete the recipe row and rebuild that must be ok

**Comment by Helfima** [comment]
that wil be fixed in next release
![image](https://github.com/user-attachments/assets/cba4e02d-ec19-4352-b2b5-1f28e3753577)

if you want use module priority
![image](https://github.com/user-attachments/assets/a8976e67-b2a8-4a23-b80d-c966aeffad71)
here that use 10 productivity module otherwise 10 speed module

**Comment by jcantara** [comment]
Excellent, that fixed it! thank you! Do you want me to close this issue?
