### ISSUE TITLE
2.0.12 Quality of buildings not stored when exporting/importing production line

### ISSUE THREAD

**Issue by EBTheHero** [Helfima/helmod#581]
When exporting and importing a production line, the quality of the buildings and beacons (not the modules within) is lost and reset to default/normal quality.

Repro steps:
Create a production line.
Set the quality of the building and beacon to uncommon or higher
Export to a string using "Upload to production line"
Import with "Download production line"

Current behavior:
Building qualities are not kept

Expected behavior:
Building qualites are kept

**Comment by Helfima** [comment]
fixed in v2.0.13
