### ISSUE TITLE
Pyanadon alternative energy incorrect water consumption and steam production

### ISSUE THREAD

**Issue by Morf2015** [Helfima/helmod#585]
In helmod 2.0.13 pyanadon alternative energy oil burner work incorrectly. It consumed wrong amount of water. And produce incorrect amount of 250 degree steam. Py electric boiler unavailable in steam recipe at all.
1 Helmod steam recipe. Steam per second
![2](https://github.com/user-attachments/assets/e5780f44-5314-4de6-bfd3-79ea5d608fc4)
2 Oil burner ingame description
![3](https://github.com/user-attachments/assets/c6b2f4d1-f073-4893-945c-97283a189d1e)
3 Ingame water consumption and steam production for 1 oil burner per minute
![4](https://github.com/user-attachments/assets/78bd11fe-5677-41b0-9b84-d69d270a48d3)

Pyanadon coal boiler also have issue with incorrect steam production
1 Helmod steam production per second
![5](https://github.com/user-attachments/assets/90d5531d-f1be-41ed-8601-39b9a1d9f09b)
2 Coal boiler ingame description
![6](https://github.com/user-attachments/assets/51cdc609-c89c-46ca-aa15-1a155e4a4b5b)
3 Ingame steam production for 1 coal boiler per minute
![7](https://github.com/user-attachments/assets/124aba95-ca05-4fa8-8ea9-a83bfb442f6c)

**Comment by Helfima** [comment]
I don't know anything about PY, when someone talks to me about a machine I need a screen of the icon otherwise I spend hours looking and if the name is incorrect.
Py electric boiler?

**Comment by Helfima** [comment]
![image](https://github.com/user-attachments/assets/9bcf0ff6-6056-4646-b1e0-f9d0ad67d44e)

**Comment by Morf2015** [comment]
Yes its item name py-electric-boiler
icon
![EB2](https://github.com/user-attachments/assets/620d6953-b71c-4e32-9e9e-ba2026e3c010)
![EB3](https://github.com/user-attachments/assets/4e50be2a-468e-4027-a827-1d292db93e8f)

**Comment by Helfima** [comment]
your recipe here for py-electric-boiler
![image](https://github.com/user-attachments/assets/749227d9-b609-442c-ad5e-72fe94aa9a6c)

**Comment by Morf2015** [comment]
I usually use this recipe for steam.
![S1e](https://github.com/user-attachments/assets/80584393-70ac-4ecc-be72-1bb1c0926be7)

And then edit it if needed. But now electric boiler unavalable from this menu.
![s2](https://github.com/user-attachments/assets/169b1b1d-c7fa-4535-9e9e-06f4bf58079c)
In old helmod for factorio 1.x (for example helmod 2.0.1) electric boiler was available from edit recipe menu directly
![S3](https://github.com/user-attachments/assets/82a0de2e-26f1-4013-a4b8-3cd48da36eeb)

**Comment by Helfima** [comment]
py-electric-boiler is not a boiler, is a machine and use a recipe. I can't do more.

**Comment by Morf2015** [comment]
Understood. Thank you for your reply. And what about wrong water consumption and steam production in oil burner and boiler? Can it be fixed?

**Comment by Helfima** [comment]
![image](https://github.com/user-attachments/assets/e4b53eb1-05a5-44a5-9154-451d18e04c83)
fixed in v2.0.14
