### ISSUE TITLE
Incorrect steam calculation in Pyanodons

### ISSUE THREAD

**Issue by florianschanda** [Helfima/helmod#587]
Hi, another bug that I noticed.

In Pyanodon's the steam boiler can make 7.5 steam/s, but in Helmod it's showing 10x that value, i.e. 75.

![image](https://github.com/user-attachments/assets/9b698491-7e6d-4c1c-9c35-bfefb0197322)
![image](https://github.com/user-attachments/assets/76ce330a-11a4-4175-8fda-7ff73e411dd5)

I notice that the water input is correct, just not the output.

**Comment by Helfima** [comment]
normaly fixed in v2.0.14

**Comment by florianschanda** [comment]
You are correct, it's fixed. Turns out if you ever select an older version of a mod, and then click update all; it keeps the old version.
