### ISSUE TITLE
Recipe Edit Issue

### ISSUE THREAD

**Issue by Snowmech** [Helfima/helmod#59]
I am using Reverse Factory mod. For some recipes, such as gears, this mod replaces the icon for factory selection, which can be corrected in options. However, it also replaces the recipe, allowing for the breakdown of gears, no matter what assembler is chosen.

**Comment by Helfima** [comment]
I have not understand your problem?

**Comment by Snowmech** [comment]
Other mods are overwriting your mod. With the mod: Reverse Factory; Gears outputs Iron Plate, Not Gear; Input Gear, Not Iron Plate.

**Comment by Helfima** [comment]
I see no problem?
![reverse_gear](https://cloud.githubusercontent.com/assets/20326713/25963406/6756dd0a-3681-11e7-9b38-79b4a5457c75.PNG)

**Comment by Snowmech** [comment]
So to produce gears, this is the product, you need iron plates. In your picture your product is iron plates, instead, and your ingredient is gears. So if I want to know how many assemblers i need making gears for turrets, I need to first get gears as my ingredient, and my product will be iron plates?

Please, take a closer look at your picture. Recycling and breaking down gears is Not the desired result.

**Comment by Helfima** [comment]
in this picture I have iron gear wheel recipe and reverse factory iron gear wheel
You must choose the expected result first, no?
![reverse_gear2](https://cloud.githubusercontent.com/assets/20326713/25970424/e47244d4-3698-11e7-9a05-380728b024dd.PNG)

**Comment by Snowmech** [comment]
When I chose Gears, wanting to produce gears, I only get the reverse. Right not I toggled off the reverse mod.
