### ISSUE TITLE
Final step not applying production bonus for the number of assembly machines

### ISSUE THREAD

**Issue by Liquid5n0w** [Helfima/helmod#6]
You can see in this screenshot when I add the modules they do not reduce the count on the number of machines I need.

![image](https://cloud.githubusercontent.com/assets/9867874/18357166/dc039d44-75bd-11e6-9015-1782c7496065.png)

![image](https://cloud.githubusercontent.com/assets/9867874/18357172/e640c552-75bd-11e6-8838-6e59ad126653.png)

**Comment by Liquid5n0w** [comment]
I just realised that this problem isn't only with the output step, but with every step.  If I add productivity modules totally +100% productivity, it should reduce the total number of machines needed by half as each machine is producing twice as much from the same materials.

**Comment by Helfima** [comment]
Yes i try it and it's ok, when using modules with productivity, altering the values of the necessary ingredients and so the following, not the current line.
no bug :)

**Comment by Liquid5n0w** [comment]
Maybe it's only a problem using the raw productivity modules from Bob's mods, as they are giving me this issue.

**Comment by Liquid5n0w** [comment]
I am now getting a negative number of machines when using productivity 2 from bobs mods:

![image](https://cloud.githubusercontent.com/assets/9867874/18399365/85b13686-769e-11e6-931b-e2603fdbbfda.png)

**Comment by Helfima** [comment]
I have added cap with 20% of speed and productivity
if u can test in game the limit effect in real cap, i need the right value
