### ISSUE TITLE
Should not use on_tick

### ISSUE THREAD

**Issue by YPetremann** [Helfima/helmod#60]
Since the mod is in majority getting event through keybinds and gui clicks, you should avoid to set any function to on_tick event.

As I understand, the on_tick function is used here to detect if any player is not initialized, in that case then it initialize the player, I would suggest you to hook such functions to on_player_created, on_player_joined_game and on_runtime_mod_setting_changed, so that it depends on really specific event that would not do useless executions each ticks.

**Comment by Helfima** [comment]
You're right, I do not know why at one time I had a problem with ui
