### ISSUE TITLE
Nuclear turbine does not show in summary, shows Steam engine instead

### ISSUE THREAD

**Issue by dtupper** [Helfima/helmod#62]
Issue: When I choose only the nuclear steam turbine in the power tab, the summary view shows the steam engine (boiler-powered) instead.

Replication steps: 

1. Create some production line with power requirements.
2. Click the Power tab.
3. Add the nuclear-powered steam turbine to your power list.
4. Go to the Summary tab.
5. The Summary will display how many steam engines are required instead of steam turbines.

**Comment by Helfima** [comment]
yes it's right
I must update summary with power tab or remove it

**Comment by Helfima** [comment]
now there are energy recipes
v 0.10.6
