### ISSUE TITLE
Ratios for Electric & Burner Drill Iron Ore Output Wrong

### ISSUE THREAD

**Issue by Lohengramm512** [Helfima/helmod#66]
It looks like your mod says it will take 48 Electric Drills to mine 100 Iron Ore per second, but it would actually take 191~ Electric Drills to mine 100 Iron Ore / sec because Electric Drills without mods mine 0.525 items / sec. (100 / 0.525 = 190.476~)

It also suggests 90 Burner Drills could output 100 Iron Ore per second, but their rate is 0.28 Iron Ore / sec, which would require 358~ Burner Drills to output 100 Iron Ore / sec. (100 / 0.28 = 358~)

I believe the fix would be changing the "nominal speed" from 2.1 to 0.525 for Electrics, since "Nominal Speed" doesn't really exist for drills, but that would at least get you the correct requirements for copper, coal, and iron. I get it that this isn't the easiest thing to deal with, but as it is right now I'm pretty sure the numbers provided are meaningless?

Proof: http://i.imgur.com/AWalfLx.png

**Comment by Helfima** [comment]
I have not validated if the calculation is correct, I have just added this option for the moment
I will check for the next version

**Comment by Helfima** [comment]
fixed Version 0.5.0
