### ISSUE TITLE
I updated your english localisation files

### ISSUE THREAD

**Issue by Arumba07** [Helfima/helmod#71]
I'm not sure how to get the .cfg to you, as this 'issue' tracker won't accept that filetype.  I could convert it to .txt, but that seems silly.

I'd also like to ask for a couple features/functions if possible?

1) A toggle to disable administrators from seeing all production blocks.  I often have many players join my games, create a block, do nothing with it, and then when I go to use Helmod myself I have to look through 25+ tabs, most of which are empty junk.
2) An option to disable the button in the corner, preferably a startup option.  I don't like duplication when it doesn't serve a purpose.  We have fantastic hotkeys (THANK YOU), so I don't need a button up there cluttering the interface.  It conflicts with other mods, pushes other gui-elements out of position, and I have never once clicked it.
3) Would it be possible to calculate the fuel cost to run burner entities?  Right now it shows 0 power usage for a stone furnace for example, but we know how much fuel they consume per second and can easily calculate the MJ consumption of the block.  It might not be the same type of power usage as the electric grid, but it *is* a type of power consumption.

Love the mod, really getting the hang of it, and I hope these suggestions help!  Let me know the best way to get these updated localizations to you.

**Comment by Helfima** [comment]
The best method to propose a language change is to use the "Pull Request" of this site or you can put them in a zip file
if you have few proposal, make few issues. :)

1. Ok I add this in a new issue
2. I like screen shoot when the are a problem, I'm not sure I understood this point
3. Ok I add this in a new issue

**Comment by Arumba07** [comment]
![image](https://user-images.githubusercontent.com/27012898/26903433-193a3ef2-4bab-11e7-945b-e576d8321690.png)

This top left button, the icon for and clickable gui element to open up the interface.  If you use hotkeys, it serves no purpose except to push other GUI icons further into the center of the game interface.  I would like an option to hide the button.

**Comment by Helfima** [comment]
english localisation files merged in version 0.5.6
