### ISSUE TITLE
Search filter lag in multiplayer

### ISSUE THREAD

**Issue by Arumba07** [Helfima/helmod#75]
When using the text string search filter, the game grinds to a halt for everyone on a server.  I believe the text string is search every tick for matches?  Perhaps it would be better to have it a static text string, with a 'search' button that is clicked just once?

![image](https://user-images.githubusercontent.com/27012898/26841747-7b3e51c2-4ab8-11e7-84d3-9a3771a1e132.png)

**Comment by Alxandr** [comment]
May I recommend (if it is indeed the case that it searches every tick) that you simply cache the search result, and only perform a new search whenever the text changes? That way, there is no change in functionality, only perf.

**Comment by Helfima** [comment]
in helmod settings, debug mod is "none" ?

**Comment by Arumba07** [comment]
Yes, default settings

**Comment by Arumba07** [comment]
Please consider joining our server to see a quick example of how bad the lag is in multiplayer. You can join our discord at ► Discord - http://Discord.gg/Arumba  and then use these links to download the pack:  
http://arumba.tv/media/ArumbaModPackDynamic.7z
http://arumba.tv/media/ArumbaModPackStatic.7z

**Comment by Helfima** [comment]
I have added option to enable filter on change text by default is disabled and use a button
I can't upload on factorio mod site, there a problem
[helmod_0.5.7.zip](https://github.com/Helfima/helmod/files/1083094/helmod_0.5.7.zip)

**Comment by Arumba07** [comment]
We tested this version and man, it is awesome.  We can use Helmod in multiplayer!!! YAY

One minor feature request?  Could the 'enter' key be made to click the apply button?  Also in places like changing the factory outputs, if the 'enter' key could click the 'Save' button that would be really great as well.
