### ISSUE TITLE
Code simplification

### ISSUE THREAD

**Issue by aubergine10** [Helfima/helmod#8]
I noticed [this pattern](https://github.com/Helfima/helmod/blob/master/core/elementGui.lua#L95) used in a lot of your code:

```lua
if key ~= nil then
  options.name = action..key
else
  options.name = action
end
```

That can be simplified to:

```lua
options.name = key and (action..key) or action
```

There's also this sort of thing:

```lua
if style ~= nil then
  options.style = style
end
```

An initial simplification is:

```lua
if style then --> nil is falsey, so we don't need to explicitly state it in this case
  options.style = style
end
```

But `nil` values in a table property are automatically removed, so we can further simplify it to (in most cases):

```lua
options.style = style
-- if style is nil, the options table won't have a style property
```

**Comment by Helfima** [comment]
I prefer to use the normal writing and test condition with right type
I use a lot of different language, I keep writing similar to read faster
My MOD have many line, I did not look at the intricacies of the code lua
but thanks
