### ISSUE TITLE
Omnimatter Interaction Bug

### ISSUE THREAD

**Issue by iamwyza** [Helfima/helmod#83]
The omnimatter mod has multiple levels of many recipes.  To help reduce the spam of this, after recipe level 2 of a specific recipe is researched, all entities that have that entity used, are updated to use the new one and then the previous level is disabled.  However Helmod still uses the values from the previous level.  Is there any way to detect when this event changes and update the recipe used?

**Comment by Helfima** [comment]
what you mean?
update the last factory or the last recipe?

**Comment by iamwyza** [comment]
He goes through and finds every factory that uses, for example, level 1 of a recipe, updates that factory to use level 2 of the recipe, then disables the level 1 recipe.  This event occurs when Level 2 of a given recipe is researched. The different between level 1 and level 2, is the ratios of useful products to bad bi-products.

**Comment by Liquid5n0w** [comment]
I am also having this issue.  We just started a MP game with omni, and any time you click the add recipe button in helmod, it locks up the server for everyone for about 10 seconds, making helmod unusable.

**Comment by Helfima** [comment]
tooltip cached i can't do more
