### ISSUE TITLE
Recipes trying to use machines they can't be crafted in

### ISSUE THREAD

**Issue by Arumba07** [Helfima/helmod#85]
http://i.imgur.com/3SLE5Gm.jpg

The recipe here for example, military science packs, is telling me that I need to use 10 level 1 assembly machines.  Unfortunately, assembly machine 1's can only craft recipes that have 2 components, while this recipe has 3.  This machine is incapable of doing this crafting job, so it probably shouldn't show up as a valid machine for this craft.

I would suggest a sanity check to make sure the machines listed in the Factory selection screen can actually handle the craft.

**Comment by Helfima** [comment]
fixed in version 0.6.8
