### ISSUE TITLE
Error on addding recipe

### ISSUE THREAD

**Issue by mik69** [Helfima/helmod#88]
Factorio 0.15.15 (win64), Reproduced on helmod 0.5.6-0.5.7. Works correctlyon helmod 0.5.5.

Add production block or recipe of inserter or assembling table, labolatory etc. ends the game with error:

> Error while running event helmod::on_gui_click (ID 1)
> LuaEntityPrototype doesn't contain key resource_categories.
> stack traceback:
> 	__helmod__/controller/PlayerController.lua:579: in function 'getProductionsCrafting'
> 	__helmod__/model/Model.lua:2233: in function 'getDefaultRecipeFactory'
> 	__helmod__/model/Model.lua:738: in function 'addRecipeIntoProductionBlock'
> 	__helmod__/selector/AbstractSelector.lua:296: in function 'on_event'
> 	__helmod__/dialog/Dialog.lua:152: in function 'send_event'
> 	__helmod__/controller/Controller.lua:226: in function 'parse_event'
> 	__helmod__/controller/Controller.lua:114: in function 'on_gui_click'
> 	__helmod__/controller/PlayerController.lua:98: in function 'on_gui_click'
> 	__helmod__/helmod.lua:155: in function 'on_gui_click'
> 	__helmod__/control.lua:32: in function <__helmod__/control.lua:31>

**Comment by Helfima** [comment]
Hi, I have missing update the minimal version of factorio, it works with factorio v0.15.17+
because resource_categories property is added at this version
if you want play with factorio 0.15.15 use only helmod 0.5.5
