### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by desep** [Helfima/helmod#90]
crash on try to chenge assembly machine
[img](https://monosnap.com/file/IbICLcnQilnVLfmsIjZOZCiZvbS0s5.png)

**Comment by desep** [comment]
https://mods.factorio.com/mods/Klonan/upgrade-planner 

The crashes started after installing this mod

**Comment by Helfima** [comment]
duplicate #89

**Comment by Helfima** [comment]
resolve in 0.6.0
