### ISSUE TITLE
Very slow to add recipes when there are many recipes in the game

### ISSUE THREAD

**Issue by Liquid5n0w** [Helfima/helmod#94]
Using Helmod with the Omni suite of mods causes a serious problem with adding recipes to a plan.  For me it locks up the game for about 5 seconds, but a larger problem for me is that trying to use helmod + Omni on a multiplayer server causes all players to lock up for those 5 seconds every time you try to add a recipe.

This makes helmod unusable with Omni, which is exactly the kind of mod you want it to be usable for.

Would it be possible to cache the recipe list so that it locks up once, but just loads the cache on future lookups?

**Comment by Helfima** [comment]
I see lag to display a big production line or a large list of recipe in the selector
I must analyse why in the new code we lost time to build display

**Comment by Helfima** [comment]
I have change code but I think the speed gain is only 40%
try v0.6.3

**Comment by Liquid5n0w** [comment]
Looks good, between that change and the removal of omni compression it works well.

**Comment by Helfima** [comment]
to further improve the speed of the selector it will be complicated.
