### ISSUE TITLE
Placement objects not loading

### ISSUE THREAD

**Issue by sm0ze** [Helfima/helmod#99]
Can see placement of objects in some parts of the screen and not in others.
Seems to start from top left corner to about that far across the screen. Same distance for no object from top to bottom of screen. Any zoom level has this problem

![sprite](https://user-images.githubusercontent.com/31851788/30274558-59614bf6-9741-11e7-97ed-fbbc51f8e222.png)
![nosprite](https://user-images.githubusercontent.com/31851788/30274563-5ef9b666-9741-11e7-9e39-393b2ccbf046.png)

**Comment by Helfima** [comment]
what's problem with my mod, is this an invisible frame?
perhap you can use in command prompt
`/c remote.call("helmod","close")`

**Comment by sm0ze** [comment]
problem only occurred for me when your mod was loaded regardless if it was just base game or with many other mods.
It also has stopped since yesterday after progressing in the save for a couple of hours without helmod loaded. Adding it back to the save at a later point seems to have done something. Sorry for the trouble.

**Comment by Helfima** [comment]
ok good game :)
